### ISSUE TITLE
webwork doesn't like scandinavian characters

### ISSUE THREAD

**Issue by skandix** [openwebwork/webwork2#1004]
I tried to make a course with the course title: "test_øæå" but it seems like webwork doesn't handle these so well. I'm running latest version from the master branch with docker.
![image](https://user-images.githubusercontent.com/2757177/64478366-e26c4200-d1a7-11e9-9851-063bca3f657e.png)

**Comment by taniwallach** [comment]
Right now the support for UTF-8 in WeBWorK is supported for the text of problems, student names, and in answers.

Several aspects of the system including the names of courses (which become part of database table names), email addresses, and several other things I cannot recall off-hand are still expecting 8-bit (Latin 1) characters. 

I don't recall off-hand whether the path to a PG file can contain non-Latin-1 characters.

**Comment by mgage** [comment]
There is a better chance that the WeBWorK-2.15 branch would handle this -- it won't surprise me if it doesn't.  We've been fixing one utf8 limitation at a time as they come up.  Thanks for the report. We'll look in to it.

**Comment by skandix** [comment]
will try the 2.15 branch instead then :smile:
