### ISSUE TITLE
Gateway quiz not properly respecting setting of separator in parserRadioButtons.pl

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1032]
Reported in: http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4000

Not clear is this is a PG issue or a webwork2 issue, as the setting works in regular homeworks and not in gateway quizzes.

**Comment by drgrice1** [comment]
The separator is respected, but the css styling on the page makes the spacing that they are attempting to use for the separator on the page not work.  I posted a detailed explanation on the forum.

**Comment by drgrice1** [comment]
This issue should be resolved by PR #1094.
