### ISSUE TITLE
Can't locate Apache/Test.pm in @INC 

### ISSUE THREAD

**Issue by tpegues2** [openwebwork/webwork2#1045]
Running Webwork 2.13 on RedHat 7.0

Can't locate Apache/Test.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl
/usr/lib64/perl5 /usr/share/perl5 .) at build/version_check.pl line 27.

checking whether to enable maintainer-specific portions of Makefiles... no
./configure: line 20252: -q: command not found
./configure: line 20266: -q: command not found
./configure: line 20270: -q: command not found
./configure: line 20274: -q: command not found
./configure: line 20274: -q: command not found
build/version_check.pl failed: no version_string found in '' for 'apache2'.
configure: error: Bad apache2 binary (/)
-> N/A
-> FAIL Configure failed for Apache2::Request. See /root/.cpanm/work/1571841418.19796/build.log for details.

**Comment by tpegues2** [comment]
That helped but now I get the message below.
The plan is to upgrade but we were trying to create our production environment in test so we can validate our upgrade.
Thanks!

==========================================
Please install mod_perl: 1.25 < version < 1.99
(Can't locate mod_perl.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /u
sr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 7.
) at Makefile.PL line 8.
BEGIN failed--compilation aborted at Makefile.PL line 18.
-> N/A
-> FAIL Configure failed for libapreq-1.34. See /root/.cpanm/work/1571929792.19284/build.log for details.

**Comment by drgrice1** [comment]
I don't think that this is an actual issue with WeBWorK, so I am going to close this issue.  If I am mistaken, then it may be re-opened.
