### ISSUE TITLE
Can't locate object method "remote_addr" via package "Apache2::Connection"

### ISSUE THREAD

**Issue by tpegues2** [openwebwork/webwork2#1051]
I am attempting to install and Webwork 2.13 from a production copy in preparation for an upgrade to 2.15 but can't get the restore to work in our test environment.  I am able to login but get the following error message. I am running it on RHEL7.

Error messages

Can't locate object method "remote_addr" via package "Apache2::Connection" at /opt/webwork/webwork2/lib/WeBWorK/Authen.pm line 958, line 755.
Call stack

The information below can help locate the source of the problem.

in WeBWorK::Authen::write_log_entry called at line 231 of /opt/webwork/webwork2/lib/WeBWorK/Authen.pm
in WeBWorK::Authen::verify called at line 321 of /opt/webwork/webwork2/lib/WeBWorK.pm

**Comment by drgrice1** [comment]
I think that this is not an issue with the WeBWorK code, and is an issue with the perl setup on your system.  As such it would probably be more appropriate to ask about this on the webwork forums.

In any case to try to help you diagnose your problem, you should try to run check_modules.pl and see if that reports an issue.  Particularly check to see if it reports an issue with the Apache2 modules.

**Comment by tpegues2** [comment]
Thank you!!!
I will take a look in these areas as I did have lots of issues installing the Apache2 module.
It finally installed after some time and the check_modules.pl came back clean but there may still be issues.

**Comment by taniwallach** [comment]
I think this may be related to what is fixed in https://github.com/openwebwork/webwork2/pull/1145 and has to do with the setting of `ServerTokens` in the Apache config.
