### ISSUE TITLE
Improve accessibility of AttemptsTable

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1055]
See http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4694

where the are proposals to improve the web accessibility compliance of WeBWorK by improving the material provided in the AttemptsTable:
  - index number column
  - change focus links to the relevant form elements (first element for MultiAnswer/matrix)

**Comment by pstaabp** [comment]
closing this since #2228 removes the attempts table.
