### ISSUE TITLE
Encapsulate javaScript associated with problems (either in header text or in the body of the problem)

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1061]
A long term project to avoid interference between fancier problems using javaScript when they are loaded on the same page as in Gateway quizzes or when viewed in the Homework sets editor

1. there must be javaScript call or framework that keeps you from loading a javaScript function or file twice.  That would be a useful addition, but doesn't seem to be immediately necessary.
2. We should also create a means of encapsulating problems when necessary (iframes?) Even for ordinary problems the CSS files associated with downloading Sage applets conflict with the CSS that decorates the Next/Previous buttons and some other checkbox items that instructors see. (see PR #1026)

**Comment by Alex-Jordan** [comment]
I've been learning about shadow DOM recently in the context of web components. It looks like a promising way to isolate javascript.

**Comment by Alex-Jordan** [comment]
@drgrice1 Has your work over the past few years addressed the concerns here?

**Comment by drgrice1** [comment]
Yes, mostly.  The `ADD_JS_FILES` and `ADD_CSS_FILES` methods prevent loading of JavaScript or css multiple times.  Encapsulation is not entirely possible without iframes, but even better is to just take the requisite care to do things right and not cause conflict.  That is make sure to scope css properly, and use proper scope and try not to pollute the global namespace for JavaScript.  This is done with all of the JavaScript and css used by PG and the macros contained in the repository directly already.  Switching to using modules for JavaScript will make this easier too (and that is probably coming soon).

**Comment by drgrice1** [comment]
I am going to close this.  This is a general issue that will always be there, but we don't need this here to remind us.  There are always ways that problems can inject javascript and css that can cause issues outside of a problem unless we really go with an iframe.  That has other issues that are not good.  There are protections in place to contain the our internal javascript and css.  A problem author that is adding their own javascript or css needs to follow proper scoping rules.
