### ISSUE TITLE
2.15 Upgrade Documentation?

### ISSUE THREAD

**Issue by thatchermo** [openwebwork/webwork2#1068]
I'll be posting the same question on the Moodle forums as well--apologies for the double post, but not sure where the best place is.

I did a dumb thing--doing a pull of the master branch, thinking it would give me any small updates to 2.14 (since no mention is made on the main site of 2.15 being the new version), and instead got a pull of 2.15. 

I see now that 2.15 was merged with master in October, but there doesn't yet seem to be any upgrade documentation for moving from 2.14 to 2.15. The Release Notes for 2.15 don't look like they're in a finished state, and what earlier information for beta testers I've found also doesn't seem to give a complete list of what to update to go from 2.14 to 2.15.

Any help in finding that documentation would be appreciated!

As an aside, I note that the "Branching and Release Model" document seems to indicate that the master branch always represents the current release, so I'm a little perplexed as to why the main page doesn't list 2.15 as the current release, but that might be due to a misunderstanding of what "current release" means.

As a second aside, this page: http://webwork.maa.org/wiki/Upgrading_WeBWorK_with_Github#.XhZBKdlMGAk (which is the most obvious page about upgrading) also doesn't seem to have complete information.

Again, thanks for any help you can give!

**Comment by drgrice1** [comment]
The most appropriate place for this is on the Moodle WeBWorK forums.

Yes, the documentation for WeBWorK 2.15 needs to be done.  If you want help on upgrading, post on the forums and we will help you there.

If you don't want to upgrade and want to stick with WeBWorK 2.14, then run the following commands:
```
cd /opt/webwork/webwork2
git checkout -b WeBWorK2.14+ WeBWorK2.14+
```
If you also pulled the master branch of pg then run:
```
cd /opt/webwork/pg
git checkout -b PG-2.14+ PG-2.14+
```
If you also pulled the master branch of MathJax then run:
```
cd /opt/webwork/MathJax
git checkout legacy-v2
```
If you have non-standard installation locations, you may need to adapt the cd commands for the different locations.  That last command will be necessary even if you are upgrading to WeBWorK-1.15.

**Comment by thatchermo** [comment]
Thanks for the help!

**Comment by drgrice1** [comment]
I am going to close this issue, as it is not really an issue.  Although, this does point out the need for an update to the documentation.
