### ISSUE TITLE
Score for homework?

### ISSUE THREAD

**Issue by yjp20** [openwebwork/webwork2#1095]
Currently, the main student page for webwork2 shows scores only for gateway-type assignments. Maybe homework assignments should similarly show their score or completion as it will help students keep their progress at a glance without having to manually check each and individual problem set.

Reading the source code, it seemed like the scores were hidden very intentionally, but unless I'm missing something I can't think of a reason why that would be the case.

I'm happy to work on this PR as it looks pretty straightforward, but I wanted to know what the people here thought before I spent the time.

**Comment by mgage** [comment]
I'm sure the reporting can be improved, but I want to make sure that you have looked at the "Grades" link in the left margin of each main page.  I've included a screen shot below from a few semesters ago. 

![Screenshot 2020-03-11 08 55 58](https://user-images.githubusercontent.com/1203580/76419164-4994ca00-6376-11ea-8f81-0cd31d8af46e.png)

Here is another report mechanism for homework set page. It is not current part of WeBWorK
but is a Chrome web app only add on.
![Screen Shot 2020-03-11 at 9 01 08 AM](https://user-images.githubusercontent.com/1203580/76419561-ea838500-6376-11ea-8d8d-c66ef08fb1ca.png)

It was created by Jeremy Spiro. Mentioned at https://webwork.maa.org/moodle/mod/forum/discuss.php?d=4666#p13807


the git hub is at: https://github.com/spirography/webwork-helper

It would be great if we could either 
1. create a similar web-helper for firefox
2. even better, incorporate the javascript into webwork itself.

Notice also that MathQuill overlaps with the webwork-helper in that it gives feedback
on formula entry.

Glad you are interested in helping out. We need help from everybody if we are going to make WW succeed.  

You may still want to improve the existing grade reporting as well-- but I wanted to make sure you were aware of what already exists.

**Comment by yjp20** [comment]
I didn't see the grades tab; it's more or less what I was looking for.
Thanks.
