### ISSUE TITLE
Versioned hardcopy fails if no non-versioned sets in course

### ISSUE THREAD

**Issue by drdrew42** [openwebwork/webwork2#1103]
## To duplicate:
1. courseName_set table in db must have **only** /gateway/ assignment type 
1. have some version(s) created for at least one set, for at least one user
1. login with admin, become effectiveUser = any user with a version created
1. attempt to generate hardcopy for that versioned set for any users with error message: "can't generate hardcopy for set ''effectiveUser!setName,vN!N' for user 'userName' -- set is not assigned to that user."

Even if the versioned set has been assigned to that user, this error message occurs

Check the web inspector, look at the parameters passed when making the request (click Generate Hardcopy...), you will see that the requested set(s) are all of the form `effectiveUser!setName,vN!N` 

## Suspected diagnosis:

I suspect this is due to line 115-117 of WeBWorK::HTML::ScrollingRecordList:
```perl
my $class = ref $Records[0];
...
my @keyfields = $class->KEYFIELDS;
foreach my $Record (@Records) {
	push @ids, join("!", map { $Record->$_ } @keyfields);
}
```

Because there are no non-versioned sets passed to ScrollingRecordList, the first record is a versioned one, and has been altered by 415-430 of WeBWorK::ContentGenerator::Hardcopy
```perl
	# we also want to get the versioned sets for this user
	# FIXME: this is another place where we assume that there is a 
	#    one-to-one correspondence between assignment_type =~ gateway
	#    and versioned sets.  I think we really should have a 
	#    "is_versioned" flag on set objects instead.
	my @versionedSets = grep {$_->assignment_type =~ /gateway/} @GlobalSets;
	my @SetVersions = ();
	foreach my $v (@versionedSets) {
		my @usv = map { [$eUserID, $v->set_id, $_] } ( $db->listSetVersions( $eUserID, $v->set_id ) );
		push( @SetVersions, $db->getSetVersions( @usv ) );
	}
	# FIXME: this is a hideous, horrible hack.  the identifying key for 
	#    a global set is the set_id.  those for a set version are the 
	#    set_id and version_id.  but this means that we have trouble 
	#    displaying them both together in HTML::scrollingRecordList.  
	#    so we brutally play tricks with the set_id here, which probably
	#    is not very robust, and certainly is aesthetically displeasing.
	#    yuck.
	foreach ( @SetVersions ) { 
		$_->set_id($_->set_id . ",v" . $_->version_id); 
	}
```

I might be wrong. I still cannot exactly tell how these blocks (or the code surrounding them) have ended up producing the situation I've described.

However, once I found out that I'm able to fix this issue by creating _any_ non-gateway set, I gave up. That's a much easier fix.

For the record, this situation came up because we're rolling out WeBWorK sections for large-scale testing as part of our remote-instruction plan. These sections are not used for homework, just for final exams. I doubt I'd ever have encountered this otherwise.

**Comment by drgrice1** [comment]
This has been fixed.
