### ISSUE TITLE
timing.log fails to keep up and record data when server under severe load

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1104]
I did some ad-hoc load testing using "siege" to hit html2xml problems, and during the tests, when 1800+ render requests were being processed by 80+ Apache mpm_prefork processes, the timing.log file was collecting data and under 10% of the calls seem to have been logged.

It seems that the current logging mechanisms are not up to severe load.

My timing.log file was on a NFS mount which was mounted into a Docker container in which WW was running.

Has anyone else noticed issues with this?

**Comment by drgrice1** [comment]
I am closing this as it is not valid for current versions of webwork2.
