### ISSUE TITLE
redesigning json format

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1114]
Currently the json format for html2xml is like this:
```
{ 
    "body_part001" : "<body>\n", 
    "body_part100" : "<div class=\"container-fluid\">\n<div class=\"row-fluid\">\n<div class=\"span12 problem\">\n",
    ...
    "head_part010" : "<head>\n<meta charset='utf-8'>\n<base href=\"TO_SET_LATER_SITE_URL\">\n<link rel=\"shortcut icon\" href=\"/webwork2_files/images/favicon.ico\"/>\n",
    ...
    "hidden_input_field_answersSubmitted" : "1",
    ...
    "internal_problem_lang_and_dir" : "lang=\"en\" dir=\"ltr\" ",
    "real_webwork_FORM_ACTION_URL" : "https://webwork-dev.aimath.org/webwork2/html2xml",
    "real_webwork_SITE_URL" : "https://webwork-dev.aimath.org", "root_open" : "<html lang=\"en-US\">\n",
    "score" : 0
}
```

I am thinking about giving the object more structure in two ways.

1. Structurally separate "head" versus "body" versus etc.

1. Move the ordering that is encoded with those three digits at the end of keys to an array structure.

So like:

```
{
    "preamble" : [
        { "document_declaration" : "<!DOCTYPE html>\n"},
    ],
    "root" : [
        { "open" : "<html lang=\"en-US\">\n"},
        { "close" : "</html>\n"}
    ],
    "head" : [
        { "css" : ...},
        { "javascript" : ...}
        ...
    ],
    "body" : [
        ...
    ],
    ...
}
```

 Does this sound agreeable?

There is an email thread where I started discussing this with @mgage and @taniwallach. Now moving here for more public comment.

**Comment by Alex-Jordan** [comment]
I've done some restructuring today. To see it, first orient yourself by looking at [this problem](https://webwork-dev.aimath.org/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;sourceFilePath=Library/Union/setLimitContinuity/ur_lr_5_4.pg&amp;displayMode=MathJax&amp;courseID=anonymous&amp;userID=anonymous&amp;course_password=anonymous&amp;outputformat=simple). Then change the output format to `json`, seeing the [same problem's json output](https://webwork-dev.aimath.org/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;sourceFilePath=Library/Union/setLimitContinuity/ur_lr_5_4.pg&amp;displayMode=MathJax&amp;courseID=anonymous&amp;userID=anonymous&amp;course_password=anonymous&amp;outputformat=json). View the source to see how the `json` is structured.

To the keys like `body` and `head`, I might add one more key-value pair with key `order` and its value is an array with the names of the "body parts" in their canonical order. A convenience for using this.

For PreTeXt and Runestone use, I think we will jettison `head` and other things, and supply other CSS and JS (for knowls, etc.) ourselves. And we will have to write javascript that manipulates the internals of `body->problem` to a degree. Paths to images and certain other things will need that.

But my point with that last paragraph is to explain why the semantic breakdown of the pieces is useful. 

I'm interested in commentary and suggestions about what you see here. I may open a pull request soon, where discussion can continue.

**Comment by taniwallach** [comment]
To anyone else following this - the JSON output should be viewed as "raw" output, and not as a browser is likely to render it automatically.

@Alex-Jordan It looks really good. Much more logically organized than the initial approach. It's nice how you added the answerHash data into the JSON output. 

As I looked it over, I realized that it probably makes sense to split `submit_buttons` into 2 items, as at times the intermediate system may want to leave out the "Show correct answers" option, which would be easier if it were separated out in advance. Of course, the intermediate system would also want to internally check when a submission was received that an allowed mode of use ("submit", "preview", "show correct answers") was used and not just rely on not providing buttons not intended to be available.

**Comment by Alex-Jordan** [comment]
And here's another idea. Is there any reason not to drop the entire unabridged response hash into json output? For this no template is needed. [Here](https://webwork-dev.aimath.org/webwork2/html2xml?&problemSeed=1&answersSubmitted=1&AnSwEr0001=x&sourceFilePath=Library/Union/setLimitContinuity/ur_lr_5_4.pg&displayMode=MathJax&courseID=anonymous&userID=anonymous&course_password=anonymous&outputformat=everything) is an example. 

At least for PreTeXt, I can see building HTML from this to insert in the right place. If I knew more, it seems like something where someone could write a general use javascript API to do a lot with.

**Comment by taniwallach** [comment]
About the idea for a `json_minimal` - I can understand where you are coming from, but until there are systems really using the json data to create embedded problems, it is really hard to know what the "right" answer is.

About the extra hash - if someone has use for this, then making it available would be good, and it is apparently not difficult to provide it. For now, I see no reason not to include it.

One thing to consider is that we might prefer to try to have a single sufficiently generic piece of code to create the various JSON output formats and not have several files of code with much duplicated code. Otherwise, over time maintenance will become even more tedious and complicated. I would hope that it would be feasible to set up the JSON output code to respond to some new control settings and adjust its behavior accordingly. Then these additional features could be turned on and off as desired by the "user" and we would have a single Perl code file generating the various forms of output. However, it could be that such an approach would make the code so complicated that having multiple code files with very similar code might be faster/simpler - at least for now.

**Comment by Alex-Jordan** [comment]
Here is something to look at: https://spot.pcc.edu/~ajordan/temp/webwork-preview/section-1.html
Click a WeBWorK icon to activate a problem.

This is the PreTeXt "sample chapter", intended to demonstrate the capacity for PreTeXt-WeBWorK integration. Except this version is experimental. It is grabbing the full response hash as JSON, and if you look at the source, you can see my crude javascript building the HTML that wraps around the problem instead of using a `_format` template. (There are styling issues which you can ignore for now.)

The question I have is, should I preserve the current `json_format.pl` template? Or I could turn it into an empty template that just outputs JSON like [this](https://webwork-dev.aimath.org/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;problemSource=RE9DVU1FTlQoKTsKbG9hZE1hY3JvcygiUEdzdGFuZGFyZC5wbCIsIk1hdGhPYmplY3RzLnBsIiwiUEdNTC5wbCIsIlBHY291cnNlLnBsIiwpO1RFWFQoYmVnaW5wcm9ibGVtKCkpO0NvbnRleHQoJ051bWVyaWMnKTskYSA9IHJhbmRvbSgxLCA5LCAxKTsKJGIgPSByYW5kb20oMSwgOSwgMSk7CiRjID0gQ29tcHV0ZSgkYSArICRiKTsKCkJFR0lOX1BHTUwKQ29tcHV0ZSB0aGUgc3VtIG9mIFtgWyRhXWBdIGFuZCBbYFskYl1cdGV4dHs6fWBdCgpbYFskYV0gKyBbJGJdID1gXSBbX117JGN9ezV9CgoKRU5EX1BHTUwKCkJFR0lOX1BHTUxfU09MVVRJT04KW2BbJGFdICsgWyRiXSA9IFskY11cdGV4dHsufWBdCgoKRU5EX1BHTUxfU09MVVRJT04KCkVORERPQ1VNRU5UKCk7&amp;displayMode=MathJax&amp;courseID=anonymous&amp;userID=anonymous&amp;course_password=anonymous&amp;outputformat=everything) (be sure to view source after following that link). And then it falls on the client end to create the HTML.

If I preserve the current `json_format.pl`, then I need to make an empty `something_format.pl` template so PreTeXt can move on with what we're doing in that first link. For now I just called it `everything_format.pl` but if it goes this way, it should have a better name. Any suggestions?

I'm not planning to follow up on the `json_minimal.pl` idea from earlier in the thread now.

**Comment by taniwallach** [comment]
@Alex-Jordan I think the "raw" format provided the features you wanted, and I am getting data using the draft feature from https://github.com/openwebwork/webwork2/pull/1426.

I suspect that we can close this issue.

**Comment by Alex-Jordan** [comment]
Yes, thanks for reviewing issues.
