### ISSUE TITLE
Docker issue: Changes in localOverrides.conf not reflected after rebuild 

### ISSUE THREAD

**Issue by RussellSteele** [openwebwork/webwork2#1117]
I've been trying to test the webwork docker installation with Rserve enabled from the latest git version.  However, I need to enable Rserve in the pg environment variables in order to use R in WebWork.  I've created and edited localOverrides.conf so that the appropriate line is uncommented and then rebuilt the docker app, but trying to view questions that use Rserve indicates that the PG variable has not been set.  In fact, when I go to the docker installation via docker exec -it webwork2_app bash , the changes in localOverrides.conf are not reflected.  

These two lines when running docker-compose up are suspicious to me: 

app_1  | Creating a new /opt/webwork/webwork2/conf/site.conf
app_1  | Creating a new /opt/webwork/webwork2/conf/localOverrides.conf

If these exist already in the directory I'm running the build from, should they be re-created? 

I apologize if this is something obvious and my understanding of how Docker works is admittedly weak, but it seemed as if most of the previous issues with Docker and Rserve had been resolved.

**Comment by taniwallach** [comment]
Docker images are "static" and changes inside them do not persist after a shutdown+restart.
Locally modified files should be edited outside the image, and mounted using a suitable line in `docker-compose.yml`.
See: https://github.com/openwebwork/webwork2/wiki/Docker---things-to-get-used-to-(and-avoid-surprises)
