### ISSUE TITLE
CentOS 8 install failure

### ISSUE THREAD

**Issue by mjsaltzman** [openwebwork/webwork2#1119]
Created configuration for CentOS 8 (see pull request https://github.com/openwebwork/ww_install/pull/12) and attempted to install wtih ww_install script. Install terminates in section `Checking for required perl modules and external programs...` with this error:
```
** Apache2::Request found, but failed to load: Can't load '/usr/lib64/perl5/vendor_perl/auto/APR/Request/Apache2/Apache2.so' for module APR::Request::Apache2: /usr/lib64/perl5/vendor_perl/auto/APR/Request/Apache2/Apache2.so: undefined symbol: apreq_handle_apache2 at /usr/lib64/perl5/DynaLoader.pm line 193, <DATA> line 755.
 at /usr/lib64/perl5/vendor_perl/Apache2/Request.pm line 3.
Compilation failed in require at /usr/lib64/perl5/vendor_perl/Apache2/Request.pm line 3, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/lib64/perl5/vendor_perl/Apache2/Request.pm line 3, <DATA> line 755.
Compilation failed in require at (eval 699) line 1, <DATA> line 755.
BEGIN failed--compilation aborted at (eval 699) line 1, <DATA> line 755.

Missing module.  Sorry!  Try adding this module to your distribution file in distros. at bin/ww_install.pl line 1090, <DATA> line 755.
```
This apparently has to do with changes in packaging for Perl or libapreq2 because in CentOS 7 it works fine. In CentOS 8 and recent Fedoras,
`perl -MApache2::Request -e 1`
fails with the same error. Note that in both CentOS 7 and CentOS 8, apreq_handle_apache2 is defined in /usr/lib64/httpd/modules/mod_apreq2.so.

**Comment by taniwallach** [comment]
The problem with `libapreq2` on RHEL/CentOS 8 is a known problem, and Fedora/RedHat is apparently not planning to "fix" it.

See: https://bugzilla.redhat.com/show_bug.cgi?id=1526746

For what is it worth - the installation manual for WW 2.16 on RHEL 8 uses a custom Perl via Perlbrew, which works around the problem.  https://webwork.maa.org/wiki/Installation_Manual_for_2.16_on_RHEL8#Apache_2_and_mod_perl

That approach should probably be suitable, up to minor changes, for CentOS 8.

I'm closing the issue, as it is not a problem with WeBWorK per se, but with the Perl / libapreq2 on RHEL 8.
