### ISSUE TITLE
Disabling MathQuill for specific problems / parts of problems

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1155]
I'll  revisit an old suggestion: Can we create a mechanism where a problem author can mark an entire question or a specific input field to be omitted from the MathQuill handling?

Even just the second idea with the use of CSS `:not()` should help solve the problem of an overly broad initial selector. (https://developer.mozilla.org/en-US/docs/Web/CSS/:not)

For the general "skip MQ" for this problem, I'm not sure what would be the simplest mechanism, maybe setting a CSS class or a JavaScript variable which when true would "turn off" the MathQuill processing for the current page (or better yet only for DOM descendants of where the class was set).

For the specific input fields exception - let's assume that we will soon be able (in PG) to add additional class names (and style attributes, etc.) to input fields via some sort of extension of the `ans_rule()` method, so we could have a skipMQ class for this purpose. (See https://github.com/openwebwork/pg/issues/444 ) I intend to work on implementing that within the next few months (and sooner would be better for me also).

Note: The `openDiv()` support already supports creating a DIV with a given class name. See: https://github.com/openwebwork/pg/commit/da0f007e17bd25d220328f3dba2f5f8d3a2585d7#diff-2c3e0f1c9ff2f13866441f52d449f855

_Originally posted by @taniwallach in https://github.com/openwebwork/webwork2/pull/1071#issuecomment-580703131_

**Comment by taniwallach** [comment]
There is also some interest in disabling MQ for a problem, at the "webwork2" level rather than just at the PG level.

This probably requires DB support in the settings for a problem in the DB.

**Comment by taniwallach** [comment]
Prior discussions about options was in the thread from PR https://github.com/openwebwork/webwork2/pull/920

**Comment by taniwallach** [comment]
See: https://webwork.maa.org/moodle/mod/forum/discuss.php?d=5009

**Comment by taniwallach** [comment]
@drgrice1  mentions an approach he has for per-input bypass in https://github.com/openwebwork/webwork2/pull/1071#issuecomment-580717220

@drgrice1 Would you share the hack in a post here.

**Comment by drgrice1** [comment]
Sure. I have attached a patch that does this. This patch applies cleanly to WW 2.15, and applies with minor offsets to the develop branch.

The first thing that it does is removes the css code that hides all text inputs with the class codeshard, and instead hides those text inputs in javascript. Next a check is added in ProblemUtil.pm where the hidden MathQuill responses are inserted for "disabled" in the (largely undocumented) mathQuillOpts flag that you can already pass to the answer hash via a MathObject's cmp method, and in that case it doesn't add the hidden MathQuill response, in which case the javascript ignores that answer.

To use this use `$ans->cmp(mathQuillOpts => "disabled")`.  Note that this is all or none for the answer blanks in a MutiAnswer object with `singleResult => 1`.

Of course you need admin access to the server to apply this patch. It is created with git diff, and so applies at a patch level of 1. (Apply with patch -p1 < per-response-disable-mq.patch run from the directory /opt/webwork/webwork2.)

per-response-disable-mq.zip

**Comment by taniwallach** [comment]
This was addressed in WW/PG 2.16:
  - https://github.com/openwebwork/webwork2/pull/1288
  - https://github.com/openwebwork/pg/pull/555
