### ISSUE TITLE
ERRORS in rendering problem: ... Unrecognized response type: at [PG]/lib/Rserve.pm line 26

### ISSUE THREAD

**Issue by justineuro** [openwebwork/webwork2#1168]
Hi!

Has anyone encountered a problem similar to the one depicted in the image below (involving WW problems that require an R server,e.g., the ones found in _Statistics -> Simple linear regression -> Hypothesis tests_).  I would be very much interested in a workaround or a patch for it.  Thank you in advance for whatever assistance anyone can extend!

![ww-Screenshot from 2020-12-20 07-19-21a](https://user-images.githubusercontent.com/7970053/102701813-15035680-4296-11eb-9d5c-783e676dde1a.png)

**Comment by drgrice1** [comment]
Do you have an rserver set up for your webwork server to access?  I get the same error as you on a server that does not have access to an rserver.  However, on another server that does have access to an rserver the problem renders fine.

**Comment by justineuro** [comment]
Yes, an R server is installed (`r-cran-rserve/focal,now 1.7-3.1-2 amd64 [installed]`) and runs in port 6311.

**Comment by drgrice1** [comment]
There is a problem with the Ubuntu r-cran-rserve package if r-base is 3.5.0 or newer (which it is on focal).  Uninstall that package (but leave the r-base package installed), and run
```
sudo Rscript -e 'install.packages("Rserve", repo="http://rforge.net", type="source")'
```
to install the latest version of the rserver.

**Comment by justineuro** [comment]
Thank you very much!  That is indeed a fix to it!  The two WW problems are now properly rendered (please see the two attached images). 

![Screenshot from 2020-12-20 09-41-53a](https://user-images.githubusercontent.com/7970053/102703311-3bca8880-42a8-11eb-8acd-f536c415f2d4.png)

![Screenshot from 2020-12-20 09-42-28a](https://user-images.githubusercontent.com/7970053/102703315-4422c380-42a8-11eb-8b25-3293da6c685d.png)

Wishing hou all the very best!

**Comment by justineuro** [comment]
May we close this now?

**Comment by drgrice1** [comment]
You can close it.

**Comment by justineuro** [comment]
Many thanks again for your generosity!
