### ISSUE TITLE
Provide PG version to the PG evaluator

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1204]
@taniwallach: I was looking for something like that, but as of yet I have not found a way to obtain the PG version in a PG problem.  Seems like something that should be available though.  And yes, that would certainly be better.

_Originally posted by @drgrice1 in https://github.com/openwebwork/webwork2/issues/1121#issuecomment-782742255_

**Comment by taniwallach** [comment]
I suggest making it part of IO.pm which already interacts with the disk (we tried to keep all of the "dangerous" disk interaction in one place so that we could trouble shoot errors better).   Give IO.pm a subroutine that reads the PG_version file (and sanity checks that the version is written correctly). You can also have another that reads the webwork2 version file.  Then export the ability to read that value to PGcore and perhaps further to PG.pl or PGbasicmacros.pl so that the version can be easily checked.  webwork2 has access to the version files, but PG did/does not as far as  I know

_Originally posted by @mgage in https://github.com/openwebwork/webwork2/issues/1121#issuecomment-782751039_

**Comment by drdrew42** [comment]
fixed by openwebwork/pg#530
