### ISSUE TITLE
Set Detail 2 for a GW quiz version uses wrong seeds to render student version

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1210]
I make my way to the Set Detail 2 page for a student's quiz version. This is the page where you might manually edit a student's scores, prior to Glenn's manual problem grader. I have to get there in an awkward way: Classlist Editor, then click the #/# in a student's row that shows how many sets are assigned to them, then scroll down to the quiz version and click it.

I see problems and the seeds that were assigned to the student. If I click to render problems, they do not use the stated seeds. I haven't explored what seed it uses: my own seed, some seed that was set for the global quiz, or some default. But it's not the student's seed.

I was helping an instructor over the phone and we both were at the same place and rendered problems, and got confused that the problem details did not match. Even though we saw the same seed numbers.

**Comment by drgrice1** [comment]
I noticed that if you click on the button to "Open in New Window" then it does show the problem using the student's seed.  The problem you get when you click "Render Problem" seems to use the same seed that is used when you click "Render Problem" from the unversioned set detail page for the quiz.  I don't know where that seed comes from.

It would be good if both of those buttons would use the student's seed when you are viewing the set detail for a student's specific quiz version.

I also agree that it is tedious to get to that page.

**Comment by drgrice1** [comment]
By the way, utilizing the "Open in New Window" button to see if the seed was the student's or not revealed a bug in the "in problem grader".  I have pushed a fix for that to the pull request.

**Comment by drgrice1** [comment]
I noticed that this is the same behavior as for homework sets when viewing a student's data in the set detail page.  Opening the problem in a new window uses the student's seed, and rendering the problem in the page uses your seed.

**Comment by Alex-Jordan** [comment]
#1211 fixed this.
