### ISSUE TITLE
Make decision on old browser support

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1217]
Another thing we need to discuss is how far back we want to go with browser support.  At this point, I think the only sane thing to do is to go no further back than IE 11.  Although, if no one is opposed, I would be up for dropping all IE support entirely.  That really opens up doors.

_Originally posted by @drgrice1 in https://github.com/openwebwork/webwork2/issues/1167#issuecomment-787064558_

**Comment by drgrice1** [comment]
Note that the decision to move to MathJax 3 forces our hand on going no further back than IE 11, as it does not support anything before that.

**Comment by taniwallach** [comment]
Microsoft is dropping support for IE 11 also:

https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666
  - March 9, 2021 - "Edge Legacy End Of Life"
  - August 17, 2021 - M365 stops supporting IE 11,

I don't think we need to wait that long.I would say that with WW 2.16 planned for release after March 9, 2021 - we can drop support for IE 11 in WW 2.16.

**Comment by drgrice1** [comment]
I think that at this point everything in webwork still works with IE 11.  I agree with dropping support for IE 11, but we also don't need to go out of our way to remove support.

**Comment by drgrice1** [comment]
IE 11 support is now officially gone.
