### ISSUE TITLE
Implementing LTI advantage should be a priority

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1222]
LTI Advantage  (LTI 1.3) supposedly allows the ability to pass back an entire gradebook from WeBWorK to the LMS.  http://www.imsglobal.org/lti-advantage-overview
Not all LMS's implement this new standard but they will soon.
We'll try to have things ready on our end. IMS Global suggests targetting LTI 1.3 as opposed to various LTI 1.2 ( a transition to LTI v2) or LTI v2

**Comment by taniwallach** [comment]
LTI 1.3 core is a big change from LT 1.0 or 1.1 (or whatever we currently have) apparently using more modern tools and different protocols.

LTI Advantage are additional modules (services) on top of LTI 1.3 core. 

We'll need to implement LTI 1.3 core  https://www.imsglobal.org/spec/lti/v1p3/  before we can work on the additional services.

Moodle for examples has progress on LTI 1.3 support for both the consumer side and the provider side. Various material is at:
  - https://docs.moodle.org/dev/LTI_1.3_supp
  - https://tracker.moodle.org/browse/MDL-62599
  - https://tracker.moodle.org/browse/MDL-64780
  - https://tracker.moodle.org/browse/MDL-69542
  - https://tracker.moodle.org/browse/MDL-69542
  - https://tracker.moodle.org/browse/MDL-54809
  - https://tracker.moodle.org/browse/MDL-63088
  - https://tracker.moodle.org/browse/MDL-60416
  - https://moodle.org/mod/forum/discuss.php?d=388278

**Comment by xcompass** [comment]
We have implemented LTI 1.3 and advantage in our fork:
https://github.com/ubc/webwork2/pull/27. It has some UBC specific stuff.

We are planning to submit a PR to upstream once we remove UBC stuff.
However, we just lost two staff and resources are tight here now. If anyone
is interested porting, please let me know.

**Comment by taniwallach** [comment]
> We have implemented LTI 1.3 and advantage in our fork: [ubc#27](https://github.com/ubc/webwork2/pull/27). It has some UBC specific stuff. We are planning to submit a PR to upstream once we remove UBC stuff. However, we just lost two staff and resources are tight here now. If anyone is interested porting, please let me know.

Assuming that the Technion's Moodle will be updated to support LTI 1.3 over the summer, I should be able to work on this in July or August, if not sooner - so it will be ready for local production use by late October 2021 when we start out 2021-22 academic year. I may be able to start sooner, but cannot commit to it. I can certainly help with review work sooner.

**Comment by taniwallach** [comment]
Was not meant to be in WW 2.16... sorry about the accidental click.

**Comment by Alex-Jordan** [comment]
As of 2.19 (and partly with 2.18) LTI 1.3 with single-sign-on, grade passback, and content item selection is all here and tested with Canvas, Moodle, and Desire2Learn.

Certainly more features could be added. But I think this issue can be closed.
