### ISSUE TITLE
Applet problem in Set Detail 2

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1235]
If I am on the develop branch and I put Glenn's two-lines-parallel.pg from #1121 into a problem set, then if I visit Set Detail 2 for the problem set and click Render All, there are console errors:

```
Uncaught ReferenceError: ww_applet_list is not defined
    <anonymous> https://webwork-dev.pcc.edu/webwork2/testing/instructor/sets2/Testing/ line 2 > injectedScript:22
    jQuery 6
    success https://webwork-dev.pcc.edu/webwork2_files/js/apps/ProblemSetDetail2/problemsetdetail2.js:340
    jQuery 4
line 2 > injectedScript:22:1
Uncaught ReferenceError: ww_applet_list is not defined
    <anonymous> https://webwork-dev.pcc.edu/webwork2/testing/instructor/sets2/Testing/ line 2 > injectedScript:1
    jQuery 6
    success https://webwork-dev.pcc.edu/webwork2_files/js/apps/ProblemSetDetail2/problemsetdetail2.js:340
    jQuery 4
```

and the applet part of the problem does not load.

**Comment by Alex-Jordan** [comment]
Some notes on this at #1121, near where that PR was merged.

**Comment by Alex-Jordan** [comment]
@drgrice1, In #1121, you wrote:

> It seems that applet problems do not work on the Set Detail 2 page via the Render button at all. This is because the javascript needed for these problems is added to the header in the problem, and the Set Detail 2 page does not get that. So that means these also won't work in the library browser as it also does not load the header from a problem. This is the same as before though. That is not a change with this pull request.

Do you think anything has changed so that now when I go to the Set Detail page, this is not an issue? I was unable to reproduce the issue here and I wonder if it's all taken care of and I could close this.

**Comment by drgrice1** [comment]
Yes, that is not an issue anymore.  That was before we switched to rendering the problems in an iframe on the Set Detail page and in the Library browser (loaded via javascript). Now that problems are in an iframe on those pages, any problem should work, even these.
