### ISSUE TITLE
Feature requests for manual problem grader

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1240]
Here are some feature requests passed up to me from local faculty using the new manual problem grader. Recording them here so they are not lost.

> 1) It would be helpful if the "Previous Test", Student, and "Next Test" buttons were also at the bottom of the screen since you usually work down and end at the last question and ready to move on.

> 2) I wish it would retain the options that are checked at the bottom of the quiz as you move to the next student (i.e. "Show correct answers", "Show solutions", "Show Problem Graders")

**Comment by drgrice1** [comment]
It does retain the "Show Problem Graders" option. Note that that option implies the "Show correct answers" option.  It does not retain "Show solutions" at this point.

**Comment by drgrice1** [comment]
Note that request number 2 is fully implemented now.

Request 1 is more difficult, and at this point not entirely possible to implement with the current setup.  The nav is set up by a call from the templates.  The template could call that again, but would cause rather severe database thrashing.  The nav has to load information about all users that are assigned to the current set from the database.  Currently there is no way to just put that nav on the page twice.  There would probably also be issues with html id clashing.

**Comment by Alex-Jordan** [comment]
Would it work to give that `div.user-nav` sticky CSS so that it stays attached to the top of the page as you scroll down?

**Comment by Alex-Jordan** [comment]
Sorry, not requesting that you try that unless you happen to be active in the vicinity. I have to catch up on grading today and this weekend, and I'm still not really free for better WW contributions until mid June.

**Comment by somiaj** [comment]
I've been using the manual grader a while and like it. Thanks for the feature. I am teaching a course with multiple instructors and sections so it would be nice to filter the students listed in the manual grader by section. So have a second drop down menu next to the student list with `all` followed by a list of sections. Selecting a section only shows students in that section and prev/next cycle through that list.

**Comment by drgrice1** [comment]
@somiaj :  I don't think that adding another dropdown to the stick nav is a good idea.  That would mess with the symmetry of things in the sticky nav as well as start to make it crowded, particularly on narrow screens.  A better approach would probably be to put another dropdown somewhere else on the page.  That dropdown does not need to be in the sticky nav as that would be something that would not be changed for every problem or student.

**Comment by somiaj** [comment]
@drgrice1, I'm okay with having the option to filter students by section (or maybe even other ways) in another location, I just don't know the layout enough to have an idea where it would best be to put those things (maybe a hidden div you can open with advanced options?)

Right now our solution is just going to be multiple copies of the manual graded assignments for each section so it will be easier to cycle through the students, so such a thing would simplify work flow for us here.

**Comment by drgrice1** [comment]
I believe that everything in this issue has been addressed.  I am closing it.  Re-open if you believe there is something still needed here.
