### ISSUE TITLE
Request: Similar Question Button

### ISSUE THREAD

**Issue by iamjustgooder** [openwebwork/webwork2#1252]
Hey WebWork team. I'm wondering whether you guys can add a "Similar Question" button for homework so that after the student answers the question, they have the option to answer a similar question again. Mainly for more practice. Please consider this.

Thank you.

**Comment by drgrice1** [comment]
This is already implemented.  It is called `Show Me Another`.  This can be enabled from the course configuration under optional modules.  You can also make it so that it is enabled per problem.

**Comment by iamjustgooder** [comment]
> This is already implemented. It is called `Show Me Another`. This can be enabled from the course configuration under optional modules. You can also make it so that it is enabled per problem.

Hmm, I don't see anything. Do you think you can send screenshots of where I can find the option? 

Thanks.

**Comment by drgrice1** [comment]
![optional-modules](https://user-images.githubusercontent.com/47527406/111192983-acbbcc80-8587-11eb-977a-e5324b212d99.png)

**Comment by iamjustgooder** [comment]
Oh, do you have to be a teacher to enable this? I'm only a student.

**Comment by drgrice1** [comment]
Yes, you need to be an instructor.  So you will need to talk to your instructor about this.  We can not make it so that WeBWorK allows something that your instructor does not.
