### ISSUE TITLE
The "Courses" navigation link under main courses seems to be broken. 

### ISSUE THREAD

**Issue by enoxos** [openwebwork/webwork2#1272]
Just installed webwork on Linux server 20.04 and this is the only issue having.  Was wondering if anyone else has this issue.

**Comment by drgrice1** [comment]
I have seen no issues on Ubuntu 20.04.  Do you mean the `Courses` link under `MAIN MENU`?  What exactly do you mean that the link seems broken?

**Comment by enoxos** [comment]
Thank you for the reply, Yes, the link "Courses" under the Main Menu. I rebooted the server and it works now! So strange. 
Before the reboot, every time I would click the link, it will reproduce the main link with many copies of the work webwork2, for example:
myserver.com/webwork2webwork2webwork2webwork2...

Being on the topic, what creates the main page myserver.com/webwork2 and where can I locate this file in case I want to modify the content and the looks?
Thank you

**Comment by drgrice1** [comment]
WeBWorK uses mod_perl2 to generate page content.  It does not load an html document directly.  So there isn't a .html file that you can simply edit to modify things as you are asking.  The home page is generated by `lib/WeBWorK/ContentGenerator/Home.pm`.  That uses the `system.template` file in the selected theme (the default is the math4 theme located in `htdocs/themes/math4`).  Note that the `system.template` file is used for most pages, so modifying that file modifies all pages, not just the home page.

You can copy the file `math4-overrides.css.dist` to `math4-overrides.css` and modify that file if all you want is to change colors and such.

**Comment by enoxos** [comment]
Thank you for that information. 
I looked for such index.html file for some time, which prompted the question since I could not locate one. Paradoxically, Chrome creates a pseudo index file when the page is viewed in developer tools which added to the confusion.
Again, thanks for steering me in the right direction.

**Comment by dlglin** [comment]
I'm going to close this as it appears that the issue was resolved
