### ISSUE TITLE
copyright date

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1286]
It is common to believe that a copyright date like 2000-2021 is appropriate for software that was developed over that time span. However, librarians have taught me that the copyright date should be the date of publication. For example, for version 2.16, I think the copyright date should simply become 2021.

Differing opinions welcome.

**Comment by Alex-Jordan** [comment]
Also, I find a few "2000-1307" for the copyright date...

**Comment by taniwallach** [comment]
The date needed is really the "first publication" for each copyrightable "block" of code, but very few people in the past made any effort to track the authorship or exact first publication date for each line of code, and common practice seems to be to use a date range for simplicity. Were TWP to sue someone for infringement there would probably be a need to establish the correct "first year of publication" for the relevant blocks of code. With a "life of author + 70 year" duration for US copyright for material published in 1978 or later -  the exact year is probably not really a big deal.


References:
  - https://epiphany.law/articles/copyright/copyright-dates-single-year-or-range
    - "Once in a while you might see what looks like a date range instead of a single year of first publication, ...This is appropriate for ‘documents’ such as web pages or software programs which are constantly being revised and updated incrementally. The ‘start’ year should be the date of the oldest content still contained in the work, with the ‘end’ year being the last year that the work was revised."
  - https://photocopyrightlaw.com/can-i-use-a-range-of-dates-in-a-copyright-notice/
  - https://opensource.stackexchange.com/questions/2872/why-does-the-fsf-make-this-recommendation-about-ranges-of-copyright-years

**Comment by drgrice1** [comment]
The following is from https://www.gnu.org/licenses/gpl-howto.html:

>The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each past release; for example, “Copyright 1998, 1999 Terry Jones” if some releases were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.
>
>For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.
>
>Always use the English word “Copyright”; by international convention, this is used worldwide, even for material in other languages. The copyright symbol “©” can be included if you wish (and your character set supports it), but it's not necessary. There is no legal significance to using the three-character sequence “(C)”, but it does no harm.
>
>If you have copied code from other programs covered by the same license, copy their copyright notices too. Put all the copyright notices for a file together, right near the top of the file.

We are using a GPL license, so we should follow their rules.

**Comment by taniwallach** [comment]
> We are using a GPL license, so we should follow their rules.

One of the links I sent was more than a little critical about the very strict approach recommended by FSF. The FSF approach is almost certainly safe and best-practice when it is followed carefully from very early on in a project.

In theory following the GPL/FSF recommendations would be a good idea, but I suspect that in practice it would be quote hard to implement fully. WeBWorK, as a community developed and managed software development effort, has been "cutting corners" over the years, but maybe future contributions could be handled "better".

Unless the TWP executive committee wants to get legal help in determining the best future approach given the complicated authorship history, it may be simplest and more-or-less sufficient to continue with the more informal and laxer approach to the content and format of the WW copyright disclaimers in the code files.

Maybe we can do better for the webwork3 codebase.

AFAIK:
  - What is a release, when "draft" code becomes public as soon as it is on someones public fork, or in a PR, or maybe even in a public post on the forums.
  - TWP has not been collecting "contributor license agreements," but the copyright notices list "The WeBWorK Project" or other such phrases as the "owner".
    - FAQ with a section on "joint work": https://fairuse.stanford.edu/overview/faqs/copyright-ownership/#who_owns_the_copyright_in_a_joint_work
  - Although GitHub can help determine who wrote what parts of code recently, the data is not always complete or accurate, such as when code was "written" by A, but put into Git by B.
  - Contributors have not been getting their employers or institutions to provide them with "copyright disclaimers."
    - That makes ownership even less clear even when the author of given "block of code" is known.
