### ISSUE TITLE
MathQuill in WebworkClient templates

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1296]
It would be nice if the WebworkClient templates could use MathQuill, depending on if the host course has enabled it.

To that end I have tried to understand better how MathQuill works with answer blanks, but there is something about it that I do not understand. If I simply add the two MQ-related script tags and the two MQ-related css loads to a template like `simple_format.pl`, that does not work. Doing that makes the actual answer input fields hidden, but then the MQ answer input fields are not created.

[For example.](https://webwork.pcc.edu/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;sourceFilePath=BasicAlgebra/QuadraticEquations/solveQuad90.pg&amp;displayMode=MathJax&amp;courseID=anonymous&amp;userID=anonymous&amp;course_password=open&amp;outputformat=simple_mq) This is on a recent version of `WeBWorK-2.16` (but not the most recent), using `simple_mq_format.pl` which is just the current `simple_format.pl` with the four MQ lines added as described above.

What am I missing about the process of MathQuill going into action?

**Comment by drgrice1** [comment]
I have something in the works that adds that.

**Comment by Alex-Jordan** [comment]
I should have known :)  OK, I will wait and do testing etc when the time comes.

**Comment by drgrice1** [comment]
This is still a valid issue.  You could leave it open as a reminder/marker.

**Comment by taniwallach** [comment]
https://github.com/openwebwork/webwork2/pull/1301 seems to provide MQ support to `html2xml`.
Once that gets merged - it should work.
@drgrice1 - Please confirm.

**Comment by drgrice1** [comment]
Yes, that is true.

**Comment by pstaabp** [comment]
Fixed in #1301
