### ISSUE TITLE
Need to update version information

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1326]
With the release of 2.16 the VERSION files in webwork2 and pg should be updated with the new version number, and probably have the copyright dates updated as well.

**Comment by pstaabp** [comment]
#1271 does this.  I think we were waiting until the very end to pull this in.

**Comment by taniwallach** [comment]
@drgrice1 has a plan on how to do the merges to master and develop to try to keep things well organized which is discussed in https://github.com/openwebwork/webwork2/pull/1271 .

For PG: https://github.com/openwebwork/pg/pull/550 also waiting there until things are settled down.
