### ISSUE TITLE
Comment field missing from manual grader for one student in one quiz

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1339]
On my production server (which is running on an early version of the 2.16 release candidate) I was using the manual grader to grade a quiz. When I reached one student, something different happened. For each question I could still manually assign a score, but the field for me to leave a comment was missing. I could travel to other student versions of the quiz and the comment field is there. But for this one student, nope.

This student appears to have timed out during the quiz. That's the one thing that stands out about them. They have some answers in the first few questions, but then more than half of the quiz never had an answer submitted.

I could not reproduce this with my test server that is using the most up to date 2.16 release candidate. Is there any reason to think this was an issue earlier that is now addressed? If not, I need to keep looking to see if I can reproduce this.

**Comment by drgrice1** [comment]
Note that the place that the comment is stored is in the past_answer table of the database.  The score is stored in the problem_user table.

As soon as the quiz version is created for the student, all of the problems for that quiz in the problem_user table are created.  The rows in the past_answer table are only created when the quiz is submitted. 

So in short, there is always a place to store the score if a quiz version has been created, but there is only a place to store the comment if an answer has been submitted.  So the problem grader does not show the comment field in this case.

So this is not a bug in the grader.  It is just that there is no place to store a comment.

**Comment by Alex-Jordan** [comment]
That makes sense, there is nothing in the Show Past Answers page for this student for this quiz.

What I don't understand is why the quiz page is populated with some of the student's answers, even though there are no "Past Answers". The first 4 out of 11 questions have an answer in them, for example "3x^8/2 + 4x + c". Is something now grabbing the content of these fields when there is a timeout, storing it somewhere, and then populating it when I visit the quiz page?

**Comment by drgrice1** [comment]
The answers that are displayed in the quiz are the last_answer from the problem_user table.  That will be there if the student has entered an answer and changed pages or previewed answers.  The past_answer entry is not created until the exam is submitted.

If you change to course configuration "Permission" option "Can submit answers for a student" to "professor" and then go to the students exam and click "Grade Test" the past answers will be created using the answers in the last_answer column of the problem_user table.  Then you can add comments.

**Comment by Alex-Jordan** [comment]
Thanks, I will do that.

Answers are leading to more questions, but I will post a separate issue.
