### ISSUE TITLE
WeBWorK 2.16 looks for css files htdocs, not in htdocs/css

### ISSUE THREAD

**Issue by robert-marik** [openwebwork/webwork2#1347]
The update to WeBWorK 2.16 brings new problem if the user uses custom css files such as
```
$pg{specialPGEnvironmentVars}{extra_css_files} = ['robmar.css'];
```
in the conf file or 
```
ADD_CSS_FILE("left.css");
```
in the pg file. The css files are not found. The solution is either to put these files into htdocs directory (rather than to htdocs/css) or to use something like
```
$pg{specialPGEnvironmentVars}{extra_css_files} = ['css/robmar.css'];
```
and
```
ADD_CSS_FILE("css/left.css");
```
This can be easily resolved by adjusting about three files (`FormatRendered.pm`, `Problem.pm`, `GatewayQuiz.pm`), but I wonder if this is a bug or intended change.

**Comment by taniwallach** [comment]
This is an intended change, and the intention is that people use a format like `['css/robmar.css'];`as this allows the same mechanism to load from multiple locations.

**Comment by robert-marik** [comment]
Thank you.

**Comment by taniwallach** [comment]
The changes were made in https://github.com/openwebwork/webwork2/pull/1258 and there is a discussion there of the rationale.

**Comment by robert-marik** [comment]
Thank you, sounds to be a reasonable change when reading the discussion.
