### ISSUE TITLE
Default password using user_id instead of student_id

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1356]
On a server using the 2.16 branch I have noticed that if I add a student using the Classlist Editor, the default password is being set to the user_id and not the student_id. (If I add a group of users just a class .lst file, student_id is used).

**Comment by somiaj** [comment]
It appears this commit changed the initial password from student_id to user_id.

https://github.com/openwebwork/webwork2/commit/76aad684c15ab8cc432dba7f819c2e10cf8fdd07#diff-95190b3277941906a63fd8707d8885c1ac82a4da6f14249cd2ec79c28e32bf1c

If this is working as intended, the add user page needs to be updated to reflect this, right now it states:

```
Enter information below for students you wish to add. Each student's password will initially be set to their student ID.
```

In addition this behavior should be consistent with using a class list (.lst) file. For what it is worth, I would prefer student_id be used.

**Comment by drgrice1** [comment]
This is now fixed.
