### ISSUE TITLE
math in solution knowl not rendering

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1360]
We have two reports (one from a student and one from an instructor) that on their iPads with Safari, the math content in a solution knowl is not rendering. We are using the latest version of MathJax rendering that puts it inside script tags. I can't reproduce it, but I do not have an iPad. With Safari on a MacBookPro, I do not experience the issue.

My first guess is that MathJax is trying to render the math in the knowl before it has been fully loaded, but it's hard to say without hands on access. Could that be the explanation?

The instructor's details are:
```
Device: iPad Pro (Late 2018 model)
OS: 14.4.2
Safari: (Google says my iOS and Safari version are the same.  Otherwise, I'm not sure.)
```

Then they upgraded the OS a little, but still no math in the solution knowls.

```
Device: iPad Pro (Late 2018 model)
OS: 14.5.1
Safari: (Google says my iOS and Safari version are the same.  Otherwise, I'm not sure.)

```

**Comment by davidfarmer** [comment]
Is there a specific example to look at?

**Comment by Alex-Jordan** [comment]
@davidfarmer This is not a PreTeXt issue, it's with `webwork2` which has its own knowl mechanism and solutions.

@taniwallach The report is that this happens with any problem file. But I will set up something public and see if the instructor confirms seeing the issue there. And then post it here.

**Comment by davidfarmer** [comment]
Can you point me to the knowls javascript in the repository?

**Comment by davidfarmer** [comment]
I will send a pull request with updated knowls code that works with
MathJax 3.

**Comment by davidfarmer** [comment]
Since the knowls code calls MathJax.Hub, which does not exist in MathJax3,
I don't see how math could be rendering in a knowl in any browser.

But, I have not actually had a chance to see an example.

**Comment by drdrew42** [comment]
@drgrice1 you're right - I should have linked the 2.16 branch for [knowl.js](https://github.com/openwebwork/webwork2/blob/WeBWorK-2.16/htdocs/js/vendor/other/knowl.js)

**Comment by dpvc** [comment]
@Alex-Jordan, there is a bug in WebKit (the underlying HTML engine for Safari) that can cause CHTML output to be clipped (some characters don't show fully) intermittently.  It may be that this is the underlying problem your users are seeing.  If they continue to get it, ask them to use the MathJax menu to select SVG output instead, and see if that works better for them.

**Comment by pstaabp** [comment]
The solution and hint knowls has been changes to using html details/summary tags in openwebwork/pg#941
