### ISSUE TITLE
Click to view a student's problem from a versioned quiz

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1369]
Suppose a student has taken a quiz and has a quiz version. 

1. Make your way to the Set Detail page for that student, for that version: Classlist Editor, click the #/# for sets assigned to that student, and click the versioned quiz.I

2. If you click the eyeball icon, you will see the problem in an Undefined Set. It would be better if you were viewing that problem within that quiz version set.

An attempt was made to fix this in #1233, but making this change will be a bigger project than what was in that PR.

**Comment by drgrice1** [comment]
I do not think that this is possible at all in any reliable way with the current GatewayQuiz.pm module.

**Comment by drgrice1** [comment]
This has been fixed.  So I am closing this issue.
