### ISSUE TITLE
solutions not rendering via XMLRPC

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1379]
Here is a problem from the Contrib folder. It's just an example and the point is that it has a solution coded.
https://github.com/Alex-Jordan/webwork-open-problem-library/blob/master/Contrib/PCC/BasicAlgebra/QuadraticEquations/solveQuad90.pg

Here is the problem rendered using PCC's WW server, which is at an early stage of the 2.16 branch. This is using a `login_proctor` level user, where most permissions for that user have been taken away (set to `admin`). Note how the solution is present (good).
https://webwork.pcc.edu/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;sourceFilePath=Contrib/PCC/BasicAlgebra/QuadraticEquations/solveQuad90.pg&amp;displayMode=MathJax&amp;courseID=anonymous&amp;userID=anonymous&amp;course_password=open&amp;outputformat=simple

Now here is the same problem rendered using AIM's WW server, which is at a very recent stage of the 2.16 branch. The user is a `login_proctor` level user and they still have all of their default level permissions, except the ability to change password has been elevated to `admin`. Here, the solution does not render:
https://webwork-ptx.aimath.org/webwork2/html2xml?&amp;problemSeed=1&amp;answersSubmitted=0&amp;sourceFilePath=Contrib/PCC/BasicAlgebra/QuadraticEquations/solveQuad90.pg&amp;displayMode=MathJax&amp;courseID=debug-demo&amp;userID=login_proctor&amp;course_password=password&amp;outputformat=simple

Did something recently change with how rendering via XMLRPC happens that would explain why there is no solution rendering? (And if so, was the change intentional?) This is an issue for PreTeXt, which uses this method to obtain the rendered solution text.

**Comment by drgrice1** [comment]
You need to add showSolutions=1 to the url.  Solutions are not shown by default.  The same is true for hints.  Add showHints=1 for those.

**Comment by Alex-Jordan** [comment]
Thanks!
