### ISSUE TITLE
Incomplete upgrade instructions for 2.16

### ISSUE THREAD

**Issue by teepeemm** [openwebwork/webwork2#1393]
The [upgrade instructions for version 2.14](https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.14#Upgrade_Instructions) have the expected `sudo git checkout master` (as do 2.10--2.13).  The upgrade instructions for [version 2.15](https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.15) don't exist.  On the other hand, the [upgrade instructions for version 2.16](https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.16#Upgrade_Instructions) have a number of steps about dependencies that now need to be installed manually, but there doesn't seem to be a step that actually upgrades WeBWorK via `git`.  Am I misunderstanding something?  Shouldn't I need to update the WeBWorK and pg files?

I suppose I could install the dependencies according to 2.16, then run the `git` commands according to 2.14, and then finish with the customizations of 2.16.  But it's not me that will be doing the upgrade, but my IT department.  And I would rather not tell my IT department that they should interleave upgrade instructions from two nonconsecutive versions.

**Comment by drgrice1** [comment]
The git commands for 2.14 won't quite work for 2.16.  2.16 is still in release candidate stage, and so it has not yet been merged into master.  It is in the WeBWorK-2.16 and PG-2.16 branches.  So change master to those branch names for webwork2 and pg respectively.  So for webwork2 use:
```
cd /opt/webwork/webwork2
git fetch
git checkout master
git branch -m master-save
git checkout WeBWorK-2.16
```
and for pg use:
```
cd /opt/webwork/pg
git fetch
git checkout master
git branch -m master-save
git checkout PG-2.16
```

Note that the instructions for 2.14 were never quite correct.  git should really not be run via sudo (as the root user).

**Comment by drgrice1** [comment]
I guess if you previously ran git via sudo, you will probably need to do so again.  Either that or fix the ownership of the git clones.

**Comment by pstaabp** [comment]
The install instructions have the code clone the repositories, which assumes that they pull master.  Perhaps we should update those to pull `WeBWorK-2.16` and `PG-2.16` as well.

**Comment by drgrice1** [comment]
This issue is not valid anymore.
