### ISSUE TITLE
Geogebra Applets not working

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1420]
It appears that geogebra applets are not working.  The link to the javascript library: `http://web.geogebra.org/4.4/web/web.nocache.js` is a dead link.  It appears that there may be a new library system: https://wiki.geogebra.org/en/Reference:GeoGebra_Apps_Embedding

**Comment by drgrice1** [comment]
The link needs to be updated.  It is now https://www.geogebra.org/apps/latest/web/web.nocache.js.  We should probably switch to the new API, but that will take a lot of work.

**Comment by pstaabp** [comment]
I should have posted this on pg.  This was taken care of in openwebwork/pg#582
