### ISSUE TITLE
using local desk copy of webwork2  interfers with npm

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1425]
As best I can tell if you use a local copy of webwork2 with docker (so that you can make modifications) install npm doesn't work properly.  the directory node_modules is not installed in webwork2/htdocs.  Can anyone else verify this?

*  uncomment the line
        # - ".:/opt/webwork/webwork2"
   in docker-compose.yml
* remove the webwork image from docker to force everything to rebuild.  (docker image rm webwork)
*
with this change  the directory node_modules  does not appear on the desktop, nor does it appear
inside inside the docker container at   webwork2/htdocs/node_modules.   some css and javascript actions fail as a result
the javascript inspector show that the files at   webwork2_files/node_modules/* are not found.

**Comment by drgrice1** [comment]
If you mount a local webwork2 directory via docker-compose.yml, then you will need to manually install the javascript files by running `npm install` from the local htdocs directory.  The build step installs the javascript files inside the image, and the external docker mount is not available at that time.

**Comment by mgage** [comment]
got it.  Thanks.  I actually did that in desperation (along with several other things) but I wasn’t sure which of the changes made it work.
