### ISSUE TITLE
Archive::Zip needs to be added to check_modules

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1436]
and perhaps needs to be included elsewhere (on the wiki??) in a list of WW prerequisites. 
(This was required for running WeBWorK-2.16)

**Comment by drgrice1** [comment]
Archive::Zip is in check_modules already.  We have also added the appropriate Ubuntu package that installs that perl module in the installations instructions.

**Comment by drgrice1** [comment]
This is also noted in the upgrade instructions of the release notes.

**Comment by mgage** [comment]
Sorry I missed it when I looked at check_modules (probably unconsciously looking for Zip).  I was installing 2.16 on  demo.webwork so I could test with a lot of courses and I was not using docker. Thanks for following up.
