### ISSUE TITLE
course upgrade page gives warning: Couldn't release lock...

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1441]
when clicking on the upgrade courses tab in the admin course I get these warnings:

Warning messages

    (in cleanup) Couldn't release lock because the lock is not held by this thread.
    (in cleanup) Couldn't release lock because the lock is not held by this thread.
    (in cleanup) Couldn't release lock because the lock is not held by this thread.

**Comment by drgrice1** [comment]
This was fixed a while ago.
