### ISSUE TITLE
Remove checker for sufficiently new directory_tree.json

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1442]
The CourseAdmin.pm file checks that if the `directory_tree.json` file is sufficiently new.  (line 3441)  That file is no longer used in the current code and needs to be removed.

**Comment by taniwallach** [comment]
I just ran into https://webwork.maa.org/moodle/mod/forum/discuss.php?d=5599 which lead me to find this issue.

It looks like `tagging-taxonomy.json` does get updated by `OPL-update` so maybe checking the time of that file could be a suitable test instead of checking `directory_tree.json`.

**Comment by pstaabp** [comment]
This is no longer valid.  I can't find where it was removed.

**Comment by drgrice1** [comment]
@pstaabp:  I think this is actually still there.  It is now on line 3984.

**Comment by drgrice1** [comment]
This seems to be your problem:  https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/

I opened the file in binary mode with `vim -b` and I see this character at the beginning of your file.  I am not sure what to do about it though.

**Comment by drgrice1** [comment]
Also, if I delete that `<feff>` character that shows up, webwork can successfully import the students in the file.

**Comment by drgrice1** [comment]
I am closing this again.  Now I think it is resolved.
