### ISSUE TITLE
error when archiving courses with 'main'

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#1455]
When trying to archive a course I get the following "missing DNS error"

An error occured while archiving the course UR102:
no database specified in DSN! at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 293.
WeBWorK Warnings

WeBWorK has encountered warnings while processing your request. If this occured when viewing a problem, it was likely caused by an error or ambiguity in that problem. Otherwise, it may indicate a problem with the WeBWorK system itself. If you are a student, report these warnings to your professor to have them corrected. If you are a professor, please consult the warning output below for more information.
Warning messages

    Use of uninitialized value $var in hash element at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 285.

----------------------
2. The course UR102 is also not archived.
3. If I switch back to the develop branch everything works.
4.  the develop branch is a bit old c23o433  just after merging 1138
5. the main branch is brand new  48b9fea just after merging #1448

**Comment by drgrice1** [comment]
I think that you need to reset your develop branch.  The only differences between origin/main and origin/develop are the version changes and the docker git branch args.  Those won't affect things.

Either that or there is something not right in your conf files.

**Comment by drgrice1** [comment]
Run
```bash
git checkout develop
git fetch --all
git status
```
and see what that tells you.

**Comment by drgrice1** [comment]
Actually, you said the develop branch works, so this may be the main branch.  So also see what `git status` says when the main branch is checked out and after a fetch has been done.

**Comment by taniwallach** [comment]
I was able to archive a course on my laptop which is running the main branch in Docker, so I'm pretty certain that it is a configuration issue.

The database configuration in `site.conf` had **major** changes. I would check carefully that the database config closely follows the new structure (lines 207-230 from https://github.com/openwebwork/webwork2/blob/main/conf/site.conf.dist).

My first guess is that you are missing the block of lines (219-227) which define the `$database_dsn` based on the prior values and have an older format.

The new format requires using several `key=value` pairs as the code which parses the DSN to be able to get the data needed to archive out of the DB settings makes use of that format. (See the current `lib/WeBWorK/DB/Schema/NewSQL/Std.pm`.)

The new format is (for a non-localhost case):
```
$database_dsn="DBI:$database_driver:database=$database_name;host=$database_host;port=$database_port";
```
while older versions looked like
```
$database_dsn ="dbi:mysql:webwork";
```

**Comment by drgrice1** [comment]
@taniwallach: The fact that @mgage is getting different behavior from the develop and main branches indicates that one of those branches is out of sync or not updated.  So that needs to be resolved first.

**Comment by taniwallach** [comment]
> @taniwallach: The fact that @mgage is getting different behavior from the develop and main branches indicates that one of those branches is out of sync or not updated. So that needs to be resolved first.

Absolutely. I suspect he is on https://github.com/mgage/webwork2/commits/develop_cumulative which ends with a merge of 1138 as he mentioned in the original post. ("git log" saw that branch as being the just after the merge of #1138).

That branch is about 7 months out-of-date, while https://github.com/openwebwork/webwork2/pull/1160 which added the support for `DBD::MariaDB` and made major changes to the many DB related things (an in particular how `Std.pm` processes the DSN) is much newer. That old a branch has the old style DB settings inn `site.conf.dist`.

I think we can focus on directing to what to fix in the config to get the main branch working. He can update his develop branch separately.

**Comment by drgrice1** [comment]
I am closing this.  I believe it is obsolete.
