### ISSUE TITLE
html2xml raw format and invalid authentication - deciding how to respond

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1457]
When the `html2xml` interface is used with "regular" formats like `simple` and invalid authentication data is provided - the problem region of the generated page includes an error message about the authentication failing:
```
Unable to decode problem text:
Error message for command: renderProblem
faultcode: 404
faultstring: WebworkWebservice: Can't authenticate -- session may have timed out.
End error message
```
Ex: https://webwork2.technion.ac.il/webwork2/html2xml?language=en&displayMode=MathJax&outputformat=simple&answersSubmitted=0&courseID=daemon_course&userID=daemon&course_password=invalidpassword&problemSeed=1797382129&psvn=154768&sourceFilePath=Library%2FDartmouth%2FsetMTWCh2S4%2Fproblem_5.pg

However, when the `raw` output format is in use, as in https://webwork2.technion.ac.il/webwork2/html2xml?language=en&displayMode=MathJax&outputformat=raw&answersSubmitted=0&courseID=daemon_course&userID=daemon&course_password=invalidpassword&problemSeed=1797382129&psvn=154768&sourceFilePath=Library%2FDartmouth%2FsetMTWCh2S4%2Fproblem_5.pg
then the JSON reply does not contain anything to indicate the cause of the problem. The `raw` output from that URL (using the current code) is:
```
{"input":{"envir":{}},"lang":"en","answerTemplate":" ","dir":"ltr","inputs_ref":{"sourceFilePath":"Library/Dartmouth/setMTWCh2S4/problem_5.pg","outputformat":"raw","displayMode":"MathJax","language":"en","courseID":"daemon_course","problemUUID":null,"course_password":"invalidpassword","answersSubmitted":"0","userID":"daemon","problemSeed":"1797382129","psvn":"154768"},"rh_result":{"flags":{},"problem_result":{"score":0},"debug_messages":""}}
```

It is possible that some sort of message being added to the output could help sites using the `raw` format.

@Alex-Jordan Any thoughts on what would be a suitable response for use in PreTeXt when there is a problem?

Note: The output does not contain any significant data which is not part of the request in such a case, so does not seem to have any security implications.

**Comment by drgrice1** [comment]
I am closing this as it is no longer valid.
