### ISSUE TITLE
need warning about changing name of "master" branch to "main"

### ISSUE THREAD

**Issue by gajennings** [openwebwork/webwork2#1459]
When I tried to upgrade my local webwork2/master branch of webwork 2.15 by executing "git pull" I got errors about missing refs because it was linked to webwork2/master on github, which no longer exists.  I didn't know you had changed "master" to "main" so, following instructions I found on the internet, I tried to fix the missing refs and fell down  a rabbit hole.  To avoid mistakes like this it would help to post a warning that you have changed the name of the "master" branch on github to "main", and that "main" points to version 2.16 even though that hasn't been officially released, and that upgraders should read the last few lines of the version 2.16 release notes to cope with this change.  It would also help to add this warning to the instructions on https://openwebwork.org/2021/05/29/webwork-2-16-release-candidate/

**Comment by Alex-Jordan** [comment]
This is included in the release notes at https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.16. Do you have edit access to the wiki? It could help with your firsthand experience to reword and/or reposition that part of the release notes.

**Comment by gajennings** [comment]
OK I added warnings to the [Release notes for Webwork 2.16](https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.16) and also to [Upgrading WeBWorK from 2.15 to 2.16](https://webwork.maa.org/wiki/Upgrading_WeBWorK_from_2.15_to_2.16)

**Comment by pstaabp** [comment]
Looks like this was done.
