### ISSUE TITLE
load-OPL-global-statistics.pl: ERROR 1046 (3D000) at line 22: No database selected

### ISSUE THREAD

**Issue by justineuro** [openwebwork/webwork2#1460]
I got the following error when running `load-OPL-global-statistics.pl` (ver. `ww_version: 2.16`) as suggested by `update-OPL-statistics.pl` (when issued at the command line):
```bash 
# load-OPL-global-statistics.pl
ERROR 1046 (3D000) at line 22: No database selected
```
I was able to fix it by adding the following line (after line 177) in the block of codes for Database options of the `/opt/webwork/webwork2/conf/site.conf`file of my install:
```conf
$database_name = 'webwork';
```
There might be some better way to fix it.  Hoping this will help.

**Comment by drgrice1** [comment]
It sounds like you need to update your site.conf file. That is the correct thing that should be in that file. You should compare your site.conf file to site.conf.dist.

**Comment by justineuro** [comment]
Many thanks for looking into this.  Indeed, that is the cause of the problem.  My *.conf files have not benn upgraded when I tried the said script. :astonished:
