### ISSUE TITLE
Missing math4 theme files

### ISSUE THREAD

**Issue by apizer** [openwebwork/webwork2#1462]
I'm in the process going through the installation instructions.  Testing the Library Browser I see the following errors in the Console

GET http://192.168.138.130/webwork2_files/themes/math4/math4-coloring.css net::ERR_ABORTED 404 (Not Found)
GET http://192.168.138.130/webwork2_files/themes/math4/math4-overrides.css net::ERR_ABORTED 404 (Not Found)
GET http://192.168.138.130/webwork2_files/themes/math4/math4-overrides.js net::ERR_ABORTED 404 (Not Found)

In the htdocs directory I see

-rw-rw-r-- 1 wwadmin wwadmin  6146 Jul 26 20:07 math4-overrides.css.dist
-rw-rw-r-- 1 wwadmin wwadmin   783 Jul 26 20:07 math4-overrides.js.dist

I assume the .dist versions should be copied.  What happened to math4-coloring.css file?  I didn't see any mention of this in the Release Notes, only a note that math4 has changed.

**Comment by Alex-Jordan** [comment]
I think there never was such a file. If there was, this should reveal it:

```
git log --all --full-history -- htdocs/themes/math4/math4-coloring.css.dist
```

but I get nothing. Maybe you are just supposed to create `math4-coloring.css` when needed.

**Comment by drgrice1** [comment]
Those are harmless console warnings for files that are only needed if you are using a custom theme. If you want to get rid of the console warnings, create empty files.

**Comment by apizer** [comment]
OK. So a reasonable thing to do is to recommend creating an empty math4-coloring.css file and copying the .dist files to non .dist versions. I'll add that to the instructions.

**Comment by pstaabp** [comment]
Looks like these were added to the instructions.
