### ISSUE TITLE
styling on input form hiding some text

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1469]
In a 2.16 admin course, I was adding a new course. The title of the course is:
MODELOS ESTOCASTICOS I

I just pasted it in to the course title field that way, with all caps. In Firefox at actual size zoom level, the "I" at the end is not visible. One thing I can do to make it visible is remove `width: auto;` from the input field but I'm not sure what is the right thing to do.

**Comment by pstaabp** [comment]
The UI for 2.17 is different than that in 2.16 and this isn't a problem anymore.
