### ISSUE TITLE
session cookie management and LMS

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1473]
I'm not sure if this is on anyone's radar, so posting an issue. WW 2.16 moved to session management using cookies, if I understand correctly. I have found that with institutions using Canvas (and maybe others), that if WeBWorK is set to open within a panel in the LMS, the session cookies aren't managed correctly (or at all?)  The user will enter WeBWorK fine, but then if they try to do anything that would load the page, they are taken to the login screen.

Setting the external tool to open in a new tab gets past this. And that's what I would recommend to do anyway, because embedding all the WeBWorK navigation inside the LMS navigation looks messy and confusing.

I suspect the LMS is just interfering with what the application is allowed to do, as a well-intended security measure. And it's not letting the browser write a cookie. But I haven't looked deeper than the symptom and the workaround.

And then of course if it really is the LMS interfering, I'm not sure what WeBWorK can do about that. If there's nothing better to do, I will update the LTI pages on the wiki to strongly recommend opening WW in a new tab when setting up external tool links.

**Comment by drgrice1** [comment]
Another option if embedding is desired is to set webwork to manage the session via session keys.  That should work still.  In localOverrides.conf (or in the course.conf file for the course) add `$session_management_via = "key";`

**Comment by Alex-Jordan** [comment]
Oh, I didn't realize that keys were still an option. Thanks. Soon I will attempt an update of the LTI pages on the wiki. There are several things there worth updating, I think.

**Comment by awmorp** [comment]
I am seeing this issue occur even when Webwork is set to open in a new tab. It's Webwork version 2.15, and only with recent versions of Safari. Here are some affected user agents:

Mozilla/5.0 (iPad; CPU OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

[This parser](https://developers.whatismybrowser.com/useragents/parse/#parse-useragent) identifies these as Safari 15.1 on iOS 15.1 iPad, Safari 14.1 on iOS 14.6 iPhone, and Safari 14 on macOS (Catalina), respectively.

It isn't affecting every Safari user; for instance, here is a user-agent of a student who had no problem:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
(Safari 15 on macOS (Catalina))
