### ISSUE TITLE
Enabling $strip_address_from_email for LTI could lead to username collisions

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1508]
Not sure if this is a bug or just a gotcha for instructors/admins to be aware of:

Enabling `$strip_address_from_email` when using email addresses as usernames via LTI assumes that all email addresses in the LMS have the same domain.  If this is not the case, then two different LMS users could be logged in to the same WeBWorK account.  e.g. user1 has email address jsmith@domain1.edu, user2 has email address jsmith@domain2.edu.  Both users would be logged into the WeBWorK account jsmith.

An example of where this might occur: I am teaching an academic upgrading course, where users in our LMS do not have institutional email addresses, so they use their personal emails.

Possible remedies:

1. Do nothing, since several things would have to coincide for this to be an issue
2. Add a warning about this to the config file
3. Add a configuration variable that specifies the domain of email addresses, and then only strip that domain from emails.  If the domain doesn't match, then this could be handled a couple of ways: Leave other domains attached to the username, or don't allow students with other domains to log in.

**Comment by pstaabp** [comment]
Just looking there is the comment:
```
# This feature should not be used if emails could collide after the domain is removed.
```
on line 152 of `authen_LTI.conf` which is immediately after the `$strip_address_from_email` line.  

So perhaps, 1) above is what is needed.

**Comment by pstaabp** [comment]
After discussion with @dlglin, will close this.
