### ISSUE TITLE
wwsh script - '.' is no longer in @INC

### ISSUE THREAD

**Issue by chrisdukey** [openwebwork/webwork2#1511]
With perl 5 version 30 the `/opt/webwork/webwork2/bin/wwsh` script throws an error when you try and add an admin user (e.g. `./wwsh myCourse addadmin`). The error is `do "addadmin" failed, '.' is no longer in @INC;`

This can be fixed by adding `use lib ".";` into the wwsh script

**Comment by pstaabp** [comment]
@chrisdukey Which webwork version are you running?

I'm trying this on the develop branch and running perl 5.30 and don't see this, but some changes have been made with perl libraries.

**Comment by chrisdukey** [comment]
@pstaabp We're on version 2.16

**Comment by drdrew42** [comment]
Is it any different if you use `wwsh myCourse ./addadmin`? i.e. provide a path to the script file?

**Comment by pstaabp** [comment]
I see another issue.   Running as `wwsh` or `./wwsh` runs perl as `/usr/bin/perl` (first line of the file.).  That's not the perl that I use (I'm using perlbrew).  The top line should be `#!/usr/bin/env perl`.  Once I change it, I see @chrisdukey error.  

I generally run scripts starting with perl, like `perl bin/wwsh myCourse addadmin`, 

And yes, `use lib ".";` fixes it.   I think adding the proper top line and this line should fix this.

**Comment by drgrice1** [comment]
@pstaabp:  Looking at the git history for this file, I see why `#!/usr/bin/perl` was used.  It used to be `#!/usr/bin/perl -d`.  Flags don't work with `#!/usr/bin/env perl`.  Of course, now that the flag has been removed it could be changed.  @mgage removed the flag in 2015.

**Comment by drgrice1** [comment]
@pstaabp:  Also, have you tried running the script as @drdrew42 suggested with the relative (or absolute) path to the `addadmin` file?  So for your usage try `perl bin/wwsh myCourse bin/addadmin` without adding `use lib "."`, and see if that works.

**Comment by drgrice1** [comment]
If I run `perl bin/wwsh myCourse bin/addadmin` it fails with the error that @chrisdukey shows.  But if I run `perl bin/wwsh myCourse ./bin/addadmin` it works.

**Comment by pstaabp** [comment]
I can get it to run and I can get it to fail depending on how it is called and in what directory.

If we want it to run as an executable I would say we should call the user's version of perl (not necessarily `/usr/bin/perl`). 

Even though `addadmin` is a script, it's not clear by saying `wwsh myCourse addadmin` that you are calling a script unless you dig into the `wwsh` script itself.  That is, we should probably make this easy to use.    Although after writing a few other webwork scripts lately, I would tackle this whole problem differently at this point.

**Comment by drgrice1** [comment]
Looking even closer at this, I see that adding `use lib ".";` is certainly the wrong thing to do.  The argument passed for the script is a file that is evaluated via `do`, and so it should not be added via `use lib`.  The correct thing to do is to use the full or relative path when passing the argument as I mentioned in my previous comment.

Either that or the script should be rewritten to look up the correct file in the bin directory.  Although a check should be made for a full or relative path first, and if one of those are provided then the argument should be used directly to support running scripts that aren't in the bin location.  If you want to make the `wwsh` script easier to use, this is the way to go.

I don't think that when you added `use lib "."` and ran `perl bin/wwsh myCourse addadmin` that it actually worked.  Can you verify this?  Run the script in that way, and check that the admin user was actually added to `myCourse`.  Make sure that the `admin` user does not already exist in `myCourse` before testing this.

**Comment by drdrew42** [comment]
But the point is that installation instructions add webwork2/bin to the PATH, so that wwsh can be run from anywhere. The path to the script intended to be run through wwsh should be referenced by a path to that script. @drgrice1 is correct in that `use lib ".";` should not be considered a fix for this issue.

I do, however, agree that wwsh should run with env perl.

**Comment by drgrice1** [comment]
I think we are all in consensus on changing the first line to use env perl then!

**Comment by pstaabp** [comment]
If we get the directory of the script, like 
```
use File::Basename qw/dirname/
use Cwd qw/abs_path/;
$bin_dir = abs_path(dirname(__FILE__));
```

Then 
```
use lib "$bin_dir";
```

should do it, correct?

**Comment by drgrice1** [comment]
It still should not call `use lib`.  It is not a `lib` file.  It is an evaluated script.

**Comment by drgrice1** [comment]
When you execute a script, you do not `use` it.

**Comment by drgrice1** [comment]
Basically, in now way, shape, or form should `use lib` be part of the solution here.  That is the point.

**Comment by pstaabp** [comment]
@drgrice1 Good point.  I just added a possible fix for this and didn't use `use lib ".";`
