### ISSUE TITLE
Issue with non-unique student names

### ISSUE THREAD

**Issue by awmorp** [openwebwork/webwork2#1514]
My subject has two students with the same name, and their username differs by only one character. Let's call them John Doe, with usernames jdoe5@university.edu and jdo5@university.edu . Both were sitting a gateway quiz in the same Webwork course. jdo5 did the quiz and submitted as normal. jdoe5 did the quiz but did not click Grade Test at the end. I saw this when I checked for such cases at the end of the day, went in to their test, and clicked Grade Test while acting as jdoe5 . After grading the test, jdoe5's result appears under jdo5's user.

Before I graded jdoe5's test on their behalf:
![image](https://user-images.githubusercontent.com/8839416/138252293-7c1550eb-658b-4997-914c-86d017d09570.png)

After I graded jdoe5's test:
![image](https://user-images.githubusercontent.com/8839416/138252421-268a1f0d-feb3-4a6a-8b9f-a66da1945a46.png)

This is on Webwork 2.15 on a self-hosted server.
![image](https://user-images.githubusercontent.com/8839416/138252633-375ce968-0fc0-4bc7-bc24-4b12c207db64.png)

**Comment by pstaabp** [comment]
Fixed in #1643
