### ISSUE TITLE
issue with carriage return character at end of line in classlist file

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1540]
An instructor created a classlist file that appeared to be formatted fine, but when we attempted to import it, there was an error message:

Wide character in crypt at /opt/webwork/webwork2/lib/WeBWorK/Utils.pm line 1026. 

Eventually I sussed out that the file had carriage return characters (in addition to newline characters). I removed those and the file imports successfully.

Given instructors using Windows and other things, we should probably support the kind of file this instructor tried to use.

**Comment by drdrew42** [comment]
This also happens when saving as any of the alternate CSV formats provided by excel.

**Comment by pstaabp** [comment]
@Alex-Jordan can you provide a sanitized example of this?

**Comment by pstaabp** [comment]
@Alex-Jordan I remember we talked about this last week.  I've been exporting classlists from excel in other formats.  I tried Macintosh Comma Separated and MSDOS separated and couldn't repeat this error.  I wonder if this is an export from Windows version of excel.

**Comment by Alex-Jordan** [comment]
Here is one test file. I took the actual classlist file that an instructor provided. I opened it in vim and deleted all but 2 lines. I cleaned up things. I left the first 3 characters of the student ID as is, because the theory is that there is something hidden right at the start of each line that is the real problem (and not so much the carriage returns). I experience the issue when I try to import this classlist.

I haven't tried making something from Excel yet. However, in a separate incident, a different instructor raised the same issue. I told him about what Drew has pointed out, to use the very bare bones CSV output option in Excel. Then he reported that things worked. Could be Windows-specific.

I had to rename the file with .csv for upload to GitHub.
[testlist.csv](https://github.com/openwebwork/webwork2/files/7954182/testlist.csv)

**Comment by drgrice1** [comment]
This seems to be your problem:  https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/

I opened the file in binary mode with `vim -b` and I see this character at the beginning of your file.  I can delete that character in vim, and then webwork imports the students in the file fine.

I am not sure what to do about it though.

**Comment by drgrice1** [comment]
If I add `s/^﻿//;` to line 56 of lib/WeBWorK/File/Classlist.pm, then the file imports fine also.  I know it looks like there is nothing after the `^` in that substitution, but there is.  I cut and pasted the symbol (that is shown as `<feff>` in vim binary mode) into there and here.  Most likely that can be done with a proper hex code, but I haven't found it yet.  Then we could add this and make these files work.  It should be safe to do this I think.

**Comment by drgrice1** [comment]
This seems to do it:  `s/^\xEF\xBB\xBF//;`
