### ISSUE TITLE
Problem editor can save and overwrite a pg file to a different problem.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1580]
The following will cause the problem editor to overwrite a pg file to a different problem, causing data loss. The order is important here:

+ Have an assignment with multiple problems, choose to edit problem 2.
+ This opens up the editor in a new window/tab.
+ Without closing the editor window/tab, move the problems around (swap problems 1 and 2) and save the set.
+ Go back to the open tab, and try to update/save the original problem 2 pg file.

This says it will save the changes to the original problem 2 pg file, but when the window opens it says it has saved the changes to the new problem 2 pg file, thus overwriting the new problem's pg file.

It seems it is using the pg file located in the database for problem 2 to determine what to save to, instead it should probably get the info about which file to save to from the post request (or have some check to note that the problem has been moved and not overwrite the new problems pg file).

**Comment by pstaabp** [comment]
@drgrice1 Looks like you have a branch that addresses this, but never put in a PR.

**Comment by drgrice1** [comment]
Yeah, I need to finish that.  I did to much in the branch (code clean up stuff), and never got around to fixing it.
