### ISSUE TITLE
Inconsistent behaviour when gateway set open date is after a version open date

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1595]
As reported by @glarose:
Something came up here that I think is technically a bug, though not
one that's likely to show up often.  This is in the GatewayQuiz
module.  The issue we've hit is the following: we have GatewayQuiz
assignment which opened with a given open/due date pair (1/25--2/4).
For scheduling reasons, we are re-opening the set 2/13--2/18, so after
2/4 I reset the open and due dates for the set accordingly.  Between
1/25 and 2/4, of course, students took some versions of the test.  But
in the window 2/5--2/12 they appear to be unable to view the set
versions, getting the error "you don't have permission to view
unopened sets."

Below I give the long explanation of what I think triggers this, which
I'm hoping you will have a moment to check; the error message that
shows up for the student(s) isn't the invalidSet message "This set is
not open" that I'm seeing in the code, so I wanted to get some other
eyes on it before concluding that I'm correct.

Long-winded explanation:

I think this is due to the test setting $isOpen at line 683 in the
GatewayQuiz module, which is
```
           my $isOpen = $tmplSet && $tmplSet->open_date &&
              ( after($tmplSet->open_date()) ||
                  $authz->hasPermissions($userName,
                  "view_unopened_sets") );
```

Here $tmplSet is defined in line 616 as

`$tmplSet = $db->getMergedSet( $effectiveUserName, $setName );`

Then in line 972 we store $isOpen:

`$self->{isOpen} = $isOpen;`

and in line 1028 this triggers an error
```
   if ( ! ( $self->{isOpen} ||
            $authz->hasPermissions($userName,"view_unopened_sets") ) ) {
       $self->{invalidSet} = "This set is not yet open.";
       return;
   }
```

I think what should happen is that $isOpen should be defined to look
at $set (from line 649),

```
             $set = $db->getMergedSetVersion($effectiveUserName,
                                               $setName,
                                               $requestedVersion);
```

if there is a requested version.  This would lead to replacing line
683 with a more convoluted logic:

```
   my $isOpen = ( $requestedVersion ) ?
                ( $set && $set->open_date &&
                  ( after($set->open_date()) ||
                    $authz->hasPermissions($userName, "view_unopened_sets") ) ) :
                ( $tmplSet && $tmplSet->open_date &&
                  ( after($tmplSet->open_date()) ||
                    $authz->hasPermissions($userName, "view_unopened_sets") );
```

or, avoiding the terniary operator,

```
   my $isOpen = 0;
   if ( $requestedVersion ) {
       $isOpen = $set && $set->open_date && ( after($set->open_date()) ||
               $authz->hasPermissions($userName, "view_unopened_sets") );
   } else {
       $isOpen = $tmplSet && $tmplSet->open_date &&
               ( after($tmplSet->open_date()) ||
                 $authz->hasPermissions($userName, "view_unopened_sets") );
   }
```

p.s. I think the difference in error message is to do with the fact
that I'm still running 2.15.  It looks as if the organization of the
module there isn't as good, because the merged set version isn't
created until after the initial test for the open set.

**Comment by drgrice1** [comment]
Note that this issue is fixed in #1590.
