### ISSUE TITLE
Zooming in on figures does not follow convention

### ISSUE THREAD

**Issue by tactlessfish** [openwebwork/webwork2#1597]
ww_version: 2.15

I expected pinching out on 3-D figures to zoom in and pinching in to zoom out, just like Chrome and iOS. But, pinching out zooms out and pinching in zooms in. This is quite confusing.

**Comment by tactlessfish** [comment]
Hmm, the problem is for a school assignment, so I don't know if you'll be able to access it. Here's the URL: https://webwork4.math.wustl.edu/webwork2/math233spring2022/HW04/5

The figures in the problem seem to be using `x3dom-canvas`.

**Comment by pstaabp** [comment]
I don't see anything in the OPL or Contrib related to x3dom-canvas.  This might be a custom problem. @tactlessfish maybe pass this bug over to your instructor.

**Comment by tactlessfish** [comment]
Ah, you're right. It turns out this is an x3dom issue: https://github.com/x3dom/x3dom/issues/486
