### ISSUE TITLE
Only top half of MathJax shows on problems

### ISSUE THREAD

**Issue by knstnce** [openwebwork/webwork2#1602]
More recently, the MathJax elements of the problems get cut in half like in the picture. 

**Bug fixes that I use for now :**
Use Google Chrome
Reload the page and try to get a screenshot in less than one second
Display equations as Images (although I don't like it)

**Informations :**
Apple M1 chip
Safari Version 15.2 (17612.3.6.1.6) (I have tried clearing the caches, still the same issue)
ww_version: 2.16

<img width="996" alt="Capture d’écran 2022-02-18 à 09 56 33" src="https://user-images.githubusercontent.com/79022298/154706807-95ba1e10-f96d-4bf3-ae51-2abe54eebe52.png">

**Comment by dpvc** [comment]
Try switching to SVG output in MathJax: right-click or command-click on a math expression to get the MathJax contextual menu, and choose Math Settings->Math Renderer->SVG.

**Comment by knstnce** [comment]
yes that worked ! I did ask my teacher about it but she couldn't solve the problem, so I didn't know where else to go. Sorry if this is the wrong place, but thanks for fixing it :)
