### ISSUE TITLE
Show scores is set to override when editing a user's quiz by default.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1664]
When editing the user details for a gateway quiz, the checkbox to override the set's option to 'Show Scores on Finished Assignments?' is selected by default. I don't think this should be selected by default, and I find I am unclicking this checkbox with the quizzes I need to change the start/due times for an individual student.

**Comment by drgrice1** [comment]
I disagree.  I always use that option as is, and so if the option were the other way, then I would always have to change it back.

**Comment by drgrice1** [comment]
In any case, This is not technically an issue.  You just disagree with the default.  We can have a discussion about what the default should be though.

**Comment by somiaj** [comment]
The reason I brought this up as I found it odd this one field is treated different than the others. For my use case I would prefer it was unchecked and consistent with how the other fields work, but if this default is useful to most, I can keep manually unchecking it myself.

**Comment by drgrice1** [comment]
After looking at this closer I see that I was misinterpreting what you are talking about.  I thought you were talking about the default values that are set when a gateway quiz is created.  You are instead talking about the checkbox for determining if the user value overrides the global value.  You are correct, and this definitely is an issue.  There is a mistake in the logic for determining when the override should be checked.  I will put in a pull request soon to fix it.

**Comment by pstaabp** [comment]
Fixed by #1665
