### ISSUE TITLE
Test Time Limit warning shows time module 24 hours 

### ISSUE THREAD

**Issue by andrasbalogh** [openwebwork/webwork2#1680]
On the initial warning popup about timed quizzes the time shown is module 24 hours. The actual time for the quiz is calculated correctly. It is juts the initial warning popup that does not show correct time for time >24 hours (1440 minutes).
For example:
100 minutes will show as "You will have 1 hour 40 minutes to complete the quiz".
1440 minutes (24 hours) shows empty time: "You will have to complete the quiz."
1480 minutes (24 hours+40 minutes) shows "You will have 40 minutes to complete the quiz."

**Comment by drgrice1** [comment]
Unfortunately this will never be fixed.  The popup has been removed in the next release of WeBWorK in favor of a dedicated page for quiz versions and a start button on that page that displays the time for the quiz.  The time is correctly displayed on that page for times greater than 24 hours.
