### ISSUE TITLE
Hmwk Sets Editor shows warning if no set definition files are found.

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1684]
I just upgraded a test server to 2.17, but didn't run OPL update.  When I use the Hmwk Sets Editor I get the following warning messages:
Use of uninitialized value $_ in pattern match (m//) at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm line 711.
Use of uninitialized value $_ in uc at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm line 712.
Use of uninitialized value $_ in pattern match (m//) at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm line 711.
Use of uninitialized value $_ in uc at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm line 712.

This is because the library-set-defs.json and contrib-set-defs.json files don't exist on my server.  This can be fixed by either setting `$options{useOPLdefFiles}` and `$options{useContribDefFiles}` to 0, or by running `generate-OPL-set-def-lists.pl` (which happens when you run OPL-update), so this is a bit of an edge case, but if someone were to want to run WW without installing the OPL they will get this warning unless they change the settings quoted above.

**Comment by pstaabp** [comment]
Fixed in #1685
