### ISSUE TITLE
Date select closes when choosing a Month with drop down menu.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1688]
On the new date select tool, when choosing a different month using the drop down menu, the date select tool is closed after clicking on the desired month.

**Comment by drgrice1** [comment]
What exactly do you mean?  If I use the month drop down menu, and click on a month it does not seem to close the date select tool.

**Comment by Alex-Jordan** [comment]
Is this maybe a browser-specific issue? What were your details when this happens?

**Comment by somiaj** [comment]
It does appear to be browser specific. With firefox-esr in Debian, I get this issue, but I don't get this issue using chromium.

The issue is the select tool closes exactly as it would if you clicked somewhere outside of the tool. Doesn't appear to be a general issue with the tool, but with my system. I have tried to see if there is any issue around this in flatpickr, but haven't found any relevant yet.

**Comment by somiaj** [comment]
This appears to be an issue with flatpickr, since I get the same result on their test page. If I feel like debugging this more, I'll report it over there.

**Comment by drgrice1** [comment]
It could also be an issue with the firefox-esr build on Debian.
