### ISSUE TITLE
How do I approach debugging Use of uninitialized value in string ne at (Line 731 LTIAdvanced.pm)

### ISSUE THREAD

**Issue by jeis4wpi** [openwebwork/webwork2#1689]
Hi All,

One of our courses reports the error below:

WeBWorK Warnings

WeBWorK has encountered warnings while processing your request. If this occured
when viewing a problem, it was likely caused by an error or ambiguity in that
problem. Otherwise, it may indicate a problem with the WeBWorK system itself.
If you are a student, report these warnings to your professor to have them
corrected. If you are a professor, please consult the warning output below for
more information.

Warning messages

Use of uninitialized value in string ne at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 731.
Request information

Time
Tue May 10 19:54:55 2022
Method
POST
URI
/webwork2/MAPlaceTestForCalc/Calculus_Placement_-_Calculus_1R/

What do I look for in Calculus_Placement_-_Calculus_1R ?
Thank you.
-John

**Comment by jeis4wpi** [comment]
This is very helpful Glen, so 3 of my 12 students do not have Student ID.  I should just add their Student ID in WebWork to resolve?

**Comment by jeis4wpi** [comment]
OK, I added the student_id.  Our other classes don't have student_id(s).  The other fields are populated?

First Name, Last Name Email Link Status set to Enrolled.  Section and recitation are blank?  Other classes don't have section or recitation populated either?

**Comment by drgrice1** [comment]
You might try posting in the forums and see if anyone else has seen this specific issue.

You seem to be looking at the information that is saved in the WeBWorK database.  None of that will cause this issue.  The issue is with what is being passed in from the LMS.

**Comment by drgrice1** [comment]
Have you enabled LTI debugging?  Set `$debug_lti_parameters` to 1 in /opt/webwork/webwork2/conf/authen_LTI.conf for this.  Then when you or a student enters WeBWorK from the link provided in the LMS, WeBWorK will show debugging information.  This includes a list of all of the parameters that the LMS sends.

**Comment by jeis4wpi** [comment]
I will do that next

**Comment by jeis4wpi** [comment]
I created a new webwork class using the templates from the problem class that may have resolved the Canvas/WW integration issue.  Thank you again Glen.

**Comment by jeis4wpi** [comment]
forr user id nchisholm there is an uninitialized vs user id jpeismeier ?  Do you see with the LTI debug snippet what is missing?

============================ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 151.
=========== summary ============ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 270.
User id is |nchisholm| (obtained from lis_person_contact_email_primary which was preferred_source_of_username)
User mail address is |nchisholm@wpi.edu|
strip_address_from_email is |1|
Student id is ||
preferred_source_of_username is |lis_person_contact_email_primary|
fallback_source_of_username is |undefined|
preferred_source_of_student_id is |undefined|
================================
The following path was reconstructed by WeBWorK. It should match the path in the LMS: at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 453.
https://wwserver.wpi.edu/webwork2/MAPlaceTest22/Placement_Calculus_1/ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 454.
Use of uninitialized value in string ne at
/opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 731.





============================ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 151.
=========== summary ============ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 270.
User id is |jpeismeier| (obtained from lis_person_contact_email_primary which was preferred_source_of_username)
User mail address is |jpeismeier@WPI.EDU|
strip_address_from_email is |1|
Student id is ||
preferred_source_of_username is |lis_person_contact_email_primary|
fallback_source_of_username is |undefined|
preferred_source_of_student_id is |undefined|
================================
The following path was reconstructed by WeBWorK. It should match the path in the LMS: at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 453.
https://wwserver.wpi.edu/webwork2/MAPlaceTest22/Placement_Calculus_1/ at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced.pm line 454.

**Comment by drgrice1** [comment]
This needs to be moved to the forums rather than here.  This is not a bug in webwork2 code, but is an issue with your setup.

I don't see the difference from what you show.  You aren't showing all of the output, and there could be something else going on.

**Comment by jeis4wpi** [comment]
OK, sorry.

**Comment by drgrice1** [comment]
No problem.  If you post on the forums, I can also help you there.  The forums are the appropriate place for this type of thing though.  Furthermore, more will see it there that may have seen exactly this sort of thing, and you may get an answer that fixes your problem quicker.

**Comment by jeis4wpi** [comment]
https://webwork.maa.org/moodle/mod/forum/discuss.php?d=6653
