### ISSUE TITLE
Spans with ltr appear in titles on some pages.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1703]
Some of the page titles include the `<span dir="ltr">` in them.

![image](https://user-images.githubusercontent.com/18082412/169942866-006ae2b0-0360-45ba-b5fd-2eefd19f82f3.png)

I tried to track down where this is being set, but wasn't able to. The pages I notice this on are: Problem Set, Problem Set Details, Stats/Student progress. Seems to be any page that has the problem setID as part of the title.

**Comment by pstaabp** [comment]
Fixed in #1704
