### ISSUE TITLE
course archive and close date extension issue

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1708]
There is a weird issue happening in a Runestone course. If a student is given an extension on the close date, and they answer some things correctly during that time period between the class close date and their extended due date, then they don't get credit in the database. The past answers table and the answer log do show the submitted answers and indicate they are correct, but the score is still 0 when you look at Grades or use Scoring Tools.

Here is what makes that course stand out from other courses. This user previous used MAA hosting. When we initialized their course back in the Fall, it was from a course archive file that Danny was able to get from the MAA server. That is, we put the course archive file in /opt/webwork/courses/ and then "initialized" this user's course by unarchiving it. I can't recall at this point but I assume there was a need to update that course's database tables.

I don't know if this is worth investigating and fixing, assuming my suspicion is correct that the issue is related to how this course was initialized. But I wanted to share that this happened. People rarely archive a course, then unarchive it and actually continue to use it. So it's possible that there's some kind of issue with archiving/unarchiving even if you don't change servers. And the issue has just gone unnoticed.

**Comment by pstaabp** [comment]
@Alex-Jordan Is this on WeBWorK 2.16 ?

**Comment by Alex-Jordan** [comment]
Yes. That's another thing: I am not in a position to test on 2.17.

**Comment by Alex-Jordan** [comment]
It seems likely that this was some snag with how I unarchived an old course from another server. I will close this.
