### ISSUE TITLE
Professors can change admins role unintentionally

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1712]
Using the class list editor, if a professor edits an admin account, since a professor cannot assign the permission level of admin, the permission level in the account defaults to student, and then if the professor makes any changes to the account (leaving the permission level alone) the account permissions are dropped to student.

This could also happen with any role that can edit accounts on the class list editor with someone of a higher role. Unsure of the best fix, but maybe a lower permission level shouldn't be able to modify the permission level of a higher permission level account (though allow them to modify other settings). Also leads to the question if a professor can delete an admin account as well.

**Comment by drgrice1** [comment]
I believe this is fixed by #1888.

**Comment by Alex-Jordan** [comment]
I think this is fixed by now.
