### ISSUE TITLE
check_latex artifacts

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1727]
Running `check_latex` is leaving `check_latex.aux` and `check_latex.log` in the `bin` folder. Is that desired? If not, we could delete them at the end. Or run the whole thing in a temporary folder that gets trashed.

**Comment by drgrice1** [comment]
That is not desired.  Either of your suggestions are appropriate.  Probably using a temporary directory is best.  In fact that is what is already implemented in the script.  However, I forgot to add a `cd $TEMP_DIR` after creating the temporary directory and before running pdflatex.  Thanks for finding this error.

**Comment by pstaabp** [comment]
fixed in #1729
