### ISSUE TITLE
Solution knowl won't open with problem editor

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1739]
In 2.17, when I edit a problem that has a solution, and I click to view the problem, then when I click on the Solution knowl, nothing happens. I can visit the same problem in an exercise set and clicking the Solution knowl works. Does anyone else with 2.17 see this behavior?

**Comment by drgrice1** [comment]
I am seeing this too.  I will look into it.

**Comment by drgrice1** [comment]
By the way this is technically a PG issued.

**Comment by somiaj** [comment]
I reported this in https://github.com/openwebwork/pg/issues/688, but at that time seemed to be related to my browser, so glad to see it has been tracked down. Good to see others are seeing it so it can be fixed.

**Comment by drgrice1** [comment]
@somiaj:  When @Alex-Jordan posted this I looked for that issue but couldn't find it.  When I tested at that time it was working.  Now it is not (without the pull request).

**Comment by pstaabp** [comment]
Fixed in openwebwork/pg#696
