### ISSUE TITLE
ww2 2.17 on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by omar-hijab** [openwebwork/webwork2#1768]
This is a short summary on my experience installing ww2. 

After trying several possibilities, I set up an AWS t3a.xlarge instance running Ubuntu 22.04 LTS amd64 (nodejs v16 binary not available for arm64). The DNS is https://math.newhaven.edu. I then followed 

https://webwork.maa.org/wiki/Installation_Manual_for_2.16_on_Ubuntu
https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.17

to obtain webwork 2.17 running on Ubuntu 22.04 LTS. 

Notable snags and fixes:
- apt cannot install nodejs because of a conflict with libnode72. deleted libnode72 then did 'sudo apt install npm'.
- clicking on Library Browser leads to an error with MariaDB. 
-  - following https://webwork.maa.org/moodle/mod/forum/discuss.php?d=5596
-  - sudo apt install libmariadb3 libmariadb-dev
-  - sudo cpanm DBD::MariaDB

After these fixes, everything seems to work beautifully. Caveat: I'm new to ww2, and setting it up for a course this Fall 2022.

Omar Hijab
omar.hijab@gmail.com

**Comment by taniwallach** [comment]
Thanks for sharing your comments on setting up WeBWorK 2.17. Your post really is more relevant to the WeBWorK forums and not here on the GitHub site. The issues are all OS level configuration matters.

As far as I can tell the issues you mention are covered by the 2.17 installation guide for Ubuntu: https://webwork.maa.org/wiki/Installation_Manual_for_2.17_on_Ubuntu

Wishing you a successful roll-out of WeBWorK at your university.
