### ISSUE TITLE
Issues with essay questions in 2.17

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1774]
I'm new to essay questions in WW, so it's possible that some of this is just me not understanding how things work.

- In 2.16 if the entry assist method is set to MathView then essay boxes have a tool beside them to insert math expressions using the MathView editor.  I don't see this in 2.17.  Can the same sort of tool be created for MathQuill?
- In 2.16 if a question has essay problems, then when the instructor views the Problems page there is a "Grade Problem" link to take you to the manual grader.  This link isn't showing up for me in 2.17.  It is still accessible through the other links (on the Set Detail or Statistics page).

**Comment by drgrice1** [comment]
I will look into the MathView editor thing.  I don't remember that being there for essay questions for 2.16 though.  It may be possible to do something like that with MathQuill.

It seems that the essay flag is not being set for newly created essay problems.  I will look into it.

**Comment by drgrice1** [comment]
Wait, the flag is getting set.  It just isn't set until after a student answers a question.  So the "Grade Problem" link isn't showing up for some other reason.

I noticed that problems in existing sets created with 2.16 do get the "Grade Problem" link though.

**Comment by drgrice1** [comment]
#1775 fixes the grade problem link on the problem set page.

Now to see about the MathView thing.

**Comment by drgrice1** [comment]
The MathView problem is actually a pg issue! 

Unfortunately, adding a MathQuill editor for essay problems is something to look into for the future, but certainly can't be hotfix to 2.17.

**Comment by Alex-Jordan** [comment]
This seems to all be addressed, at least as of 2.19 if not earlier.
