### ISSUE TITLE
Shifted headers in /instructor/sets/

### ISSUE THREAD

**Issue by robert-marik** [openwebwork/webwork2#1786]
Hello. I can see a shift in the /instructor/sets/ table. See the picture. There should be empty th above checkboxes and all other th tags should move right. Can anybody check and confirm this issue? Thank you.

![Screenshot from 2022-08-16 11-28-10](https://user-images.githubusercontent.com/2342862/184847593-e72ecccd-e00c-47b2-ab4a-75f6d96baab5.png)

**Comment by taniwallach** [comment]
I don't see any such shift on WeBWork 2.17 either with the standard `math4` theme or with `math4-green`. Everything seems to display properly for me.

![set_editor](https://user-images.githubusercontent.com/39089094/184853456-edc953d5-6c23-4182-bd80-2f42bde7112e.png)

When I "inspect" I see another `<th>` before the one which has the "Edit Set Data" in it. The `<th>` you are apparently missing has the checkbox in it.

Are you running the current version of the code?

**Comment by taniwallach** [comment]
Yes - that does trigger the display bug. Sorry, I should have noticed in your image that you were in the second stage of the export process.
@drgrice1 seems to have made a patch already while I was trying to understand what was going wrong.

**Comment by drgrice1** [comment]
This is fixed by #1787.
