### ISSUE TITLE
trouble with pdf2svg on Oracle 8.6

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1795]
I'm installing on Oracle Linux 8.6, and I'm having no success at all with installing pdf2svg. The check_modules script looks for pdf2svg, making someone think it is necessary.

However it occurs to me that pdf2svg is not actually needed if I'm able to successfully use dvisvgm for LaTeX images. Should we remove pdf2svg as a requirement in check_modules? Or is there a way we can mark it as only needed for certain distributions? (IIRC, on Ubuntu 18, dvisvgm had some bug and you kind of had to switch to using pdf2svg.)

**Comment by drgrice1** [comment]
It seems that what is really needed is a check that one of them is available.

**Comment by Alex-Jordan** [comment]
There's also the issue that on Ubuntu 18 (if I recall that version number correctly), dvisvgm might be "available" but has that bug.

**Comment by drgrice1** [comment]
Yeah, if we really want to get fancy we would have the script check the operating system and make recommendations on modules and executables based on that.

**Comment by Alex-Jordan** [comment]
As of 2.19, `dvisvgm` is the default utility for this and we are not trying to support `pdf2svg`. Although, if it still works for someone, that's fine.
