### ISSUE TITLE
MathQuill with degC/degF/degK

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1804]
`degC`, `degF`, and `degK` are units from [Units.pm](https://github.com/openwebwork/pg/blob/main/lib/Units.pm#L29). With MathQuill, when for example `degC` is part of an answer, it is turned into `deg C` and then is interpreted as `deg*C` and not accepted as correct.

A workaround is to use text mode.

**Comment by somiaj** [comment]
Looks like this can be fixed by adding `degC`, `degF`, and `degK` to the list of known operators to MathQuill as well. I've added a commit to my copy of MathQuill https://github.com/somiaj/mathquill/commit/47a6279b1035b03a363f845ea89f4024dd424298, you care to test it out. I'll make a pull request if it works (you can test it out by just changing `htdocs/package.json` to my fork and reinstall the node modules.

**Comment by drgrice1** [comment]
@somiaj:  It seems that it would be better to remove `deg` form the list of operators instead.  Also note that your branch is not based off of the openwebwork mathquill main branch.  So any pull requests you make with it aren't going to work for webwork.

**Comment by drgrice1** [comment]
@somiaj:  Sorry, your branch is off of openwebwork mathquill main.  I was looking at the wrong branch.

**Comment by Alex-Jordan** [comment]
>  It seems that it would be better to remove deg form the list of operators instead.

Is that true even though `deg`, `degree`, and `degrees` are also valid units in Units.pm?

**Comment by drgrice1** [comment]
@Alex-Jordan:  You can still type any of those.  `deg` doesn't need to be an operator name for that.

**Comment by drgrice1** [comment]
Also, note that it would probably be better to change the mqeditor.js code to set this option instead of changing the mathquill default option.

**Comment by somiaj** [comment]
@drgrice1 I did think about modifying the options in mqeditor.js first, but didn't see exactly how to change the options there to override the defaults. Wasn't sure if this was something that could be modified in the `cfgOptions` defaults, or a more complicated override would be needed.

**Comment by Alex-Jordan** [comment]
I'm checking if typing `degrees` could somehow lead to `degree s` or something like that. But it sounds like if none of these are operators, that would not happen.

**Comment by somiaj** [comment]
@Alex-Jordan Yea, seems we would have to add each possible name as an operator, so @drgrice1 suggestion of just removing `deg` as an operator will cover all cases vs just the original three you mentioned.

**Comment by drgrice1** [comment]
@somiaj:  Yeah, the `autoOperatorNames` options is not done well in mathquill.  You have to set all of them at once, and you can't add more later (same with the `autoCommands` option).  Methods should be added to make it possible to add a single command or operator to the existing ones.

@Alex-Jordan:  If the are not operators then the spaces will not be added.  They are assumed to just be characters.  My suggested approach of removing `deg` makes these units consistent with other units like `ft`.  Currently `deg` gets the operator name formatting which is what adds the space after it.

**Comment by drgrice1** [comment]
In addition, operator names are supposed to be things like trig functions and such.  Things that you would typically write as something operating on some arguments.  Like `sin(x)`.  `degC` or `degF` are not operators.

**Comment by somiaj** [comment]
I updated my fork to remove `deg` instead of adding the operators. If this works, I can make a pull request unless @drgrice1 would prefer to improve mathquilll to allow this to be configured via mqeditor.js.

**Comment by drgrice1** [comment]
@somiaj:  For now we can go with this.  Eventually we should add methods to add and remove operator names from the defaults to facilitate changing the operators using mathQuillOpts so that problems can add or remove operators according to what is needed for the problem.

**Comment by Alex-Jordan** [comment]
I've been using @somiaj's branch (or rather, the state it was in the last time I ran npm install) and of course it works for this issue.

But the greater issue persists. Just now a student wanted to enter the string "prime" as one way to answer a polynomial factoring exercise. They typed it as "Prime", and the the `Pr` operator was recognized. Do we really need that operator for student answers? Do we need _any_ of these operators aside from `ln`, `log`, and trig functions for the use case of students entering WeBWorK answers?

**Comment by drgrice1** [comment]
@Alex-Jordan: I just saw your comment about the autoOperatorNames value of 'Pr'.

Currently the default autoOperatorNames for MathQuill are 'arg', 'det', 'dim', 'exp', 'gcd', 'hom', 'ker', 'lg', 'lim', 'max', 'min', 'sup', 'limsup', 'liminf', 'injlim', 'projlim', 'Pr', 'gcf', 'hcf', 'lcm', 'proj', and 'span'.  I see no reason that 'Pr' needs to be in this list for WeBWorK.  What about the others?  Should any of the others be considered for removal?

As to 'lg', should that be added to the new math function behavior?  I didn't notice that one before.

**Comment by Alex-Jordan** [comment]
There may be something I'm not considering, but my inclination would be to only keep ones that have meaning as an operator in some Math Objects context (only counting contexts that are part of the distribution). Perhaps that corresponds to the operators [here](https://github.com/openwebwork/pg/blob/main/lib/Parser/Context/Default.pm) but then I think there are also a few macros that add more (like maybe the Integer context adds 'gcd', 'gcf', and 'lcm').

I'm not familiar with the "new math function behavior". Is that where all the trig functions are? I'd move 'exp' from this list to however those are handled. And maybe 'arg' too? Among things in this list, 'arg', 'exp', and 'lg' are thee ones that accept a single number as input.

Not sure about 'lg', but again my inclination would be to only use ones that are defined in an out-of-the-box context.

**Comment by pstaabp** [comment]
degC, degF, degK is now working in math quill.  See https://github.com/openwebwork/mathquill/pull/13
