### ISSUE TITLE
Add clearfix to problem div.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1813]
I've been using a few floats in some problems, and in a few cases I need to add a `class="clearfix"` div wrapper into the problem so the float doesn't float over the problem div. Would it be reasonable to add the clearfix class to the problem div by default in webwork so if people use floats inside a problem they don't have to also wrap their output inside another div in similar cases?

**Comment by drgrice1** [comment]
I recommend not using floats ever.  Use other modern css features like flex that are better for responsive layouts.  I do not think that the `clearfix` class should be added to the problem div.

**Comment by somiaj** [comment]
I thought floats were still okay to use for their design, which is wrapping text around images. Thanks for the reply.

**Comment by drgrice1** [comment]
You should add a div containing the content inside the problem div, and add whatever classes and styles to that.  The divs that are output by webwork and pg should not have the `clearfix` class added.

Note that I don't actually know what "problem div" you are talking about in general (there are several), but this really applies to all of them.  The point is that the divs should remain clear of these sort of styles.  The `id="problem_body" class="problem-content"` div has styles applied by the pg problem.scss file.  Ideally that would in complete control of styles, and all rendering approaches would use that for styling problems.  This would give consistency of appearance across all renderers.  Adding a bootstrap class like `clearfix` could break layouts, and ideally bootstrap would not be a PG necessity at all.
