### ISSUE TITLE
Gateway quiz error if problems are not numbered 1,2,3,4,5,...

### ISSUE THREAD

**Issue by KoleNik** [openwebwork/webwork2#1814]
If you have a gateway quiz such that the problems for example are numbered 1,2,4,6 instead 1,2,3,4 you will get an error. The quiz will start and if you open it a second time you can do the problems, but there is an initial error when you try to open it.
[WeBWorK_gateway_num_error.pdf](https://github.com/openwebwork/webwork2/files/9822179/WeBWorK_gateway_num_error.pdf)

**Comment by drgrice1** [comment]
You must be running an old version of WeBWorK.  This but was fixed two releases ago.

**Comment by KoleNik** [comment]
We are on 2.17 in the department. The server got upgraded this August, Well, I wasn't a part of the setup, but could this have been missed somehow from the 2.17 install?

**Comment by drgrice1** [comment]
This is a valid issue it turns out.  There are still some cases where errors can occur with non-consecutive gateway quizzes.  One definite case is if there is no number 1.  There are some others as well.  A major case of interest is when the answer processing is done.

**Comment by drgrice1** [comment]
This should now be fixed with #1823 which is now merged.  You will have to wait until the next release for it though.
