### ISSUE TITLE
DBD::mysql::db selectall_arrayref failed: Unknown column 'pgf.libraryroot'

### ISSUE THREAD

**Issue by tpegues2** [openwebwork/webwork2#1819]
I just upgraded to the latest version (2.17) of Webwork and I get the following:
DBD::mysql::db selectall_arrayref failed: Unknown column 'pgf.libraryroot' in 'where clause' at /opt/webwork/webwork2/lib/WeBWorK/Utils/ListingDB.pm line 522.
f64d2c6b-e98c-5d67-a086-258ce690eacb::11198c74-5146-11ed-9673-de702f19ba96

**Comment by dlglin** [comment]
It will be much easier to troubleshoot this if you can provide details of where the error occurred, and exactly what you were doing when it happened.

**Comment by drdrew42** [comment]
I'm pretty sure this is indicative of a failure in running `update-OPL`. Make sure that you've pulled the latest version of the OPL and that `update-OPL` runs successfully. The update script should end with the option to share your server's usage data with the community.

**Comment by drgrice1** [comment]
Not an actual issue.
