### ISSUE TITLE
Disable autocompletion of proctor login username/password.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1824]
The proctor login username/password on the LoginProctor.pm page are not a standard username/password form that a browser should save into its password database or generate a secure password for since they are either meant to be used by a different user than the one currently logged into webwork, or a single generic password that is provided for all users to use.

This form should ideally not be auto filled with the credentials from the browsers saved logins for the webwork site, and it should not prompt to save the entered password or to generate a secure password. Since this is a fairly nonstandard use of a username/password, this doesn't seem to be something that browsers seem to fully support, so it might require some javascript for this.

This was discussed in #1821.

**Comment by pstaabp** [comment]
This is fixed in #1821.

**Comment by drgrice1** [comment]
Actually, it is not.  This issue was opened as a result of that pull request and the discussion therein.

**Comment by drgrice1** [comment]
This is fixed in #1830!
