### ISSUE TITLE
Matrix checking: The evaluated answer is not an answer hash 

### ISSUE THREAD

**Issue by rupertleveneucd** [openwebwork/webwork2#1843]
In the following toy problem, students entering incorrect answers sometimes see the warning ``The evaluated answer is not an answer hash : ||.``.
```
DOCUMENT();
loadMacros("PGstandard.pl","MathObjects.pl",);
Context('Matrix');
$A = Matrix([[0,0],[0,0]]);
Context()->texStrings;
BEGIN_TEXT
Enter \[ $A.\] \{ ans_box(3,30) \}
END_TEXT
ANS( ($A)->cmp() );
ENDDOCUMENT();
```

The warning does not appear if students enter any matrix in the correct format, e.g., ``[[1,2],[3,4]]``.

The warning does not appear if students enter the correct answer as a list of two rows only: ``[0,0],[0,0]``.

The warning does appear if students enter the wrong answer in this format, e.g., ``[1,2],[3,4]`` gives the warning.

The warning also appears if students enter some random list, like ``1,2,3,4``.

This behaviour is seen in problems in the standard library, but feels like it might be a webwork bug rather than a problem bug. Our webwork server is ww_version: 2.15 | pg_version 2.15.

**Comment by drgrice1** [comment]
Please close this issue, and reopen it again at https://github.com/openwebwork/pg/issues.  This is a bug with problem generation, not the webwork2 user interface.

**Comment by rupertleveneucd** [comment]
Thanks for pointing me in the right direction. It looks like this was already reported: https://github.com/openwebwork/pg/issues/612
