### ISSUE TITLE
Database Initialization for Docker Container

### ISSUE THREAD

**Issue by fabiangabel** [openwebwork/webwork2#1852]
I have the impression that `dockerentry-point.sh` should run a one-time `upgrade_admin_db.pl` 

If not, after starting the docker container, and trying to log as `admin`, I get the following:

```
Error record identifier
b582d797-3a30-5c8a-853e-2837896f707c::4e994472-7c55-11ed-835d-e6d0a9838667

Warning messages
It looks like the database is missing a column. You may need to upgrade your course tables. If this is the admin course then you will need to upgrade the admin tables using the upgrade_admin_db.pl script. at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 876.
Error messages
DBD::MariaDB::st execute failed: Unknown column 'set_id' in 'field list' at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 881.

Call stack
The following information can help locate the source of the problem.

in Future::result called at line 921 of /usr/share/perl5/Future.pm
```

**Comment by taniwallach** [comment]
That is almost certainly just a result of database changes between versions. You should just do the `upgrade_admin_db.pl` once, so there is no reason to do it on each start of the Docker container.

**Comment by drgrice1** [comment]
I agree with @taniwallach.  The `upgrade_admin_db.pl` script should certainly not be run in `docker-entrypoint.sh`.

**Comment by fabiangabel** [comment]
Thanks @drgrice1  and @taniwallach ! I cannot reproduce the issue anymore. Rebuilding the docker images in a fresh copy of the repository works without the need of running `upgrade_admin_db.pl`.

**Comment by taniwallach** [comment]
Once you ran `upgrade_admin_db.pl` the tables of the admin course would be permanently updated, so the issue would disappear. For other courses - the update tool in the admin course should fix things.

Possibly when you used a "fresh copy of the repository" (if it was in a new location) you were no longer providing the new containers with access to courses you had externally mounted. (By default the are in `../ww-docker-data/courses` if you use what is set in the `env.dist` file to create your local `.env` file for Docker.)
