### ISSUE TITLE
OPL problems not rendering images

### ISSUE THREAD

**Issue by jeis4wpi** [openwebwork/webwork2#1859]
Is there a fix for the OPL problem that fails to render an image ?  Some work and some fail?  I am using WW 2.17.

<img width="1424" alt="Screenshot 2023-01-06 at 2 59 46 PM" src="https://user-images.githubusercontent.com/42679190/211090768-564eab7e-1e67-4806-8478-83d6fa9ee2e7.png">

**Comment by maharper** [comment]
A quick look on our installation shows the same problem.  I think that the images that are not displaying are 3d rotatable images, while those that are displaying properly are regular pngs.  This is likely related to issues with the macro file `LiveGraphics3D.pl`.  It looks like the WW devs are already aware of the problem and there may already be a "hotfix" available for 2.17.  See openwebwork/pg#728 and openwebwork/pg#733

**Comment by jeis4wpi** [comment]
Wow!  Thank you!  does this mean a git pull on the pg repo will apply the hotfix?  Looking at the two references isn't clear to me how I can apply the hotfix Malcom?

**Comment by drgrice1** [comment]
Yes, that is correct.

**Comment by drgrice1** [comment]
You will also need to run `npm install` from the `pg/htdocs` directory.

**Comment by jeis4wpi** [comment]
Great!  Thank you Glenn.

**Comment by jeis4wpi** [comment]
Can I leave this open until I apply the hotfix please?

**Comment by jeis4wpi** [comment]
I added the hotfix and:

<img width="1371" alt="Screenshot 2023-01-09 at 5 18 39 AM" src="https://user-images.githubusercontent.com/42679190/211286509-59add3d0-79c8-4b1b-9b4b-b1aae92edaec.png">
