### ISSUE TITLE
Classlist Editor shows empty list but my account jpeismeier fails to import

### ISSUE THREAD

**Issue by jeis4wpi** [openwebwork/webwork2#1867]
the import file I used is:

```shell

cat student.lst 
# Field order: student_id,last_name,first_name,status,comment,section,recitation,email_address,user_id,password,permission
jpeismeier,Eismeier,John,C,,,,jpeismeier@wpi.edu,jpeismeier,xxx,20

```

What I see in the Classlist Editor is below.  Can I repair this class?  Other classes do not have this issue.
<img width="1289" alt="Screenshot 2023-01-20 at 4 22 51 PM" src="https://user-images.githubusercontent.com/42679190/213807922-53433baf-f23a-4d57-87f1-a891b3201540.png">

**Comment by dlglin** [comment]
When there are more than 200 students in a course the classlist editor doesn't show them all by default.  You can click Take Action (i.e. filter based on no criteria) to see the full class list, or enter a filter criterion to see a subset of the class.

... unless you are saying that your import file with one student somehow added 250 students, which would be a different issue.

**Comment by jeis4wpi** [comment]
sorry, haven't seen over 200 students before.  Filter is working.

Thank you Danny.
