### ISSUE TITLE
SMA threshold not defaaulting correctly

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1868]
In a course on a 2.17 server, you can:
1. visit Course Config. Enable Show Me Another, and set the attempt threshold to 5.
2. Create a homework set. Go to the Library Browser and add some problem, say from the OPL.

The problem is added to the set with an attempt threshold of 0. You can see this by visiting the Set Details page for the set.

Probably instead of 0, it should be -2 (which is the code for "use whatever the global setting is").

**Comment by Alex-Jordan** [comment]
I haven't looked, but maybe it is not setting it to 0, but rather leaving it blank. And something along the way interprets is 0. But the effect is the same: students can use the button before the instructor intended.

**Comment by drgrice1** [comment]
I just tested this on the develop branch, and the same thing does NOT happen.  Instead the problem uses the course default from the course configuration page.

**Comment by drgrice1** [comment]
Wait, I just tested this on WW 2.17, and what you describe is also not happening for me there.  What am I missing?

**Comment by drgrice1** [comment]
By chance, have you changed the setting of `$problemDefaults{showMeAnother}` in `localOverrides.conf`?  It is set to `-2` in `defaults.config`.  If you have changed that do another value, then that is what will be used when a new problem is created.

**Comment by Alex-Jordan** [comment]
It's happening on the Runestone server where there is no real customization. I will double check exactly the sequence of steps and write them again here. But an instructor reported it, and then I repeated it.

**Comment by Alex-Jordan** [comment]
> By chance, have you changed the setting of $problemDefaults{showMeAnother} in localOverrides.conf?

Yes, this seems to be it. Looking at it now, I think I mixed up`$pg{options}{showMeAnotherDefault}` and `$problemDefaults{showMeAnother}` when I was setting this up. And I guess I did do some customization of configuration after all.

Thanks for pointing me in the right direction.

**Comment by drgrice1** [comment]
Yeah, those pairs of options like that are a bit confusing.
