### ISSUE TITLE
WebWork - debug a problem

### ISSUE THREAD

**Issue by lufi2** [openwebwork/webwork2#1900]
Where do I submit a request for an author to debug a problem?

I have an integral question that requires a "+C" in the answer box for WebWork to mark it correct, but it also has a "+C" outside the answer box. This implies that the "+C" is not required in the submission. I was hoping to simply remove the "+C" in the text outside the answer box, but I can't seem to find the "+C" in the code.

Here's the problem: 

![image](https://user-images.githubusercontent.com/126512946/221659246-97b59011-f981-4c60-a5c9-98a9cc471feb.png)

Here's the code:

#DESCRIPTION
##  Calculus: Integration
##ENDDESCRIPTION

#####################################################################
DOCUMENT();        # This should be the first executable line in the problem.

loadMacros(
  "PGstandard.pl",
  "MathObjects.pl",
  "PGcourse.pl", 
  "parserFormulaUpToConstant.pl",
);

#####################################################################

$showPartialCorrectAnswers = 1;

TEXT(beginproblem());

#####################################################################

Context("Numeric");
Context()->variables->set(x=>{limits=>[6,10]});

$a = random(1,4,1);
$b = random(1,4,1);
while($b==$a) {$b=random(1,4,1)};

$A = non_zero_random(-6,6,1);
$coef1 = Compute("$a**2 + $a*$b + $b**2");
while($A==$coef1) {$A = non_zero_random(-6,6,1)};
$B = Compute("$coef1 - $A");

$coef2 = Compute("- $a - $b");
$coef3 = Compute("$a*$b");
$coef4 = Compute("$coef2*$a*$b + $A*$b + $B*$a");

$f = Formula("x^3 + $coef4")->reduce;

$ans = FormulaUpToConstant("(x**2)/2+$coef2*x+$A*ln(abs(x+$a))+$B*ln(abs(x+$b))");

#####################################################################

Context()->texStrings;
BEGIN_TEXT
Evaluate the integral
\[
\int \frac{$f}{x^2 - $coef2 x + $coef3} \,dx.
\]
Answer: ($ans_rule(40)); 

END_TEXT

$sum = $A +$B;
$term = $A*-$b + $B*-$a;
BEGIN_SOLUTION
First, use long division: 
$PAR
\(\displaystyle \frac{$f}{x^2 - $coef2 x + $coef3} = x + $coef2 + \frac{$sum x + $term}{x^2 - $coef2 x + $coef3}\)
$PAR
\(\displaystyle \frac{A}{x + $a} + \frac{B}{x + $b} \rightarrow A(x + $b ) + B (x + $a) = $sum x + $term\)
$PAR
When \(x = -$a\): $SPACE \(B(-$a + $b) = $sum (-$a) + $term \rightarrow B = $B \).
$PAR
when \(x = -$b \): $SPACE \(A(-$b + $a) = $sum (-$b) + $term \rightarrow A = $A \)
$PAR
\(\displaystyle \int (x + $coef2) \, dx + \int \frac{$sum x + $term}{(x+$a)(x + $b)} \, dx = \int (x + $coef2) \, dx + \int \!\left (\frac{$A}{x + $a} + \frac{$B}{x + $b} \right) \, dx\) 
$PAR
\(= \displaystyle \frac{x^2}{2}+$coef2 x+$A \ln|x+$a|+$B \ln|x+$b| \)
END_SOLUTION
Context()->normalStrings;

#####################################################################

ANS(($ans)->cmp());

ENDDOCUMENT();        # This should be the last executable line in the problem.

**Comment by dlglin** [comment]
The most reliable place to get help with authoring issues is the WeBWorK forum: https://webwork.maa.org/forums.  You can also try the authoring channel on https://thewebworkproject.slack.com, though it is less active.

When I run this problem I don't see the +C with either the code you supplied or the original OPL version.  One thing you can check is whether there are unsaved changes to your code.  If there are you will see a note at the top of the problem editor, and there will be a "revert" tab in the save dialog.

**Comment by lufi2** [comment]
Great! That was very helpful :)
