### ISSUE TITLE
SingleProblemGrader uses previous problem % score in tests when moving through problems.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1905]
I noticed in develop when using the single problem grader in a test with multiple problems, each problem on its own page, that when I move between problems, the 'Problem Score (%)' field is not updated to the current problems score, instead the field keeps the same value as the previous problem. Here are the steps I used:

+ Open up a test version with multiple problems.
+ Open up the problem grader.
+ Change the 'Problem Score (%)' to a different number.
+ Link to a new problem, the 'Problem Score (%)' will keep the same value as set in the previous step.

Unsure if this is some issue with my setup or not, as it seems weird it is caching the value from a previous page, even when I don't save the score. I have run 'npm ci', './generate-assets.js', and even done a hard reload, and still seem to have an issue with this.

Testing further, I even have this issue with the problem part sub-scores, and here is a bit stranger, it sets all the sub-parts equal to the same thing (what I entered into the final sub-part score). I also don't have this issue when moving through problems with the problem grader in normal homework sets.

**Comment by pstaabp** [comment]
fixed in #1906
