### ISSUE TITLE
bug with reduced credit during set import

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1923]
I get this error a lot when importing sets:

```
The reduced credit date should be between the open date 01/10/2023 at 11:59pm PST and close date 01/16/2023 at 11:59pm PST at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm line 1982, line 13.
```

At least one scenario where this happens is a et definition file gets created with dates like:

```
openDate          = 01/18/2023 at 05:00pm PST
reducedScoringDate = 02/01/2023 at 11:59pm PST
dueDate           = 01/23/2023 at 11:59pm PST
answerDate        = 01/23/2023 at 11:59pm PST
```

I think that an instructor is not using educed scoring, but they imported a set at one point that used it. They adjust dates, but not reduced scoring because they are not using it. They export a set, and it gets exported with a stale `reducedScoringDate`. And then later it gets imported and doesn't fit chronologically between the other dates that were adjusted.

I'm not sure that is the only scenario for this. I currently have the plague, and I'm not up for trying to parse the conditional logic where all this goes down. So i thought I'd at least report it.

**Comment by drgrice1** [comment]
Does this happen with the develop branch or is this with 2.17?  This may have been fixed in the develop branch.

**Comment by Alex-Jordan** [comment]
2.17.

I have an email today from my PCC IT contact handing over a new virtual machine to install develop/2.18. So, soon I will be up on that front.

**Comment by pstaabp** [comment]
I just tested this on develop/2.18 and I don't see any warning.

**Comment by drgrice1** [comment]
After looking at this closely, I think that the warning should be shown, but not as a warning.  I do see the warning on the current main and develop branches by the way @pstaabp.  Note that you will not see the warning if reduced scoring is not set as enabled in the file.

If a file has an invalid reduced scoring date, or anything is not valid in the file, then messages should be shown (not warnings as they are currently).

I have a branch with complete rework of the set definition file handling that I have had sitting around for a while that makes those warnings part of the messages that are shown, and not warnings shown at the bottom of the page.  It also separates those methods into a separate file that can be used from scripts.

I also did some testing on this, and am not able to actually get a date that is not between the open date and the due date to be saved to a set definition file by exporting sets.  To test the warnings I had to manually set that in a set definition file.

**Comment by stassenm** [comment]
I get this warning a lot. I'm on the same server as @pstaabp, so 2.18. Here's the header of a freshly exported set in my test course:

```
assignmentType      = default
openDate          = 07/31/2023 at 12:00am EDT
reducedScoringDate = 08/19/2023 at 11:59pm EDT
dueDate           = 08/19/2023 at 10:59pm EDT
answerDate        = 08/19/2023 at 10:59pm EDT
enableReducedScoring = N
paperHeaderFile   = defaultHeader
screenHeaderFile  = defaultHeader
description       = 
restrictProbProgression = 0
emailInstructor   = 0
```
As you can see, the reducedScoringDate is outside the open-close range, as exported by webwork. The 10:59pm in the close and answer dates tells me this set has gone through an import/export cycle spanning a change in daylight savings time status. The mismatch may be the result of disabling reduced scoring in my course configuration between an import and the next export.

When I import this set, I get the warning, despite the fact that enableReducedScoring = N. I consider that bad manners. Disabling reduced scoring makes the reduced scoring date moot, so it should be ignored. Despite the warning, the newly imported set retains the invalid reduced scoring date.

If I now export the set, the invalid reduced scoring date is preserved in the .def file, despite the fact that enableReducedScoring = N in this new file. That means I'll get the warning again on the next import. I don't see any reason to set the reduced scoring date in a set definition file that has enableReducedScoring = N.

Again, I have reduced scoring turned off for my course, so every warning about reduced scoring dates seems rude to me.

**Comment by drgrice1** [comment]
This issue has already been fixed for the next release.

**Comment by drgrice1** [comment]
By the way, I tested with your set definition dates on the develop branch and there was no warning.  Furthermore the reduced scoring date was adjusted to fit into the valid range (it was set to be the same as the due date).
