### ISSUE TITLE
Copy exercise sets when copying a course using the admin course

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1926]
I don't have the database skills to mess with this myself, but I have a feature request. When an admin uses the admin course to copy a course, I see no reason why the exercise sets in the database (minus the user data) can't just be copied over too. Or at least as an option to check like the other options that are there now.

I am eternally explaining about exporting/importing sets to instructors, as they move from one course to the next. It seems like it should be able to work more like an LMS course, where you can copy all of the structure easily. (But of course leave all user data out of the copying.)

And while we're at it, other structural stuff too like the Achievements that are active. (Actually that is the only thing I can think of...)

**Comment by pstaabp** [comment]
First of all, I agree that getting instructors on board with exporting their sets is tough. 

However, after thinking about this more, I'm wondering if a better idea might be to automatically export the homework sets (and achievements) before the course copy.   That is, do not automatically in the database.   Then the `.def` files are there and can be imported and the dates set correctly.   I do find that instructors are reasonably capable of this last step as long at the `.def` files are there.

**Comment by pstaabp** [comment]
Fixed in #2290
