### ISSUE TITLE
Editing users with Class List Editor doesn't show changes right after being saved.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#1933]
When editing users with the class list editor, the table that is generated after saving the changes is showing the previous information. To see this, edit a user in the class list editor, make a change to one of the fields, and save the change. After saving the user is shown in the user table without the changes. Reloading the class editor shows the changes, so they are being saved, just not being displayed right after the save.

**Comment by drgrice1** [comment]
This is a regression from #1888.  Previously the user information was retrieved from the database a second time in the filter handler after the action is performed, and that got the information fresh from the database.  That was removed in #1888 and an attempt was made to keep the user information in the lists up to date.  However, that isn't working in this case.

**Comment by somiaj** [comment]
Fixed in #1935
