### ISSUE TITLE
OPL update seems required, are there other steps like git pull before OPL update ?

### ISSUE THREAD

**Issue by jeis4wpi** [openwebwork/webwork2#1949]
Hi All,

A student was concerned that the problem below has the wrong solution.

<img width="773" alt="Screenshot 2023-04-21 at 1 36 36 PM" src="https://user-images.githubusercontent.com/42679190/233701368-28824c2e-7600-4bfd-9314-205d03376f46.png">

confirmed by their professor.

```shell

May 15  2020 linear-nonhomog.pg

```

I have version 2.17 but haven't pulled any hot fixes for a while?  Is it safe to just use OPL update?

Thank you.
-John

**Comment by dlglin** [comment]
If you are running WW 2.17 then OPL-update will download the latest release of the OPL for you, so you don't have to do a git pull on your OPL directory.

There were some hot fixes to the OPL-update script in August 2022, so if you installed WW prior to that you may want to get those changes before running OPL-update.

**Comment by jeis4wpi** [comment]
Thanks Danny, I see:

```shell
wwadmin@wwork-app-p-u03:/opt/webwork/libraries/webwork-open-problem-library$ git log
commit af29d6b0e40fe68c3e8553263c961b64c7ec4277 (HEAD -> main, origin/master)
Merge: 9d50dbb909 c18f543478
Author: K. Andrew Parker <kparker@citytech.cuny.edu>
Date:   Tue Jul 6 09:36:51 2021 -0400

    Merge pull request #845 from adentremont/patch-2

    Adding Mona B (student for Robyn Newell)

```

so try git pull before OPL-update ?  or does OPL-update also update this repo?

**Comment by jeis4wpi** [comment]
or is the script OK:

```shell
wwadmin@wwork-app-p-u03:/opt/webwork/webwork2$ ls -l bin/OPL-update
-rwxrwxr-x 1 wwadmin wwadmin 2138 Aug 16  2022 bin/OPL-update

```

**Comment by drgrice1** [comment]
There is no need to run `git pull` before running the `OPL-update` script.  It takes care of fetching the latest OPL release.

**Comment by jeis4wpi** [comment]
thank you.

**Comment by jeis4wpi** [comment]
After running the OPL-update, the library problem code didn't change?  I expected the diff below:

```shell

diff linear-nonhomog.pg /opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary/METU-NCC/Diff_Eq/linear-nonhomog.pg
118,120c118,120
<
<           if (Formula("$ddS[0] - ($a+$b)*$dS[0]") == Formula("-($a*$b)*$S[0]"))
< 	        { $flag[0] = 1; $msg = "\(y_1\) is fine$BR"; }
---
>           my @L = ( Formula("$ddS[0] - ($a+$b)*$dS[0] + ($a*$b)*$S[0]")->reduce,
>                     Formula("$ddS[1] - ($a+$b)*$dS[1] + ($a*$b)*$S[1]")->reduce );
>           if ($L[0] == Formula("0")) { $flag[0] = 1; $msg = "\(y_1\) is fine$BR"; }
123,124c123
<           if (Formula("$ddS[1] - ($a+$b)*$dS[1]") == Formula("-($a*$b)*$S[1]"))
< 	        { $flag[1] = 1; $msg = $msg . "\(y_2\) is fine$BR"; }
---
>           if ($L[1] == Formula("0")) { $flag[1] = 1; $msg = $msg . "\(y_2\) is fine$BR"; }
224c223
<        if (Formula("$ddS_h[0] - ($a+$b)*$dS_h[0]") == Formula("-($a*$b)*$S_h[0]")) {
---
>        if (Formula("$ddS_h[0] - ($a+$b)*$dS_h[0] + ($a*$b)*$S_h[0]") == Formula("0")) {
230c229
<        if (Formula("$ddS_h[1] - ($a+$b)*$dS_h[1]") == Formula("-($a*$b)*$S_h[1]")) {
---
>        if (Formula("$ddS_h[1] - ($a+$b)*$dS_h[1] + ($a*$b)*$S_h[1]") == Formula("0")) {
296c295
< Compute the following integrals.  (In the differential equation, \(g(t) = $g\) is the ${LQ}forcing function${RQ}.)
---
> Compute the following integrals.

```

I found out that the webwork-open-problem-library.git had files that were modified but not commited?

What are the corrective steps to having and up to date repo given the current status?

```shell

af29d6b0e4 (HEAD -> main, origin/master) Merge pull request #845 from adentremont/patch-2
9d50dbb909 Added UBC Dynamics problems (#844)

af29d6b0e4 (HEAD -> main, origin/master) Merge pull request #845 from adentremont/patch-2
On branch main
Your branch is behind 'origin/main' by 670 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    Contrib/CAPA/CAPA_Graphics/Gtype03/prob03av1.eps
        deleted:    Contrib/CAPA/CAPA_Graphics/Gtype03/prob03av1.gif
        deleted:    Contrib/CAPA/CAPA_Graphics/Gtype03/prob03av10.eps

```

Thank you.
-John

**Comment by jeis4wpi** [comment]
would like this issue re-opened please.

**Comment by drgrice1** [comment]
I am sorry, but this is not a valid issue.  The OPL-update does not literally do a `git pull` on the main branch of the repository.  It downloads and fetches the latest OPL release.  This is expected and intended behavior.  If you want to pull the latest from the OPL you can do that manually and run the OPL-update-legacy script.  That would be considered development behavior, not production use behavior.

**Comment by jeis4wpi** [comment]
Thank you Glenn, I am a bit stuck regarding pulling from the main branch as changes are not committed ?  I don't know how this happened as I don't change the repo files?  Is there a recovery path to having the OPL up to date and properly working with both frequent git pulls and OPL-update script run as needed?
