### ISSUE TITLE
LibraryBrowser in develop

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1960]
Adding problems in the Library Browser on the develop branch results in

<img width="349" alt="image" src="https://user-images.githubusercontent.com/879338/234935596-1b0437ef-13a0-48b0-991e-45219c52836d.png">

This might have occurred with #1846.

Although there is an error, it appears that the problems are added to the set.

**Comment by drgrice1** [comment]
Clearly there is a problem here.  The message is already indicative of something not done right.  It is saying "some problems in the set are already assigned" which should not be a problem if you are adding more problems to the set.  @taniwallach can you take a look at this?

**Comment by drdrew42** [comment]
Resolved by #1964
