### ISSUE TITLE
Change "Homework Sets" terminology?

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1963]
The course landing page is called "Homework Sets", which is a little misleading, as the sets may or may not be homework.  Is there a better title for this page?  I don't know if students know what "set" means in this context.  Maybe change it to "Course Home"?

**Comment by drgrice1** [comment]
I would say either call it "Course Home" as you suggest, or just "Assignments".

**Comment by dlglin** [comment]
I think "Assignments" has the same issue.  I don't think of tests as being assignments.

**Comment by Alex-Jordan** [comment]
+1 for something like "Home". If we are parsing words more, we sometimes
send students to a practice exercise we course even when the student is not
in any official "course".

**Comment by drgrice1** [comment]
The definition of "assignment" is a task or piece of work assigned to someone as part of a job or course of study.  Everything mentioned fits that definition, including tests and practice exercises.

**Comment by drgrice1** [comment]
Also note that "assignment" is the common term used by most learning management systems for this sort of thing.

**Comment by pstaabp** [comment]
Changed in #2265
