### ISSUE TITLE
Courses not visible on main Webwork page

### ISSUE THREAD

**Issue by patelh98** [openwebwork/webwork2#1977]
Hello,

I have installed version 2.17 on RHEL8. I can see the homepage at http://webwork.yourschool.edu/webwork2, where webwork.yourschool.edu is the address where I have hosted the server. I am able to login as admin to http://webwork.yourschool.edu/webwork2/admin and can also create courses. 

However, they are not visible on the main page http://webwork.yourschool.edu/webwork2/. On the server, when I go to /opt/webwork/courses, I can see the courses and can also access the course directly as admin through the URL: https://webwork.yourschool.edu/webwork2/[coursename] (where [coursename] is the name of the course I have created). So new courses are not visible on the main page but are being created. 

I made sure that there is not a file called "hide_directory" in the course directory. I have added the details added in site.conf. $database_port value is kept as the default, 3306. We are using an on-prem database server at University so I have mentioned that in the $database_host and $database_name fields. 

Please let me know what can I do to make the courses visible on the home page.

Please note: I already opened a thread at the Webwork Installation forum but no luck yet. Link to my [thread](https://webwork.maa.org/moodle/mod/forum/discuss.php?d=8231).

Thank you!
Harshal

**Comment by drgrice1** [comment]
This is an installation question, not an issue with webwork.  Please do not ask these sort of questions here.  The Github issues are for problems with the code that need to be fixed.
