### ISSUE TITLE
Remove "which users" from Classlist Editor and "which sets" from Homework Sets Editor?

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1991]
I guess this is a follow-up to #1480 

Now that there is a javascript "select all" on both the Classlist Editor and Hmwk Sets Editor, do we really need a drop-down for "which users" or "which sets" on the respective pages?  On the tabs that have such an option can we get rid of the drop-down and make the only option to be that the action applies to selected sets/users?  If the instructor wants to apply the action to all users or all shown users they can filter, then click the select all button.

I think that this would be a cleaner user experience.  Right now it's a little unclear that if you have a filtered list of users/sets, and you select "all users/sets" the action is being done to sets that you don't see.

**Comment by pstaabp** [comment]
This was addressed in #2294
