### ISSUE TITLE
Space in course name which unarchiving results in a nonfunctional course

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1995]
As noticed when reviewing #1994, when unarchiving a course, there's not check for bad characters in the course name. I put in a space and the course was created with spaces in the database tables and the directory.  However, logging resulted in errors. 

There's a check for new courses and we should use the same check here.

**Comment by drgrice1** [comment]
As you have stated it here, I think this is a bug fix.  I was interpreting your comment on #1994 as meaning to make spaces in course names work (much like spaces in set names now work).  Making spaces work in the sense that spaces are translated to underscores and back in all places where course names are shown in the UI is a feature request.  Checking for and not allowing spaces is a bug fix.  Semantics!

**Comment by pstaabp** [comment]
Fixed in #1994
