### ISSUE TITLE
hints shown in homework set even if "Hide Hints from Students" set to "yes"

### ISSUE THREAD

**Issue by ofloveandhate** [openwebwork/webwork2#2053]
In a homework set with 
* "Assignment type" set to "homework" and
* "Hide Hints from Students" set to "Yes"

and me acting as a student, I can still see the hints on problems.  This is in Webwork 2.17.  

In contrast, the same problem used in a "Gateway/quiz" set correctly hides the hints.

**Comment by drgrice1** [comment]
The "Hide Hints from Students" option doesn't actually do anything for Gateway quizzes.  That option only has effect for regular homework assignments.  Hints were never implemented for Gateway quizzes.  So hints will not be shown in Gateway quizzes no matter what settings you have set.

As to regular homework assignments, when you are acting as a student you are still not the student, and you will still be shown the instructor preview of hints even if you have "Hide Hints from Students" set to "Yes".  Note that the hint will have the message "Instructor hint preview: show the student hint after the following number of attempts: 2", letting you know that this is just a preview shown to you and not to students until after the specified number of attempts (2 in my example).

I have also checked that the hints are correctly not shown to students until after the specified number of attempts, so the option is behaving as expected.

**Comment by drgrice1** [comment]
I noticed that the message that is shown to instructors as stated in my last comment is misleading.  If you have "Hide Hints from Students" set to "Yes", then the message shouldn't say that the hint will be shown to students after some number of attempts.  It should say the hint will not be shown to students.  Note that message is shown in webwork 2.17, and will never be fixed as development has moved on and 2.18 is about to be released.  The message in webwork 2.18 (in release candidate stage now) says "The hint shown is an instructor preview and will not be shown to students. "

So for 2.17, unfortunately, you will have to just know that the message is misleading.  For 2.18 this is already fixed.
