### ISSUE TITLE
Linear relation macro including the line

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#2065]
In the new `parserLinearRelation.pl`, it doesn't appear that there is a distinction between inclusion of the line or not. 

In the example:
```
DOCUMENT();
loadMacros("PGstandard.pl","PGML.pl",'parserLinearRelation.pl');
Context("LinearRelation");

$lr = LinearRelation('2x+3y<6');

BEGIN_PGML
Enter [`2x+3y<6`] [__]{$lr}
END_PGML

ENDDOCUMENT();
```
Both `2x+3y<6` and `2x+3y<=6` are checked as correct.

**Comment by Alex-Jordan** [comment]
It looks like something more subtle. This example accepts:
2x+3y<6
2x+3y<=6
2x+3y!=6

But if I change the correct answer to 2x+3y>6, then that behaves well and
only accepts 2x+2y>6.

I'll look into the details soon.

On Mon, Jun 19, 2023 at 8:29 AM Peter Staab ***@***.***>
wrote:

> In the new parserLinearRelation.pl, it doesn't appear that there is a
> distinction between inclusion of the line or not.
>
> In the example:
>
> DOCUMENT();
> loadMacros("PGstandard.pl","PGML.pl",'parserLinearRelation.pl');
> Context("LinearRelation");
>
> $lr = LinearRelation('2x+3y<6');
>
> BEGIN_PGML
> Enter [`2x+3y<6`] [__]{$lr}
> END_PGML
>
> ENDDOCUMENT();
>
> Both 2x+3y<6 and 2x+3y<=6 are checked as correct.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-926c9b312004af0e&q=1&e=5cf4d22a-f537-43b0-a44a-b0bf2522af6e&u=https%3A%2F%2Fgithub.com%2Fopenwebwork%2Fwebwork2%2Fissues%2F2065>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-84b7bcf25d79497e&q=1&e=5cf4d22a-f537-43b0-a44a-b0bf2522af6e&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAC5WNKBEYCIQCRQ463XMBV6RANCNFSM6AAAAAAZMDMSDA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by pstaabp** [comment]
This should have been on the PG side. Oops, but openwebwork/pg#855 fixes this.
