### ISSUE TITLE
WeBWorK2.18 Job Queue problems

### ISSUE THREAD

**Issue by justineuro** [openwebwork/webwork2#2145]
I recently updated from ww-2.17 to ww-2.18 based on the instructions given in [Release Notes for ww-2.18 posted at the MAA site](https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.18#Upgrade_Instructions) and [Installation Manual for ww-2.18: Setting up the ww2 job queue ](https://webwork.maa.org/wiki/Installation_Manual_for_2.18_on_Ubuntu#Set_Up_the_Webwork2_Job_Queue).  I got `webwork2.service` to start but `webwok2-job-queue.service` is not working as I expected. After restarting the Apache 2 server, I was able to access the updated local ww-2.18 site (https://localhost/webwork2) and login into the admin site:
![ww2-admin-450-Screenshot_2023-07-23_12-42-21](https://github.com/openwebwork/webwork2/assets/7970053/3afe562e-98b1-49c0-8207-1cdcc1214d05)  
  
  
However, I get the following error that indicates that `mysql.pm` is trying to login as `'www-data'@'localhost'` into the job queue database:
![ww2-QUEUE-min-Screenshot_2023-07-23_12-21-41](https://github.com/openwebwork/webwork2/assets/7970053/1fe9cdd3-12ca-401d-b0a5-a80f5c6ee1a8)
  
  
Many thanks in advance for whatever help anyone can extend.

**Comment by drgrice1** [comment]
It looks like you are trying to use the mysql backend for the job queue.  What are your settings in site.conf for that?  That is the values of `$job_queue{backend}` and `$job_queue{database_dsn}`?  Also, if you are using the mysql backend, you will need to install the `Minion::Backend::mysql` Perl module. Furthermore, you will need create and setup the database.

I recommend using the SQLite backend, as it is much simpler.  The SQLite backend should work fine for what the webwork2 job queue uses it for.  For the SQLite backend you don't need to do any of that.  The database creation and setup is all taken care of.

**Comment by justineuro** [comment]
Many thanks!  Yes, the SQLite backend does work fine.
I am not sure though if I have everything setup properly.  I start Apache2 with virtual hosts `http://*:80` and `https://*:443`.  Next, I start `webwork2.service` so that `hypnotoad` listens at https://*:8080?....  WeBWorK2 is now accessible at `https://localhost:8080/webwork2`.  A number of problems:

1. An error occurs when I access `ww2` at `http://localhost:80/webwork2` or at `https://localhost:443/webwork2`: ![proxyError-min-Screenshot_2023-07-24_10-15-14](https://github.com/openwebwork/webwork2/assets/7970053/e5617e32-6640-48d1-ba3c-7da329227972)
A look at the Apache2 error.log shows something similar to
```
[Mon Jul 24 10:14:30.996362 2023] [proxy_http:error] [pid 10858] (104)Connection reset by peer: [client ::1:33920] AH01102: error reading status line from remote server localhost:8080
[Mon Jul 24 10:14:30.996467 2023] [proxy:error] [pid 10858] [client ::1:33920] AH00898: Error reading from remote server returned by /webwork2
[Mon Jul 24 10:18:23.977230 2023] [proxy_http:error] [pid 10820] (104)Connection reset by peer: [client ::1:54234] AH01102: error reading status line from remote server localhost:8080
[Mon Jul 24 10:18:23.977364 2023] [proxy:error] [pid 10820] [client ::1:54234] AH00898: Error reading from remote server returned by /webwork2
```
2. The LTI to a Moodle course seems problematic.  It was working the first time I tried it after I got `ww-2.18` working.  However, currently `ww2` no longer creates a new user logging in to `ww2` via the LMS (Moodle).  It does give a login prompt and allows a user to login to `ww2` if that uses already exists in `ww2`.  Does the below `debug.log` indicate that the preferred authentication method `WeBWorK::Authen::LTIAdvanced` is not functioning but the fallback method `WeBWorK::Authen::Basic` was used? 
```
[Mon Jul 24 10:21:59.879772 2023] WeBWorK::Authen::verify: BEGIN VERIFY
[Mon Jul 24 10:21:59.880132 2023] WeBWorK::Authen::LTIAdvanced::request_has_data_for_this_verification_module: LTIAdvanced has been called for data verification
[Mon Jul 24 10:21:59.880291 2023] WeBWorK::Authen::LTIAdvanced::request_has_data_for_this_verification_module: LTIAdvanced returning that it is not configured for this course
[Mon Jul 24 10:21:59.880784 2023] WeBWorK::Authen::verify: BEGIN VERIFY
[Mon Jul 24 10:21:59.880920 2023] WeBWorK::Authen::do_verify: db ok
[Mon Jul 24 10:21:59.881028 2023] WeBWorK::Authen::get_credentials: self is WeBWorK::Authen::Basic_TheLastOption=HASH(0x55e326cff9d0) 
[Mon Jul 24 10:21:59.881365 2023] WeBWorK::Authen::fetchCookie: cookie has this value: 'student002@maildrop.cc	LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm	1690165315'
[Mon Jul 24 10:21:59.881485 2023] WeBWorK::Authen::fetchCookie: looks good, returning userID='student002@maildrop.cc' key='LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm'
[Mon Jul 24 10:21:59.881639 2023] WeBWorK::Authen::get_credentials: params user '[studentEmailHere]' key 'LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm'
[Mon Jul 24 10:21:59.881764 2023] WeBWorK::Authen::do_verify: credentials ok
[Mon Jul 24 10:21:59.883215 2023] WeBWorK::Authen::do_verify: check user ok
[Mon Jul 24 10:21:59.886316 2023] WeBWorK::Authen::verify_normal_user: sessionExists='1' keyMatches='1' timestampValid='1'
[Mon Jul 24 10:21:59.886657 2023] WeBWorK::Authen::fetchCookie: cookie has this value: '[studentEmailHere]'	LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm	1690165315'
[Mon Jul 24 10:21:59.886778 2023] WeBWorK::Authen::fetchCookie: looks good, returning userID='student002@maildrop.cc' key='LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm'
[Mon Jul 24 10:21:59.886901 2023] WeBWorK::Authen::maybe_send_cookie: used_cookie='' unused_valid_cookie='1' user_requests_cookie='0' session_management_via_cookies ='1'
[Mon Jul 24 10:21:59.887584 2023] WeBWorK::Authen::set_params: params user='[studentEmailHere]' key='LF4kLJlO1TcgcZqaajiWx2BsrrQEZhsm'
[Mon Jul 24 10:21:59.887745 2023] WeBWorK::Authen::verify: END VERIFY
[Mon Jul 24 10:21:59.887847 2023] WeBWorK::Authen::verify: result 1
```
Also, after logging to `ww2` through the LMS, the following error occurs after an answer is submitted: ![student002ErrorSubmit-Screenshot_2023-07-24_10-22-22](https://github.com/openwebwork/webwork2/assets/7970053/9d10ed1d-5c68-4199-a25b-2ea3ec8c2e88)

The student's progress gets recorded in `ww2` but this is not passed on to the LMS.   

I also get the following in the `debug.log`:
```
[Mon Jul 24 10:22:00.158005 2023] WeBWorK::Authen::LTIAdvantage::SubmitGrade::warning: Submitting grade for user [...userEmailHere...] and set 0.
[Mon Jul 24 10:22:00.158554 2023] WeBWorK::Authen::LTIAdvantage::SubmitGrade::warning: LMS user id is not available for this user.
```
and 
```
[Mon Jul 24 10:22:00.201167 2023] WeBWorK::Authen::LTIAdvantage::SubmitGrade::warning: Submitting grade for user [...userIDHere...] and set 0.
[Mon Jul 24 10:22:00.201463 2023] WeBWorK::Authen::LTIAdvantage::SubmitGrade::warning: LMS user id is not available for this user.
[Mon Jul 24 10:22:00.201635 2023] WeBWorK::Authen::LTIAdvantage::SubmitGrade::warning: LMS lineitem is not available for this set.
```
Again, many thanks for looking into this!

**Comment by drgrice1** [comment]
It looks like you need to update your configuration files.  For the first issue, check your apache2 setup.  It looks like the proxy isn't working right.  For the second issue, note that the LTI settings are not all in `authen_LTI.conf` anymore.  There is also `authen_LTI_1_1.conf` (and `authen_LTI_1_3.conf` for LTI 1.3 authentication).

**Comment by justineuro** [comment]
No luck on the first problem (`proxy error`) until now.   
For the LTI problem, I think the error is being caused by `ww2` not being to connect with the LMS `Moodle` through `port 443`.  I noticed this using `ww-2.17` when both `ww2` and `Moodle` are forced to use SSL fro the LTI (please see the attached file containing an excerpt from the Apache2 `error.log`) : [student003ErrorLTISubmit.txt](https://github.com/openwebwork/webwork2/files/12159149/student003ErrorLTISubmit.txt).  Would you happen to know how Perl's `http.pm` verifies the CAs as it tries to LTI-connect `ww2` to `Moodle` to update the user's scores?  
Many thanks!

**Comment by drgrice1** [comment]
You are trying to localhost via https.  I don't think there is any way to make that work.  You will need to switch to http for localhost.  Note that localhost is secure even with http.

**Comment by drgrice1** [comment]
I am closing this issue as I do not believe this is a bug in webwork2.  I believe this is a configuration issue.
