### ISSUE TITLE
Accessibility observations

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2157]
A user has reported some accessibility observations. These were made with 2.17, but I think the same issues are in 2.18.

* when tabbing through the sidebar nav, when focus is on the current route, the outline indicating focus is not a clear indicator that this is where focus is. The outline color is too close to the background color. I am unsure what is a nice way to address this. Possibly change the outline color, or possibly change something about the background color or the text color.

* after submitting an answer, the input field has a glow about it, green or red. This is the case with MathQuill or not. This glow is not a sufficient indicator for users who do not perceive contrast or color well. (The results table gives more information, but that is not helpful for this issue.) They suggested some kind of icon adjacent to the input field. FWIW, PTX inserts a background image (⚠ or ✓) into the input field along with some padding so that does not overlap their answer. Again I'm unsure what wee would like to do to address this best.

**Comment by drgrice1** [comment]
The first point is an issue with changing the background color of some of the size nav.  When focus is on a link in the instructor tools portion the focus is considerably clearer.

One solution is to make the background color lighter.  That background color is not critical, and only differentiates between links that are instructor links and those that are not.

Another solution is to dispense with the background color entirely, and use a separator instead between instructor links and the rest.

**Comment by drgrice1** [comment]
By the way, I don't believe the first point was an issue for 2.17 since it did not have the colored background.

Also, on the second point.  I don't think there will be a solution for that until we eliminate the results table.

**Comment by Alex-Jordan** [comment]
This came from a school testing with the Runestone 2.17 server. When you are, for example, on the Grades page, there is a colored background for Grades. This is less about the coloring from the "student" section of the TOC. It is more about the color being applied to the current route, and if you tab focus to that item.

**Comment by Alex-Jordan** [comment]
Here are 2.17 and 2.18 screenshots. In both cases, we are on the Grades page (giving the dark background). But also I've tabbed focus to "Grades" and you can't really tell. This is their point.

<img width="350" alt="Screen Shot 2023-08-04 at 2 30 03 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/0edb565e-6c64-4fb1-a2df-bc29783ef6b3">

<img width="261" alt="Screen Shot 2023-08-04 at 2 29 20 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/aeb49749-ca84-4c67-9bf9-d4a8ea5340ef">

**Comment by drgrice1** [comment]
I see.  I didn't notice that you are specifically referring to when the current route is focused.  That background color should be made lighter.  That isn't too hard to do.  The challenge is making it work for all themes, and also not causing contrast issues for the background color and the text foreground color.  Note that changing the outline color is probably harder than changing the background color.

You might note that this is not an issue for the math4-yellow theme.  So if changes are made, it should be ensured that it doesn't create an issue there.

**Comment by Alex-Jordan** [comment]
At this page, try opening an exercise and submitting correct/incorrect answers to see what is done there.
https://pretextbook.org/examples/webwork/sample-chapter/html/section-1.html

Would you object to something like that to address the second issue? I think I can do the same when MathQuill is in use. At least, I have that for a PTX embedded exercise, but not 100% sure that the HTML structure is the same for webwork2. Also, I'm not wedded to ⚠ or ✓ as the indicators and would take any suggestions.

**Comment by drgrice1** [comment]
That would be okay.  Bootstrap has that sort of thing available with form validation.  I am not sure how well this would work with MathQuill though.

The plan for the next release is to eliminate the results table entirely.

**Comment by drgrice1** [comment]
I believe this issue is fixed in develop.  Can we close it now?
