### ISSUE TITLE
Please allow customizing the date format

### ISSUE THREAD

**Issue by szhorvat** [openwebwork/webwork2#2204]
WeBWorK uses m/d/y date format, which is mostly exclusive to the US. As I understand, it is possible to customize the format of the date shown to students, but not the display of other dates in the interface. Ref: https://webwork.maa.org/wiki/Dates,_Times,_and_Time_Zones#Date_Time_Display

I find that having dates displayed in different ways throughout the interface is very confusing, and brings a high risk of eventually making a mistake by exchanging the month and day.

I hope that the date display will be improved in the future, to better serve non-American users.

**Comment by drgrice1** [comment]
There is work that is needed on this.  This is something that certainly has not been implemented well.  Those settings are not used correctly in numerous places.

There is also an issue with multiple settings for locale that don't integrate well.  There is the site wide `$siteDefaults{locale}` setting and the per course `$language` setting, and those two settings don't work correctly together.

**Comment by szhorvat** [comment]
Is there a workaround in terms of `$language` that changes the date order to d/m/y or y/m/d (whichever)?  Or does it only change the names of weekdays/months?  Any tips for a practical workaround would be much appreciated!

**Comment by szhorvat** [comment]
> Also what version of webwork2 are you using?

We have 2.15, partly because I am using WeBWorK for the first time and took over an older installation. Attempting an upgrade mid-semester did not seem wise. Did things change since that version?

> Which dates in the user interface are you referring to specifically?

I am aware that it is possible to customize the dates that students see (open dates, close dates, etc.) I have already done this. I am referring to all other date displays, which are all in American format on our installation.

Whenever I _set_ a date as an instructor, I need to do it in American format. This lead to mistakes more than once, not just by myself, but others as well. For example, we set an incorrect opening date. This is a real issue.

> Those are displayed in the current locale with a properly localized date format already.

Are you saying that changing the system locale will be sufficient to correct this? Personally I do not have direct access to the machine where WeBWorK is running, so I will need to ask someone else.



> So I want to know what exactly you are seeing that leads you to making this issue request?

Opening this issue was motivated by having made multiple mistakes due to having to juggle multiple date formats (when setting dates in WeBWorK, when reading dates in a student view, and in everyday life).

**Comment by drgrice1** [comment]
I see.  So this issue is not entirely valid then.  With WeBWorK 2.17 I did quite a bit of work on this, and almost all dates are shown in the locale of the course.  I see a few dates that do not correctly honor the course language setting, and I assumed that is what motivated this issue.

WeBWorK has changed quite a bit since the 2.15 release.  I highly recommend upgrading to version 2.18 when you get a chance, but definitely not mid-semester.

**Comment by drgrice1** [comment]
The locale settings are WeBWorK settings.  Currently there is a site wide locale setting in site.conf.  It is near the end of that file and is `$siteDefaults{locale}`.  Although, I plan to remove that.  There is also the `$language` setting in localOverrides.conf.  That can be set per course.  That will become to only locale setting in the future.

Of course all dates that are shown to students use the `$studentDateDisplayFormat` (other than a few cases that will be fixed soon).

**Comment by szhorvat** [comment]
@drgrice1 We are now happily on version 2.19, but I still cannot figure out how to get the dates to use a familiar format (such as day/month/year or year-month-day). For as long as I have the system set to the `en` locale, it displays using the American format, month/day/year, which is very confusing for me.

Here's an example from the sets manager:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/c21a4713-c213-4c46-b30c-b4740fc7871d">

I am trying to have `25/08/2024 23:59` instead of `8/25/24 11:59 PM`. In the calendar view I'm looking to have Monday as the first day and Sunday as the last. I still need to keep the language as English, but there's only a single `en` available, which is interpreted as American.

Do you have any hints for me on how to fix this?

**Comment by drgrice1** [comment]
The only way to change the dates in the sets manager is to change the language.  We don't support changing the date formats for the instructor pages in any other way.

**Comment by szhorvat** [comment]
Then let me suggest re-opening this feature request. Please allow this kind of customization. The format of the date, time, and the calendar layout should not be tied to the language. English is used for teaching in many countries (some mostly English speaking, some not), but the American date format is something specific to the US. The same applies other languages as well, not just English. I am saying it as the speaker of a minority language in my home country: location, language and date/time formats are three things that should be kept independent.
