### ISSUE TITLE
MathQuill formats an answer in a way that is inconsistent with how WeBWorK interprets it

### ISSUE THREAD

**Issue by JeffAdler** [openwebwork/webwork2#2209]
A student had a problem where the answer was along the lines of: a * sin(x).  [Actually, it was a little more complicated, but let's not worry about that.]
When he typed "asin(x)", MathQuill displayed his answer as 
*a* sin(*x*).
Notice that the leading constant is italicized, leading the student to believe that he has entered the correct answer.  However, according to WW's answer preview, the system is interpreting the answer as involving arcsine.
So the issue here is not that WW is doing anything wrong: It's interpreting the answer as expected.  Rather, MathQuill giving an incorrect display.

**Comment by drgrice1** [comment]
What needs to be decided is whether MathQuill is showing the wrong thing or is PG (or MathObjects specifically) interpreting the answer incorrectly.  This comes down to should we support `asin` as an alternate notation for `arcsin`.  Currently MathQuill does not support `asin`, but PG does.  In my opinion `asin` should not be an alternate notation for `arcsin`.  That is a computer science notation, but not a mathematical one.

**Comment by JeffAdler** [comment]
Are people willing to change PG in this way?  If so, then I agree that that seems like the best solution.

**Comment by Alex-Jordan** [comment]
I don't think we can change PG to remove `asin`, unless we patrol for it in the OPL and find that it is not used much. But it seems likely that many problems might have things like `Compute("asin(x)")` in them.

**Comment by drgrice1** [comment]
Yeah, that is unfortunate. However, https://github.com/openwebwork/mathquill/pull/28 gives another solution that works with PG allowing `asin`.  However, students will not be able to enter `asin` when MathQuill is in use.  They will need to use `arcsin` or `sin^{-1}` instead.  With that pull request, if a student types `asin` then it will appear as *a* sin(*x*) and will be interpreted by PG in the same way.
