### ISSUE TITLE
absolute path to hypnotoad

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2234]
https://github.com/openwebwork/webwork2/blob/f35316ff6d865b143a7400c5a99bb5d4b260195d/conf/webwork2.dist.service#L13C1-L14C56

On a CentOS 7 system where I am trying to get webwork2 proxied through nginx, I had to change these lines to give an absolute path to hypontoad (`/bin/hypnotoad`). I'm unsure if that would be desirable/harmless to change in this distribution file.

**Comment by somiaj** [comment]
In general it is probably best to not have an absolute path, as this can vary between different OSes, on Debian the location is `/usr/bin/hypnotoad`, and if someone has it installed locally, it could be `/usr/local/bin/hypnotoad`. So I don't think it would be a good idea to have an absolute path there.

**Comment by drgrice1** [comment]
I agree with @somiaj.  The location of `hypnotoad` should be in the system PATH in the environment.

**Comment by Alex-Jordan** [comment]
Right. The issue I hit was similar to here though:

https://superuser.com/questions/1238471/systemd-error-executable-path-is-not-absolute

For this OS, it was not OK for the `ExecStart=` to not use an absolute path. I was getting errors like the following:
```
Oct 21 14:58:39 utmost.aimath.org systemd[1]: [/opt/webwork/webwork2/conf/webwork2.service:13] Executable path is not absolute, ignoring: hypnotoad /opt/webwork/webwork2/bin/webwork2
```

This and the use of `www-data` are things that may need to be edited depending on the OS. If there is no universal way to address these issues, I guess all we can do is have OS-specific installation variants. Or we can expect the person doing the installation to track the issues like this one I hit.

**Comment by drgrice1** [comment]
The distribution file is designed to work on most systems.  It will need modification on some systems, and that is why it is a `.dist` file that is meant to be copied and adjusted as needed.

You can sun `systemctl show-environment` to see the path that will be used for services by default.  If `hypnotoad` is not in that path, then you will need to add the full path to the `webwork2.service` file.  As I understand it the path that `systemctl` uses is defined when the `systemctl` executable is compiled.
