### ISSUE TITLE
proctor authentication for grade test when problems are not numbered consecutively from 1

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2247]
Found this while testing #2245.

1. On develop branch, go to Library Browser and create a new empty set. Add two problems to it.
2. Use Set Manager to delete the first problem, leaving the second problem still numbered as number 2.
3. Use Set Manager to change it to a Proctored Test, with authentication for start and grade. Adjust the dates so that you can start the test now.
4. Start the test. Enter an answer for the lone question. Click to grade.

This leads to the error I encountered as described in the #2245 thread. The issue is ultimately that in the database, the problem is numbered as 2, but there is a call to the database looking for a problem with number 1. I haven't looked into it enough to suggest a solution.

**Comment by drgrice1** [comment]
Fixed by #2248 and #2249.
