### ISSUE TITLE
Error message in exported hardcopy

### ISSUE THREAD

**Issue by d-torrance** [openwebwork/webwork2#2256]
I'm not sure if this is a WeBWorK issue or a PG issue, but I found a line integral problem (https://github.com/openwebwork/webwork-open-problem-library/blob/main/OpenProblemLibrary/ASU-topics/setCalculus/stef16_3p3.pg) for which the "Generate Hardcopy" button (using WeBWorK 2.18) generates a hardcopy without problems, but the resulting TeX file (and pdf) includes an error message:

```tex
{\bf (Error: syntax error  in 'Consider the vector field \\(\\mathbf{F} \\left( x, y, z \\right) = \\left( $p1\\right)
\\mathbf{i} + \\left( $p2 \\right) \\mathbf{j} + \\left( $p3 \\right)
\\mathbf{k} \ \).
$PAR
a) Find a function \\(f\ \) such that \\(\\mathbf{F} = \\nabla f \ \) and 
\\(f(0,0,0) = 0 \ \).
$BR
\\(f(x,y,z) = \ \) {\\answerRule[AnSwEr0001]{20}}
$PAR
b) Suppose C is any curve from \\(\\left( 0, 0, 0 \\right) \ \) to \\(\\left( 1, 1, 1 \\right). \ \) 
Use part a) to compute the line integral \\(\\int_{C} \\mathbf{F} \\cdot d\\mathbf{r}\ \).
 $BR{\\answerRule[AnSwEr0002]{20}}
')}
```
I think it would be much more useful if the error was identified and reported to the user during the generation of the hardcopy.  (And of course, this particular problem should be fixed, but that's a separate issue.)

**Comment by drgrice1** [comment]
I also downloaded the resulting TeX.  No error there.  You are not being clear on how to make this error occur.

This is what is in the TeX file for me, and there are no errors anywhere.  Not in webwork2, not in the TeX output, and not when pdflatex runs.
```TeX
\batchmode
\documentclass{article}
\usepackage{webwork2}
\pagestyle{empty}
\parindent=0pt
\begin{document}

\newpage
Consider the vector field \(\mathbf{F} \left( x, y, z \right) = \left( 3 z+ 3 y\right)
\mathbf{i} + \left( 2 z+ 3 x \right) \mathbf{j} + \left( 2 y+ 3 x \right)
\mathbf{k}\).
\vskip\baselineskip 
a) Find a function \(f\) such that \(\mathbf{F} = \nabla f\) and 
\(f(0,0,0) = 0\).
\leavevmode\\\relax 
\(f(x,y,z) =\) {\answerRule[AnSwEr0001]{20}}
\vskip\baselineskip 
b) Suppose C is any curve from \(\left( 0, 0, 0 \right)\) to \(\left( 1, 1, 1 \right).\) 
Use part a) to compute the line integral \(\int_{C} \mathbf{F} \cdot d\mathbf{r}\).
 \leavevmode\\\relax {\answerRule[AnSwEr0002]{20}}



\vspace{\baselineskip}\par{\small{\it Correct Answers:}
\begin{itemize}
\item
$\displaystyle 3zx+3yx+2zy$
\item
$\displaystyle 8$
\end{itemize}}\par

\end{document}
```

**Comment by Alex-Jordan** [comment]
I'm not able to reproduce this on 2.18 either. I created an assignment with this problem only, and the tex file does not have the `Error: syntax error...` content.

**Comment by Alex-Jordan** [comment]
Can you check a few things that might be local to your installation?
* Does `git status` show any relevant modified files? Either in `pg` or in `webwork2`?
* Is there anything in this course's `PGcourse.pl` file that could matter?
* Is your OPL up to date? (Since this is an OPL problem.)

**Comment by d-torrance** [comment]
Apologies for not being clear.  You did successfully attempt to reproduce the problem, but just aren't able to reproduce it!  Very strange!

Currently, I have the webwork2 repository checkout out at commit b0f516ba84d71ec7aae4527c43582c000e1b7382 and PG at commit https://github.com/openwebwork/pg/commit/e258ae292797ff3bae2a1f4ca1fe2db7fc256053.  Should I try updating either one of them?

**Comment by d-torrance** [comment]
> Can you check a few things that might be local to your installation?

Sure thing!

> * Does `git status` show any relevant modified files? Either in `pg` or in `webwork2`?

No, looks pretty normal:

```
dtorrance@terracini:/opt/webwork/pg$ git status
On branch main
Your branch is behind 'origin/main' by 15 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	lib/chromatic/

nothing added to commit but untracked files present (use "git add" to track)
dtorrance@terracini:/opt/webwork/pg$ cd ../webwork2; git status
On branch main
Your branch is behind 'origin/main' by 53 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   htdocs/package-lock.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	htdocs/piedmont_site_info.txt

no changes added to commit (use "git add" and/or "git commit -a")

```

> * Is there anything in this course's `PGcourse.pl` file that could matter?

No -- I'm just using the default.

> * Is your OPL up to date? (Since this is an OPL problem.)

I hadn't updated it since the start of the semester, but just did.  No changes.  (The problem in question hasn't been updated since 2017, so that's not surprising, I suppose.)

**Comment by Alex-Jordan** [comment]
I guess I would look into how the repos are behing origin/main by 15 and 53 commits. 53 commits back in webwork2 is a lot. That sounds like even more than the few hotfixes since 2.18 was officially released.

**Comment by d-torrance** [comment]
> I guess I would look into how the repos are behind origin/main by 15 and 53 commits. 53 commits back in webwork2 is a lot. That sounds like even more than the few hotfixes since 2.18 was officially released.

That fixed it!  Thanks :)

What's the best practice for how frequently to merge?  I generally just update in the summer after the release and forget about it until the next release.

**Comment by Alex-Jordan** [comment]
So I guess I was wrong about 53 commits being more than the difference between the original 2.18 release and the various hotfixes since then. You were already at 6 commits later than the original 2.18 release. Nothing occurs to me about the interim hotfixes that would apply here, but I guess something must have.

It's hard to say about how often to pull. Hopefully you don't have to pull again until 2.19. But if a bug is discovered, and it is serious enough that we need to repair it for 2.18, then we do that. It's hard to predict the frequency of discovering bugs.

You could schedule looking to see if origin/main has evolved, maybe once a month?

**Comment by drgrice1** [comment]
I think a monthly check is about right.  If you see that your local clone is behind main the pull it, run `npm ci` from the htdocs directory if anything in the htdocs directory has changed, and restart the webwork2 and webwork2-job-queue services.

I hope that @Alex-Jordan is right, and there are no more hotfixes.  2.18 was a pretty big change, so it is not surprising that there are a few more hotfixes than usual.
