### ISSUE TITLE
Copy/pasting a date in the date override box causes the date to reset to a future date.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#2257]
Assign a set to all students, then go override a single student's dates. I then want to change the open date for that student to be an hour earlier, so I copy the current open date, paste it into the blank open date field, and modify the time. When I click out of the input box, the date I entered in is reset to a future date.

Manually typing the full date in works as expected, using the date selector tool also works as expected. The issue is something with the copy/paste of the current date into the input box. Unsure if this is just an issue with my browser (firefox-esr on Debian) or something else causing the date to be detected as invalid when it is copy/pasted. Looking at the date, it looks formatted correctly, so maybe some hidden characters being copied into the date field.

**Comment by Alex-Jordan** [comment]
When you say reset to a future date, is it just reset to that original date you copied? This would be strange, but I was wondering you ruled out this has something to do with a one-hour difference for daylight savings time.

I could not reproduce this on my Mac with Firefox, Chrome, or Safari on the develop branch. Or in Firefox on 2.18.

**Comment by somiaj** [comment]
@Alex-Jordan it is resting to some default date in the future. Since the input starts empty it defaults to what ever the default open date in the future is.  If I had another date there, it reverts back to the date that was there before I copy/pasted.

Basically the date string is being detected as invalid and the javascript is setting it to a default value or the previous value. I now think it might be a translations issue.

**Comment by somiaj** [comment]
Fixed in #2258. This might be worth a hot fix so date translations work better in 2.18.
