### ISSUE TITLE
Achievement items and problem numbers

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2281]
Suppose an achievement item applies to a particular problem from a set. Now suppose you have a set with irregular numbering, like the set problems are numbered 2, 5, 6. The user will be presented a select menu with all the numbers 1, 2, 3, 4, 5, 6. If they choose a number like 1, they get an "error accessing that problem" message. Ideally they would just be presented with 2, 5, 6.

**Comment by pstaabp** [comment]
Fixed in #2299
