### ISSUE TITLE
instructors can nullify test version dates

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2340]
An instructor did not understand how test and test versions work. What they wanted to do was (for a particular student) extend all close dates until the end of the term. They navigated to some page in WeBWorK where they could see all the sets assigned to this student (which included test version sets) and they changed dates. In the case of test versions, (not understanding those dates should have been left alone) they saw that the "set values" were already what they wanted, because the parent test had its close date set to the end of the term. So they cleared the "user overrides" fields (which in the case of test versions are not really overrides; those are just that student's actual open, close, answer date for that version).

WeBWorK should not have permitted the instructor to save these fields with nothing in them. In fact as far as I can tell from a screenshot from the instructor, WeBWorK did give an error message and said the invalid (null) dates would not be saved. And yet, these dates are all null now when I visit the course. So if the student wanted to, they can return to "version 1" tests and continue working all the way up to the end of the term, even though it's a 90-minute timed test. (Actually in this case they can't do that because the tests are set to only one graded submission, and that is used up. But that is beside the point.)

The instructor was just a bit frustrated and went through clearing dates without understanding how test versions work. But there is something to look into here, because the instructor should have not been allowed to nullify all these test version dates. The instructor has not clarified to me yet what process they used to clear the dates, but again, I can see that they are all null now.

**Comment by pstaabp** [comment]
Fixed in #2345
