### ISSUE TITLE
Please help debug Assignment Type = Test error 

### ISSUE THREAD

**Issue by hartww** [openwebwork/webwork2#2341]
Please see attached for error that occurs in my Spring 2024 course even though  in my Fall 2023 course the same practice test works great.  I imported it from Fall 2023 into my Spring 2024 course, and get this error in Spring 2024.
[proctoredexamerror.pdf](https://github.com/openwebwork/webwork2/files/14412238/proctoredexamerror.pdf)

Our WeBWorK administrator tried this Test in other Fall 2023 courses and Spring 2024 courses,
and the Test works in Fall 2023 courses but not Spring 2024 courses.  Our tech support updated our system to
the latest/current version 2.18 in summer 2023 and says no changes have been made to the server at all since last year's upgrade

**Comment by Alex-Jordan** [comment]
The error message indicates that someone should go into the `admin` course for your server, and use the "Upgrade Courses" tool applied to this course.

**Comment by hartww** [comment]
Thanks for your quick reply, but our course administrator checked the upgrade tool, and shared the attached image, which seems
to say that our Spring 2024 courses do not need upgrading.
What more should our admin check?
Joan

________________________________________

**Comment by Alex-Jordan** [comment]
I think the attached image did not make it to your post. Can you try posting it directly on the GitHub thread?

**Comment by hartww** [comment]
<img width="641" alt="courseslist" src="https://github.com/openwebwork/webwork2/assets/161389777/42ea98a5-d930-454f-8c01-925db237a356">

The above is the missing attachment.

**Comment by Alex-Jordan** [comment]
OK, looking more closely at the first screenshot, it's like there is some database query that joined some tables and need to fully qualify the `set_id` field as to which table it came from. Or something like that. We will look into it.

**Comment by hartww** [comment]
Thanks for looking into it,
Joan

________________________________________

**Comment by Alex-Jordan** [comment]
Pinging other developers: I'm not sure I can understand this with only the screenshots. Going down the call stack from the first image, the first time `set_id` is used is at line 198 of `ProblemSet.pm`. The error message says that 'set_id' is ambiguous in some order clause. I think that comes from the third argument of `sub get_records_where` in `DB/Schema/NewSQL/Std.pm` but that's as far as I can probe this for now.

**Comment by drgrice1** [comment]
@hartww:  Which database and perl database driver are you using?  Are you using mysql or mariadb for the database?  Are you using `DBD::mysql` or `DBD::MariaDB` for the perl database driver?  (Note that `DBD::mysql` can be used with the mariadb database, and `DBD::MariaDB` can be used with mysql, so I need to ask both.)

**Comment by drgrice1** [comment]
@hartww:  I created a pull request that might fix this issue.  If you could get the administrator of your webwork instance to test it and see if it fixes the issue, we would appreciate it.  The pull request is #2344.

**Comment by drgrice1** [comment]
If you could find out from your system administrator the answer to my question about which database setup the system has, that would also be useful.

**Comment by hartww** [comment]
Our tech support for our server said that based on your discussion he changed it from usingdbd:mysql to dbd:mariadb in the site.conf file. Both drivers were installed but the default configuration was mysql
My practice exam still gave me an error, so he installed the patch and now my practice exam with
Assignment Type = "Proctored Test" works.  Thank you!
