### ISSUE TITLE
no summary div for simple format from render_rpc

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2370]
Here is a render_rpc call to our WW test server (currently at the tip of develop):

https://webwork-test.pcc.edu/webwork2/render_rpc?courseID=orcca&userID=orcca&password=anonymous&course_password=orcca&answersSubmitted=0&showSolutions=1&displayMode=MathJax&outputformat=simple&problemSeed=1&problemSource=RE9DVU1FTlQoKTsKbG9hZE1hY3JvcygiUEdzdGFuZGFyZC5wbCIsIk1hdGhPYmplY3RzLnBsIiwiUEdNTC5wbCIsIkFuc3dlckZvcm1hdEhlbHAucGwiLCJwYXJzZXJPbmVPZi5wbCIsIlBHY291cnNlLnBsIiwpO1RFWFQoYmVnaW5wcm9ibGVtKCkpO0NvbnRleHQoKS0%2BdmFyaWFibGVzLT5hcmUoKTsKZm9yIG15ICRpICgxLi4yNikgewogICAgQ29udGV4dCgpLT52YXJpYWJsZXMtPmFkZCgkQUxQSEFCRVRbJGktMV09PidSZWFsJyk7CiAgICBDb250ZXh0KCktPnZhcmlhYmxlcy0%2BYWRkKGxjKCRBTFBIQUJFVFskaS0xXSk9PidSZWFsJyk7CiAgICB9OwpDb250ZXh0KCktPnN0cmluZ3MtPmFkZCgneWVhcnMnPT57fSk7CkNvbnRleHQoKS0%2Bc3RyaW5ncy0%2BYWRkKCd5ZWFyJz0%2Be2FsaWFzPT4neWVhcnMnfSwgJ3lycyc9PnthbGlhcz0%2BJ3llYXJzJ30sICd5cic9PnthbGlhcz0%2BJ3llYXJzJ30sICd5Jz0%2Be2FsaWFzPT4neWVhcnMnfSwgJ3lycy4nPT57YWxpYXM9Pid5ZWFycyd9LCAneXIuJz0%2Be2FsaWFzPT4neWVhcnMnfSwgJ3kuJz0%2Be2FsaWFzPT4neWVhcnMnfSk7CgpDb250ZXh0KCktPnN0cmluZ3MtPmFkZCgnaG91cnMnPT57fSk7CkNvbnRleHQoKS0%2Bc3RyaW5ncy0%2BYWRkKCdob3VyJz0%2Be2FsaWFzPT4naG91cnMnfSwgJ2hycyc9PnthbGlhcz0%2BJ2hvdXJzJ30sICdocic9PnthbGlhcz0%2BJ2hvdXJzJ30sICdoJz0%2Be2FsaWFzPT4naG91cnMnfSwgJ2hycy4nPT57YWxpYXM9Pidob3Vycyd9LCAnaHIuJz0%2Be2FsaWFzPT4naG91cnMnfSwgJ2guJz0%2Be2FsaWFzPT4naG91cnMnfSk7CgpDb250ZXh0KCktPnN0cmluZ3MtPmFkZCgnbWlsZXMnPT57fSk7CkNvbnRleHQoKS0%2Bc3RyaW5ncy0%2BYWRkKCdtaWxlJz0%2Be2FsaWFzPT4nbWlsZXMnfSwgJ21pcyc9PnthbGlhcz0%2BJ21pbGVzJ30sICdtaSc9PnthbGlhcz0%2BJ21pbGVzJ30sICdtJz0%2Be2FsaWFzPT4nbWlsZXMnfSwgJ21pcy4nPT57YWxpYXM9Pidob3Vycyd9LCAnbWkuJz0%2Be2FsaWFzPT4nbWlsZXMnfSwgJ20uJz0%2Be2FsaWFzPT4nbWlsZXMnfSk7CgpDb250ZXh0KCktPnN0cmluZ3MtPmFkZCgnc3F1YXJlIGZlZXQnPT57fSk7CkNvbnRleHQoKS0%2Bc3RyaW5ncy0%2BYWRkKCdmdF4yJz0%2Be2FsaWFzPT4nc3F1YXJlIGZlZXQnfSwgJ2ZlZXQgc3F1YXJlZCc9PnthbGlhcz0%2BJ3NxdWFyZSBmZWV0J30sICdmZWV0IHNxdWFyZSc9PnthbGlhcz0%2BJ3NxdWFyZSBmZWV0J30sICdzcSBmdCc9PnthbGlhcz0%2BJ3NxdWFyZSBmZWV0J30sICdzcWZ0Jz0%2Be2FsaWFzPT4nc3F1YXJlIGZlZXQnfSwgJ3NxLiBmdC4nPT57YWxpYXM9PidzcXVhcmUgZmVldCd9LCAnZnQuXjInPT57YWxpYXM9PidzcXVhcmUgZmVldCd9KTsKJGE9T25lT2YoJ2EnLCdBJywneCcsJ3knLCd6Jyk7CiR0PU9uZU9mKCd0JywnVCcsJ3gnLCd5JywneicpOwoKQkVHSU5fUEdNTApJZGVudGlmeSBhIHZhcmlhYmxlIHlvdSBtaWdodCB1c2UgdG8gcmVwcmVzZW50IGVhY2ggcXVhbnRpdHkuIFRoZW4gaWRlbnRpZnkgd2hhdCB1bml0cyB3b3VsZCBiZSBtb3N0IGFwcHJvcHJpYXRlLgphLiAgTGV0IFtfXXskYX17Mn0gYmUgdGhlIGFnZSBvZiBhIHN0dWRlbnQsIG1lYXN1cmVkIGluIFtfXXsneWVhcnMnfXsxMH0uCgoKYS4gIExldCBbX117JHR9ezJ9IGJlIHRoZSBhbW91bnQgb2YgdGltZSBwYXNzZWQgc2luY2UgYSBkcml2ZXIgbGVmdCBQb3J0bGFuZCwgT3JlZ29uLCBib3VuZCBmb3IgQm9pc2UsIElkYWhvLCBtZWFzdXJlZCBpbiBbX117J2hvdXJzJ317MTB9LgoKCmEuICBMZXQgW19deyRhfXsyfSBiZSB0aGUgYXJlYSBvZiBhIHR3by1iZWRyb29tIGFwYXJ0bWVudCwgbWVhc3VyZWQgaW4gW19deydzcXVhcmUgZmVldCd9ezEwfS4KCgoKRU5EX1BHTUwKCkJFR0lOX1BHTUxfU09MVVRJT04KYS4gIFRoZSB1bmtub3duIHF1YW50aXR5IGlzIGFnZSwgd2hpY2ggd2UgZ2VuZXJhbGx5IG1lYXN1cmUgaW4geWVhcnMuIFNvIHdlIGNvdWxkIHNheToKCiAgICAiTGV0IFtgYWBdIGJlIHRoZSBhZ2Ugb2YgYSBzdHVkZW50LCBtZWFzdXJlZCBpbiB5ZWFycy4iCgoKYS4gIFRoZSBhbW91bnQgb2YgdGltZSBwYXNzZWQgaXMgdGhlIHVua25vd24gcXVhbnRpdHkuIFNpbmNlIHRoaXMgaXMgYSBkcml2ZSBmcm9tIFBvcnRsYW5kIHRvIEJvaXNlLCBpdCB3b3VsZCBtYWtlIHNlbnNlIHRvIG1lYXN1cmUgdGhpcyBpbiBob3Vycy4gU28gd2UgY291bGQgc2F5OgoKICAgICJMZXQgW2B0YF0gYmUgdGhlIGFtb3VudCBvZiB0aW1lIHBhc3NlZCBzaW5jZSBhIGRyaXZlciBsZWZ0IFBvcnRsYW5kLCBPcmVnb24sIGJvdW5kIGZvciBCb2lzZSwgSWRhaG8sIG1lYXN1cmVkIGluIGhvdXJzLiIKCgphLiAgVGhlIHVua25vd24gcXVhbnRpdHkgaXMgYXJlYS4gQXBhcnRtZW50IGFyZWEgaXMgdXN1YWxseSBtZWFzdXJlZCBpbiBzcXVhcmUgZmVldC4gU28gd2UnbGwgc2F5OgoKICAgICJMZXQgW2BBYF0gYmUgdGhlIGFyZWEgb2YgYSB0d28tYmVkcm9vbSBhcGFydG1lbnQsIG1lYXN1cmVkIGluIFtgXHRleHR7ZnR9XjJcdGV4dHsufWBdIgoKCgpFTkRfUEdNTF9TT0xVVElPTgoKRU5ERE9DVU1FTlQoKTs%3D

If you try this and enter some answer to check, then the summary lines below the problem:
```
You received a score of 33% for this attempt.

You can earn partial credit on this problem.

Your score was not recorded.
```
are in HTML `p` tags without a surrounding `div`. I've been looking but I can't find where I would add such a `div`, or if that's even possible with this mechanism. I'd like to add such a `div` with an `id` so that it can be quashed when desired.

Note that when a problem is rendered in the usual way in webwork2, these lines are inside a `<div id="score_summary">`.

**Comment by drgrice1** [comment]
That is added in `templates/RPCRenderFormats/default.html.ep`.

**Comment by Alex-Jordan** [comment]
OK, thanks. I'll add a div there and open a PR.
