### ISSUE TITLE
new warning on development server

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2375]
Today on my development server after pulling, I am getting a warning at the admin course login screen:

```
Use of uninitialized value $hostname in string ne at /opt/webwork/webwork2/lib/WeBWorK/Controller.pm line 76.
```

Entering my username and password does not let me in, it just returns me to the same screen with the same error message.

**Comment by drgrice1** [comment]
How many courses were you signed into?  That is the warning that you get when the issue I was talking about in https://github.com/openwebwork/webwork2/pull/2334#issuecomment-2000136974 occurs.

**Comment by drgrice1** [comment]
You might also check to see if there are cookies left over from other courses that you no longer have open, but that you were previously signed into without logging out.  Those cookies also contribute to the limit.
