### ISSUE TITLE
getting logged out if I visit problem editor or library browser

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2381]
Since advancing my production server to `develop` (plus a few uncommitted changes), when I am in a course and visit the library browser, and I refine the subject select (say to Calculus - single variable) then I get an error like:

<img width="415" alt="Screenshot 2024-03-26 at 1 57 15 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/31a8edad-2113-4a77-959b-64fdd43f4d51">

Also if I go the problem editor, it fails to render the problem and I get:

<img width="1103" alt="Screenshot 2024-03-26 at 2 00 56 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/b83fe1f9-48fe-48a3-82ef-e3e703100f44">

After either of these things, I am logged out (if I try to navigate somewhere, I'm taken to the login screen).

I have cleared all cookies for the site, and I reverted all session/cookie config settings to the distribution defaults, except I have only the admin course using 2FA. But I get the same behavior. I have not been able to reproduce this on my pure development server though, so I'm not sure what is going on.

**Comment by Alex-Jordan** [comment]
And the same thing if I try to render problems in a set detail page.

**Comment by Alex-Jordan** [comment]
Changing session management to key gets me past this for the problem editor and set details pages, but not for the library browser page issue.

**Comment by drgrice1** [comment]
So I am seeing this issue with `session_management_via = 'key'` on the library browser page and the develop branch.  I will look into that.

I am also seeing the more general issue with cookies when using the lti-content-item-selection branch for pull request #2322 which I believe you are using.  So I will look into that also.

**Comment by Alex-Jordan** [comment]
OK, thanks for your insight with this. If you do make changes to that branch, for now would you mind keeping any changes on new commits for now? It will help me follow along until this is ironed out.

I can always revert to not having that branch, but it would be nice to have that for spring term, and it's also helping to go through this process now with our D2L team.

**Comment by drgrice1** [comment]
#2382 fixes the develop branch.  Most likely there was a merge issue for #2322, but I will investigate that now.

**Comment by drgrice1** [comment]
Okay, the `lti-content-item-selection` branch is also fixed.  I pushed it in the last commit.  Note that that branch is not on top of develop anymore although it does merge (or rebase) cleanly.

**Comment by Alex-Jordan** [comment]
Thanks, I can confirm things are working for me too. I'll close this.

**Comment by drgrice1** [comment]
This issue is technically not fixed until #2382 is merged.  But we won't forget the issue!
