### ISSUE TITLE
How to hide the results from the student?

### ISSUE THREAD

**Issue by joecheriross** [openwebwork/webwork2#2389]
I would like to hide the result of the student's answer while he attempts the question. I don't want the student to know whether his answer is correct or not before the deadline. How can I do that on the recent version of Webwork?

**Comment by drgrice1** [comment]
This can't be done with regular homework assignments (other than perhaps by using a custom problem grader and hacking things with problem authoring).  This is an option for tests though.

Note that this is not the correct place to ask questions like this.  This is for issues/bugs in the code.  Questions like this should be asked on the forums at https://webwork.maa.org/moodle/mod/forum/index.php?id=3.

**Comment by joecheriross** [comment]
Thank you Glenn.
