### ISSUE TITLE
File Manager double click not working correctly in Google Chrome

### ISSUE THREAD

**Issue by drgrice1** [openwebwork/webwork2#2428]
If you double click on a file or directory in the file manager using the Google Chrome browser, there is a console log error, and the view action does not occur.  This is not technically a webwork bug, but is a Google Chrome bug.  See https://support.google.com/chrome/thread/277009331/double-click-no-more-work-on-chrome-and-edge?hl=en.  However, if this isn't fixed, we may need to implement a work around.

Note that you can click on a file (selecting it), and then double click, and then the view action works.  Or just click rapidly until the view action does occur!

**Comment by Alex-Jordan** [comment]
I can't reproduce this. Maybe the Chrome bug has been fixed? Can you check to confirm?

**Comment by drgrice1** [comment]
It does seem that the Chrome bug has been fixed.  This is not happening for me anymore.  I will close this.
