### ISSUE TITLE
Is UTF-8 broken in infoboxes after upgrade to 2.19?

### ISSUE THREAD

**Issue by robert-marik** [openwebwork/webwork2#2429]
Hello, after the upgrade to 2.19 I have problems that the texts from infoboxes (the text on the right margin of the page) to the server and to the course are not displayed properly. The non-ASCII letters are broken. The infoboxes to the homeworks are OK, but load as corrupted if I try to edit. See the following image. The text should be "Toto WeBWorK zadání 10_Shrnuti z předmětu Aplikovaná matematika má datum odevzdání pátek 31. května 2024 v 20:00 hodin (podle CEST). Informace o systému WebWorK v češtině nalezenete zde. Webová stránka předmětu je zde."

![image](https://github.com/openwebwork/webwork2/assets/2342862/b6c32f5d-b22f-4262-82eb-fc07954f960e)

I used https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.19#Upgrade_Instructions for upgrade, nothing else has been changed. The problem also appears if I create new course and write something to the Course information.

**Comment by robert-marik** [comment]
Thank you very much for checking this issue.

* Attached the file our_site_info.txt [our_site_info.txt](https://github.com/user-attachments/files/15787919/our_site_info.txt) which renders as follows
  ![image](https://github.com/openwebwork/webwork2/assets/2342862/16aa9419-79a7-4e42-8aec-dee65098b310)

* Attached the file course_info.txt [course_info.txt](https://github.com/user-attachments/files/15787999/course_info.txt) which renders as follows.
  
  ![image](https://github.com/openwebwork/webwork2/assets/2342862/d7c84052-6766-49b5-937c-07409f8bd4e7)

* Attached the pg file with header to the set. The pg file appears fine on the webpage with the assignment, but turns broken when opened in the editor (the txt suffix added to allow upload to github). 
[ASimpleCombinedHeaderFile.pg.txt](https://github.com/user-attachments/files/15788070/ASimpleCombinedHeaderFile.pg.txt)
  
  ![image](https://github.com/openwebwork/webwork2/assets/2342862/93e61fa1-40ff-4e9a-933b-4ea7a6fbe025)

* Observed another issue: with essay question. Compare how it appears when the student works with the question and how it appears if I click "Grade problem". The file is https://github.com/robert-marik/hw-webwork/blob/master/AM_10/15.pg
   
  ![Untitled](https://github.com/openwebwork/webwork2/assets/2342862/54fbbd6d-6a94-4345-831f-f18c32124360)

**Comment by robert-marik** [comment]
And a similar problem is when I use WeBWorK as a web service: https://um.mendelu.cz/webwork2/html2xml?&answersSubmitted=0&sourceFilePath=problems/derivace_pouziti/hromada.pg&problemSeed=739&displayMode=MathJax&courseID=daemon&userID=demon&course_password=demonek&outputformat=simpleM&language=cs_CZ

The source is https://github.com/robert-marik/daemon-webwork/blob/main/derivace_pouziti/hromada.pg and after upgrade to 2.19 renders as follows.

![image](https://github.com/openwebwork/webwork2/assets/2342862/9c0bc2c8-f540-4c05-9865-d2c6ba0ce4a0)

**Comment by drgrice1** [comment]
I have now tested all of the files you posted on my server.  Not one of them has the issues that you are showing in your screenshots on my server (see the screenshots below).  So there is something different with your setup that is causing this issue.  It is probably a difference in a Perl dependency that you have installed that is a different version that what I have.  I am not sure how to track that down.

By the way, did any of this happen with WeBWorK 2.18?

Here are some screenshots of what I see:
![course-info](https://github.com/openwebwork/webwork2/assets/47527406/1ba72384-0bba-45e6-8e0b-01cbd333967b)
![set-info](https://github.com/openwebwork/webwork2/assets/47527406/fb24261c-a9be-4416-b0df-0feb6b58a420)
![site-info](https://github.com/openwebwork/webwork2/assets/47527406/73e1cce9-3fd9-434c-ae70-95cb1668459e)
![webservice](https://github.com/openwebwork/webwork2/assets/47527406/5f4f85b6-88b3-4370-9199-d78c14972abf)

**Comment by robert-marik** [comment]
Thank you for checking the files. The issue appears just after the upgrade to 2.19. For now I downgraded back to 2.18 (and restored the database which has been upgraded to 2.19).

Thank you very much.

**Comment by drgrice1** [comment]
The problem with you reverting to 2.18 is that this doesn't give us a way to figure out what the actual problem is.  It will not be fixed if we can't do that.

**Comment by robert-marik** [comment]
I see. Anyway, as I understand, the problem is not in WeBWorK, but there is a problem in my server configuration. I tested another one with the same result. Will look further and let know, will play with docker image and locale settings etc and if I find the solution, I will post it here. Thank you for your help.

**Comment by robert-marik** [comment]
Tried to track the problem. At least partial success. The texts before https://github.com/openwebwork/webwork2/pull/2416/commits/567b80822165d1956a9260e06cdf73a0a0de1afe are fine, after this commit I have problems with file coding.

After 
```
git reset --hard 264b4ac91e96a090ae5609e270b5445664823a60
```
the texts are fine. They become broken after installing the next patch with
```
git reset --hard 567b80822165d1956a9260e06cdf73a0a0de1afe
```

**Comment by drgrice1** [comment]
There were things in that pull request that change how files are read, which is related.  However, as noted, those changes don't cause the issue for me (and no others have chimed in with this issue as of yet either).  So unfortunately, that still doesn't help us with what is different on your system that is causing things to not work.

**Comment by robert-marik** [comment]
Thank you for your help. Did another try to find the source of the problem: installed virtual machine from https://webwork.maa.org/wiki/WeBWorK_2.18_Ubuntu_Server_22.04_LTS_Virtual_Machine_Image and wrote the text "Na serveru je nainstalován základní systém WeBWorK 2.18 v nejnovější verzi (léto 2023) a lokalizace studentské části systému do češtiny." into site_info.txt. With 2.18 everything OK on the main page. After upgrade to 2.19 the text is broken.

![image](https://github.com/openwebwork/webwork2/assets/2342862/b0cd93c2-b68e-4af8-bc80-72d3445c0ffc)

[site_info.txt](https://github.com/user-attachments/files/15803351/site_info.txt)

Tried also direct edit of course info in WW. Also with bad output. The text is fine when editing and in the preview window, but becomes broken after saving.

![image](https://github.com/openwebwork/webwork2/assets/2342862/c7018638-4203-4e77-adbb-901918a1ae2c)

**Comment by drgrice1** [comment]
Install Mojolicious from cpan with `sudo cpanm Mojolicious`.  The version of Mojolicious in the Ubuntu 22.04 repositories is no longer sufficient.  Make sure to reload the webwork2 app after doing this with `sudo systemctl reload webwork2`.  This will need to be added to the upgrade notes.

**Comment by robert-marik** [comment]
Works fine, thank you.
