### ISSUE TITLE
$authen{admin_module} must be a subset of $authen{user_module}

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#2446]
In my setup here I have the following:

```
$authen{user_module} = [
        { '*' => 'WeBWorK::Authen::LTIAdvanced' },
        { '*' => 'WeBWorK::Authen::LDAP' },
];
$authen{admin_module} = [
        'WeBWorK::Authen::Basic_TheLastOption'
];
```

And I was not able to login to my admin course because the `admin_module` was not a subset of the `user_module`.

Logic for my setup, `WeBWorK::Authen::LDAP`, already provides an option to only use basic/local passwords for users that do not exist, but will not use this for users that do, which I had configured. I am the only user who isn't using LDAP, so for the admin course I just setup 2fa with basic login, but cannot use it unless I also add the option to the `user_module`.

Is there any reason why the `admin_module` must be a subset of `user_module`?

**Comment by Alex-Jordan** [comment]
Addressed by #2493.
