### ISSUE TITLE
Issues loading Webwork page after upgrade

### ISSUE THREAD

**Issue by aweaver1fandm** [openwebwork/webwork2#2506]
I just upgraded from an older version of webwork, 2.16, to the newer version following instructions here(.https://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.18#Upgrade_Instructions)

I am able to browse to the proper URL but I have at two problems.

1. The page shows numerous warning messages about uninitialized values (see attached image)
![Screenshot from 2024-08-12 13-26-20](https://github.com/user-attachments/assets/444c7078-3867-441b-8006-e68c65782914)

2. The upgrade_admin_db.pl script seemed to fail.  Output from the command-line is given below, and when I click on a course in my browser I get a message about a missing column and needing to run upgrade_admin_db.pl
```
upgrade_admin_db.pl 
Use of uninitialized value $courseName in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 130.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Use of uninitialized value $courseName in regexp compilation at /opt/webwork/webwork2/lib/WeBWorK/Utils/CourseIntegrityCheck.pm line 141.
Table achievement created as ____achievement in database.
Table achievement_user created as ____achievement_user in database.
Table global_user_achievement created as ____global_user_achievement in database.
Table key created as ____key in database.
Table password created as ____password in database.
Table past_answer created as ____past_answer in database.
Table permission created as ____permission in database.
Table problem created as ____problem in database.
Table problem_user created as ____problem_user in database.
Table set created as ____set in database.
Table set_locations created as ____set_locations in database.
Table set_locations_user created as ____set_locations_user in database.
Table set_user created as ____set_user in database.
Table setting created as ____setting in database.
Table user created as ____user in database.
```

**Comment by drgrice1** [comment]
Please do not post issues like this here.  This is not an issue with the webwork2 code.  This is an issue with you following what are now outdated instructions.  You used the `main` branch of the webwork2 and pg repositories as the 2.18 instructions indicated.  However, 2.19 was just released.  So you need to following the 2.19 instructions instead.  We need to upgrade the wiki for all old versions, but once a release occurs the main branch is the latest release.  If you want to still use 2.18, then to get the older version you need to check out the tag for the older release and not use the `main` branch.  Use `git checkout -b WeBWorK-2.18+ WeBWorK-2.18+` to do this.  You will also need to do the same for pg with `git checkout -b PG-2.18+ PG-2.18+`.

**Comment by aweaver1fandm** [comment]
Glenn,

Thank you, I knew I was using some outdated instructions.  I was hoping it
would be close enough to work.  Do you happen to know when upgrade
instructions for 2.19 might be online?

**Comment by drgrice1** [comment]
They already are!  Although, they are still marked as in construction.  However, they should work fine.  They are at https://webwork.maa.org/wiki/Installation_Manual_for_2.19_on_Ubuntu.  They actually aren't that different than for 2.18.  One important new thing is that you set the `$admin_course_id` in `site.conf`.  That is what is causing all of your errors that you showed.

**Comment by drgrice1** [comment]
By the way, the best venue for this kind of question is https://webwork.maa.org/moodle/mod/forum/view.php?id=6.

**Comment by aweaver1fandm** [comment]
Thanks,  I think I was following an upgrade link from the main openwebwork
page that took me to 2.18.  I'll go through those instructions and see what
I may have missed

**Comment by aweaver1fandm** [comment]
Got it thanks.
