### ISSUE TITLE
File not read with same character encoding in editor as for regular use

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2508]
I'm attaching a problem file. On my 2.19 PCC installation, this problem works fine when it's used in a set and a user runs it that way. Note the special character `℃` is used.

<img width="1260" alt="Screenshot 2024-08-12 at 5 20 51 PM" src="https://github.com/user-attachments/assets/7173d293-76eb-4a4f-b60e-e507f2bca7e2">

But when editing this problem, we see:

<img width="1378" alt="Screenshot 2024-08-12 at 5 22 41 PM" src="https://github.com/user-attachments/assets/dd7e3823-192f-404b-914b-c66367bf2a33">

Note how the `℃` character has been decoded in some other way in the editor. Then MathJax has an issue with it in the rendering. We see the same issue if viewing the problem in the Set Details page and Library Browser.

I don't really care about the `℃` character, and could replace that in this instance. But if we are moving to support more unicode characters in .pg problem files, then there is something wrong with the file being read one way for regular rendering, and differently in these other places.

[1_8_6_48.txt](https://github.com/user-attachments/files/16592950/1_8_6_48.txt)

**Comment by somiaj** [comment]
@Alex-Jordan I am not able to reproduce this (maybe copy/paste of the character in the .txt file changed something), but when I copy/paste the problem you attached in my problem editor I see the following:

![image](https://github.com/user-attachments/assets/3b2ea134-3f55-44ad-b7c1-dde15b3a8e3e)

Notice now in my editor I can see the Unicode character, but in your editor you just see some garbled mess. Maybe some issue with the codemirror editor and UTF on your system garbling the character causing the editor to fail?

**Comment by Alex-Jordan** [comment]
Copy-pasting might not faithfully replicate the issue. Can you take the file and upload it to the server and then try to edit it?

**Comment by somiaj** [comment]
Never mind, I can reproduce it if I save your file as a .pg file and load it that way (I also notice this issue occurs in the library browser as well as the editor), so something with how the RPC deals with problems differently than a pure problem page is my guess to the difference. It just worked when I copy/pasted the file in my initial testing.

I also notice that if I copy/paste the problem into the editor it works, but if I save it and load it again it fails. So it appears to me the corruption is occurring when the RPC connection is loading the text of the problem.

**Comment by somiaj** [comment]
Well occurs when the editor or library browser is loading the problem.

**Comment by drgrice1** [comment]
I am not able to reproduce this.  I downloaded the file that you posted, and I don't see the encoding errors in the pg problem editor.

**Comment by drgrice1** [comment]
I also tested in the library browser, and I still don't see the issue.

**Comment by Alex-Jordan** [comment]
If @somiaj and I see it, but you do not, maybe it comes down to something in our OS, perl version, etc.

**Comment by drgrice1** [comment]
It could also be a browser issue.  What browsers are you testing with?  I tested with Firefox, but will try Chrome now.

**Comment by Alex-Jordan** [comment]
For me it's a Mac with Firefox.

The server OS is Oracle 8, perl is 5.36.1. Not sure what perl module versions might be in play for this.

**Comment by drgrice1** [comment]
No issue for me with Chrome either.  I tested on my local development server with Ubuntu 24.04 (perl version 5.38), and on my production server with Ubuntu 22.04 (perl version 5.34).  Neither had issue.

I am not sure what Perl modules to look into right off hand, but it would be something to do with file IO.  Mojolicious is now used directly, but it uses other modules to do the actual IO.

**Comment by somiaj** [comment]
I think I tracked it down. After testing this, I recalled that this is was one of the reason why the newer version of mojolicious is required. I have been lazy and never installed a newer version on my dev server, so I upgraded my server to use mojolicious 9.37 and the issue goes away.

**Comment by Alex-Jordan** [comment]
I have 9.33 right now. Will upgrade and see.

**Comment by drgrice1** [comment]
I am using Mojolicious 9.37 on all of my servers, so that is probably it.  I thought that I had fixed everything so that older versions would work fine, but I must have missed something.

**Comment by Alex-Jordan** [comment]
Earlier when I upgraded the RS server to 2.19, the Mojolicious version was so old that I *had* to upgrade it for webwork2 to load. I did not note what version that was.

Here with the PCC server, apparently 9.33 was not old enough to stop me from loading webwork2.

**Comment by Alex-Jordan** [comment]
At 9.37 now, and the issue is resolved.

For posterity: I must have multiple perl installations, and one of them told me Mojolicious was 9.33. When I used cpan to upgrade just now, it said that it upgraded form 9.32 to 9.37. And the issue is resolved. So the version that was in use before must have been 9.32, not 9.33.

**Comment by somiaj** [comment]
Seems we bumped `check_modules.pl` to require 9.34, but it was due to small issues like this, I upgraded from `9.31`, so older versions mostly work.

**Comment by drgrice1** [comment]
Yeah, 9.33 should work... Wait, I just looked at `lib/WeBWorK/Utils/Files.pm`.  It is using the `path($fileName)->slurp('UTF-8')` call.  I thought that I had reverted that to not directly use the 'UTF-8' argument (which was added in Mojolicious 9.34), and to instead do that in our code.  That is the reason for this.

**Comment by drgrice1** [comment]
Try changing line 48 of `lib/WeBWorK/Utils/Files.pm` to
```
		eval {
		   	$result = path($fileName)->slurp;
			$result = decode('UTF-8', $result)
	   	};
```

**Comment by Alex-Jordan** [comment]
I think both @somiaj and I have already upgraded to 9.37 and can't test that change without reverting.

**Comment by somiaj** [comment]
I just reverted, to test. Since I built a .deb to upgrade, it was easy to downgrade.

@drgrice1, that files as `decode` is not defined, it needs to be imported first?

**Comment by somiaj** [comment]
@drgrice1 I think we only talked about reverting this, but in the end we decided to require mojolicious 9.34 now instead of later to get people to upgrade.

**Comment by drgrice1** [comment]
Nevermind, I see that we merged https://github.com/openwebwork/webwork2/pull/2432 instead.  The decision was made to not try to support older versions of Mojolicious, and to instead change the required version to 9.34 or newer.

(Yeah, I forgot to mention you need to `use Mojo::Util qw(decode)`.

**Comment by drgrice1** [comment]
If you run `check_modules` it should complain that your version is not new enough with 9.33.

**Comment by Alex-Jordan** [comment]
Yeah, it did complain about that. I hadn't checked on the PCC server since it already was X% of the way to 2.19 anyway.

What is noteworthy though is that even with 9.32, I could `systemctl restart` webwork2. But with whatever version was running on the RS server following pulling from 2.18 to 2.19, if I `systemctl restart`ed webwork2, it failed.

**Comment by drgrice1** [comment]
Yeah, 9.32 should work with everything else, and even the `slurp` call will work.  However, any version before 9.34 will ignore the 'UTF-8' decoding argument that is now passed to `slurp`.  So the call will succeed, but the resulting data will not be UTF-8 decoded.

There are probably other things that have changed that will also break older versions of Mojolicious, and apparently whatever version the RS server was on has a worse issue with our current code.
