### ISSUE TITLE
Error creating admin course

### ISSUE THREAD

**Issue by miralgj** [openwebwork/webwork2#2536]
On a fresh new install of 2.19 using MySQL Community Server v8.4, when attempting to create the admin course using the command `$WEBWORK_ROOT/bin/addcourse admin --db-layout=sql_single --users=$APP_ROOT/courses/adminClasslist.lst --professors=admin` I am getting the following error:

```
DBD::mysql::db do failed: BLOB, TEXT, GEOMETRY or JSON column 'session' can't have a default value at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 930.
```

I knew the installation instructions for 2.19 state that MariaDB is recommended but it also states that MySQL is ok to use. Is this error due to an incompatible database?

**Comment by drgrice1** [comment]
What version of MySQL is that?  Also, are you using the `DBD::mysql` or `DBD::MariaDB` perl database driver module?

I believe that recent versions of MySQL do support default values for TEXT columns, but may be mistaken.  However, the `DBD::mysql` driver may not.  You could try the `DBD:MariaDB` driver instead.

If MySQL still does not support default values for TEXT columns, then perhaps it is time to say that we stop supporting use of MySQL.

**Comment by dlglin** [comment]
From the MySQL docs (https://dev.mysql.com/doc/refman/8.4/en/data-type-defaults.html):
The [BLOB](https://dev.mysql.com/doc/refman/8.4/en/blob.html), [TEXT](https://dev.mysql.com/doc/refman/8.4/en/blob.html), GEOMETRY, and [JSON](https://dev.mysql.com/doc/refman/8.4/en/json.html) data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal:

This is permitted (literal default specified as expression):
```
CREATE TABLE t2 (b BLOB DEFAULT ('abc'));
```
This produces an error (literal default not specified as expression):
```
CREATE TABLE t2 (b BLOB DEFAULT 'abc');
```

**Comment by drgrice1** [comment]
@dlgin: I saw that too.  That is why I suggested switching to the `DBD::MariaDB` perl database driver module.  It may take care of that, and the `DBD::mysql` module may not be updated to handle that.  Another possibility is to try changing line 33 of `lib/WeBWorK/DB/Record/Key.pm` to `session   => { type => "TEXT NOT NULL DEFAULT ('{}')" }`.  So @miralgj, could you try that and see if that resolves the issue?  If it does, then I will make a pull request with that change.

**Comment by miralgj** [comment]
> @dlgin: I saw that too. That is why I suggested switching to the `DBD::MariaDB` perl database driver module. It may take care of that, and the `DBD::mysql` module may not be updated to handle that. Another possibility is to try changing line 33 of `lib/WeBWorK/DB/Record/Key.pm` to `session => { type => "TEXT NOT NULL DEFAULT ('{}')" }`. So @miralgj, could you try that and see if that resolves the issue? If it does, then I will make a pull request with that change.

That does indeed resolve the issue. Thanks!

**Comment by somiaj** [comment]
The fix has been merged, so closing.
