### ISSUE TITLE
check_latex can't find pg.sty

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#2543]
When I run `check_latex` I get "! LaTeX Error: File `pg.sty' not found."

A bit of digging shows that the value of `$ce->{pg}{directories}{assetsTex}` is "/assets/tex", which is not correct.

I believe that the problem is that `$pg_dir` is defined in webwork2.mojolicious.yml (or the .dist version), but when a WW CE is invoked from the command line the mojolicious config is not loaded, so `$pg_dir` is never set, which means that any paths that are built from that will be incorrect.

If I'm right this means that `check_latex` won't work for anyone in 2.19.  Can someone confirm whether it works for them?

**Comment by Alex-Jordan** [comment]
I confirm on the two 2.19 servers that I checked, that I get the same error about `pg.sty`.

**Comment by Alex-Jordan** [comment]
When I check this on my production servers (PCC and RS) `check_latex` fails.  But just now I was testing Glenn's PR to address this. And I found that on my devleopment server, on the develop branch, `check_latex` runs with success. (On the develop branch, not just with Glenn's fix.)

**Comment by drgrice1** [comment]
You probably have the `PG_ROOT` environment variable set.  If you have set to the PG directory, then the script will still succeed, because it finds the PG directory that way rather than the new way of getting it from the configuration file.

**Comment by drgrice1** [comment]
By the way, when @dlglin first posted this issue and I tested it, I saw the same thing.  Then I `unset $PG_ROOT` and tried again.  Then I saw the failure.

**Comment by somiaj** [comment]
This was fixed by #2545 and hotfix #2546.
