### ISSUE TITLE
The Problem Sets (landing) page looks incomplete if there are no sets assigned to a user

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#2550]
If there are no sets assigned to a user then the Problem Sets page looks incomplete.  It's not clear to me that there are no sets available, or whether I have to navigate somewhere else to find my homework.

Perhaps in this case we could display something like "There are no sets available to you at this time".

**Comment by somiaj** [comment]
This was addressed by #2551 and hotfix #2555.
