### ISSUE TITLE
Feature request: Customize date format separately from the language

### ISSUE THREAD

**Issue by szhorvat** [openwebwork/webwork2#2552]
This is a feature request to allow customizing the date format that instructors use when setting deadlines, independently of the WeBWorK language.

Currently this date format cannot be customized independently of the language. For as long as WeBWorK is set to English, it will use the US format, i.e. month/day/year. This format is almost unheard of outside of North America, and will be confusing for many people. I certainly find it confusing to have to mentally switch to it, and it caused me to set incorrect dates multiple times in the past.

Note that this refers to how we set dates in the WeBWorK interface, not how dates are displayed to students.

(This is a distilled down version of #2204.)

**Comment by drgrice1** [comment]
I can not approve this feature request.  It is incorrect (and would be challenging and annoying to implement) to have the date format not match the locale that is set.

However, one thing that could be done is to add other English language variants.  For example, a UK variant could (and should) be added.  That would have the date/time format that you desire.

**Comment by szhorvat** [comment]
I respectfully, and _very strongly_ disagree, not only because of obvious practicality of the situation, but also because of my experience of being a speaker/member of a minority language/culture in my birth country. Treating the concept of "locale" in an inflexible way as you are here very much reminds me of being forced into rigid systems designed without an understanding of minority needs. On modern computer systems, languages, date formats, number formats, calendar systems, and other "localization" aspects are independently adjustable. In many places, there are multiple of these used at the same time. For example, in many places, both d-m-y and y-m-d are commonly used date format (in fact I use the latter on  my devices).

What I asked for was not British English, or adhering to British customs, but the flexibility to choose the date format independently of the language. Please keep in mind that English is used in higher education in many more countries than just the US and the UK.

Please consider giving this more though before rejecting the request, or consulting with users who are directly affected by this decision.

That's all I have to say on the matter, I'll leave it to you from here.

**Comment by szhorvat** [comment]
First of all, thank you for implementing a practical solution. The way you implemented it (dd/mm/yyyy and HH:mm) addresses my use case perfectly. I assume this will be part of WeBWorK 2.20 next year?

> Your statement that localization of languages, date formats, number formats, etc., be made customizable separately simply isn't going to happen, and is far more rare than you seem to be claiming. Even browsers don't allow such separate customization (neither Firefox nor Google Chrome support that at least).

This is actually not correct. Firefox (whose History view I just check), as well as programs that use standard APIs for date and number formatting (e.g. `ctime()`), take the format from the operating system setting. In other words, the detailed customization part can _in principle_ be offloaded to OS features instead of re-implementing it within WeBWorK—though I understand that doing so is additional work that a manpower-constrained open-source project like WeBWorK might not be able to afford to spend time on.

All that said, I won't need anything else in the foreseeable than the en-GB added in #2553.
