### ISSUE TITLE
Problem editor cannot find images when previewing/checking/showing answers.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#2556]
The image is shown just fine when initially rendered. But when previewing, checking, or showing the correct answer, the image is not found and a warning is issued.  Here is a test problem.

```
DOCUMENT();      
loadMacros(qw(PGstandard.pl PGML.pl PGcourse.pl));

BEGIN_PGML
    [!Alt Text!]{'imagename.png'}

END_PGML
ENDDOCUMENT();
```

The warnings issued are:

+ Unable to find file "imagename.png".
+ Unable to form a URL for the auxiliary file "imagename.png" used in this problem.

**Comment by somiaj** [comment]
@drgrice1 I have a possible fix to this, but I have a feeling it might not be correct. Check out the above commit as I'm unsure if there is a case where we would want the `$problemRecord->source_file` to be empty. The problem appears to be that the hidden field `fileName` is set to an empty string and `PGalias` is no longer able to find images relative to the location of the file being edited.

I have tested the various places problems are rendered (PGProblemEditor, Library browser, set editor, and stats for a single problem) and haven't noticed any issues with this.

I think it would be better if the rendered problem in the PGProblemEditor set the `fileName` hidden field to the temporary file name, but I wasn't able to track down where to do that.

**Comment by drgrice1** [comment]
I believe this is fixed. @somiaj: Please confirm, and close this if it is.

**Comment by somiaj** [comment]
It is fixed, I've been using the fix for a while. I'll close now that it is merged.
