### ISSUE TITLE
Importing a set definition file removes spaces from source_file

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#2563]
When importing a set definition file all spaces are removed from the `source_file` field.  This causes issues if a pg file genuinely has spaces in the filename as the imported set will not have the correct `source_file`.

To reproduce:

1. Create a pg file with a space in the filename and add it to a set.
2. Export the set.  The .def file will include the spaces in the filename.
3. Import the set into a course.  The spaces have been removed from the filename, and the Set Detail page will report that the source file can't be found (unless there happens to be a file with same name with no spaces).

This looks to be done deliberately:
https://github.com/openwebwork/webwork2/blob/647d317f126c4295bc9ef05865598091191f90e4/lib/WeBWorK/File/SetDef.pm#L565
In earlier versions of WW there were problems with including spaces in filenames, but as far as I can tell everything else now works with them.  Can this line be deleted, or might that break something else?

**Comment by drgrice1** [comment]
I think it should be okay.  We will need to test it extensively though.  So a pull request would be good now.  Then it will be thoroughly tested by the next release, and any issues with doing so fixed.

**Comment by drgrice1** [comment]
I am closing this as spaces are no longer stripped from filenames as of #2570.
