### ISSUE TITLE
checkboxes in File Manager get unchecked

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2567]
When I enter the File Manager, the two checkboxes controlling behavior of archive file uploads, "Unpack archives automatically" and "then delete them" are checked.

If I delete a file, there is a confirmation page. After confirming and following through with the delete, those checkboxes are no longer checked.

This is just a little strange. And if you aren't looking at those checkboxes because you have internalized the default behavior, you will miss that now the boxes are unchecked.

**Comment by drgrice1** [comment]
This was fixed with #2569.
