### ISSUE TITLE
perltidy discrepancy

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2626]
When I run `run-perltidy` on `lib/WeBWorK/ConfigValues.pm`, it makes this change, which seems like a good change:

```
@@ -1197,7 +1200,7 @@ sub getConfigValues ($ce) {
                        @$configValues,
                        [
                                x('LTI'),
-                               map      { $LTIConfigValues->{$_} }
+                               map { $LTIConfigValues->{$_} }
                                        grep { defined $LTIConfigValues->{$_} } @{ $ce->{LTIConfigVariables} }
                        ]
                );
```

But this is always rejected by GitHub if this change makes its way into a PR that I open. Why does the GH run want those spaces? Why does the GH run differ from my local run?

**Comment by somiaj** [comment]
What version of `perltidy` do you have installed?

**Comment by Alex-Jordan** [comment]
v20240202

**Comment by somiaj** [comment]
Wonder if it is behavior with a newer version, I am on `20220613` here and I get the same thing the github CI does. Currently I think the CI is running Ubuntu 24.04 which is on version `20230309` from what I can tell.

**Comment by Alex-Jordan** [comment]
OK, well I won't complain. I know this (and a few other things) disagree with GH. I've learned to just quickly patch if one of these slips in and GH rejects what I sent. But I do prefer the change that my version is doing. I don't get the logic behind the spacing that the GH version wants.

**Comment by somiaj** [comment]
Oh I just double checked, the actual CI is still running on Ubuntu 22.04, so maybe this change is older than what I was looking at. But it does appear that if we update the version of perltidy the CI is using, there might be some minor changes to the code. So at least we are now aware of this.

**Comment by drgrice1** [comment]
Version `20220613` of Perl::Tidy is required for development.  Any newer version will give different results.

I agree that newer versions do some nicer things.  Some bugs in alignment have been fixed.  However, they also make some changes to the existing code that are inconsistent.  I have a branch that updates to the newest version of Perl::Tidy, and plan to do that soon.  I have been waiting until some of your pull requests are merged to prevent merge conflicts though.

**Comment by drgrice1** [comment]
Note that the GitHub workflow used version `20220613` of Perl::Tidy also.

**Comment by Alex-Jordan** [comment]
OK, I will close this "issue".
