### ISSUE TITLE
Using a `NAMED_ANS` exercise twice in a test

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2635]
While testing something else, I happened to put an exercise into a test where the exercise used `NAMED_ANS`. And I had that exercise appear twice in the test. I was not aware that the exercise used `NAMED_ANS` when I chose it. Needless to say, I had some very strange behavior when I activated the test. I think because two exercises on the page have the same HTML id (although I exited all that before I checked ids). Actually, even if the two instances were on different pages of the test.

Is there anything to do about this?

**Comment by drgrice1** [comment]
Unfortunately, there is nothing that can be done about this.  What this means is that `NAMED_ANS` was used incorrectly in the problem.  `NAMED_ANS` should never be used with a hard coded answer name.  It should be used with the result of calling `NEW_ANS_NAME`.  If that is done, then the problem can be used multiple times in an assignment even if they are on the same page in a test.

**Comment by drgrice1** [comment]
We need to document rather harshly in general to never use `NAMED_ANS` unless you really know what you are doing and have a real need for it.  Most authors just think that they want to name the answer and do so.  That is not a valid reason to do it.  You really only need to name an answer if you need the name of the answer for something else in the problem (which is rare for most problems), and in that case you should not make up an answer name, but should obtain one from `NEW_ANS_NAME`.
