### ISSUE TITLE
WW3 and problemRandomize.pl

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#444]
When I try to run a problem that uses problemRandomize.pl in the Library Browser or the Problem Set Detail viewer I get a warning about an uninitialized value in a string ne at line 181, which is referring to
```
$main::inputs_ref->{effectiveUser} ne $main::inputs_ref->{user}
```
These problems work when viewed using the WW2 library browser.  My guess is that WW3 isn't setting effectiveUser when its calling PG, but it could be something else.

**Comment by pstaabp** [comment]
I'm back working on this issue.  It appears that that the line that Geoff cited above: 
```
$main::inputs_ref->{effectiveUser} ne $main::inputs_ref->{user}
```
are the standard parameters passed around using requests.  When ww3 is rendering a problem, I have written a general rendering subroutine at /webwork2/webwork3/lib/Utils/LibraryUtils.pm starting on line 27.  This sub builds up the needed information in the hash renderParams and passes it to a WeBWorK::PG object.  

Is there a way to pass the effective user to the PG renderer this way?
