### ISSUE TITLE
Changing Chapters in Library Browser, Section Pull Down Options Don't Change

### ISSUE THREAD

**Issue by emcnelis** [openwebwork/webwork2#476]
In the Library Browser, if I search by selecting a Subject, then Chapter, then Section and then decide to change the Chapter (still in same Subject), the Section pull-down options remain those for the Chapter I looked at previously.  I can't seem to force this to reset.

After selecting the Library Browser again from the Menu (trying to force a refresh) and selecting to choose by subject.  Now after selecting the Subject I don't even have options for Chapter or Section:
![image](https://cloud.githubusercontent.com/assets/7883236/4144384/ed71af44-33de-11e4-8932-8e0fc8ec7353.png)

**Comment by pstaabp** [comment]
I think I just fixed this. I'll leave it open until the branch is pulled into ww3
