### ISSUE TITLE
WW3 Security Issue

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#479]
A lot of the paths for WW3 just check the permission level of the current dancer session.  However, they don't validate the WeBWorK authentication cookie, that the user has the correct permission level in a given course or even that a user exists. 

For example, log into a test course with a test professor.  In my case it was TestCourse, with "testprof".  Then go to `http://webwork.wcu.edu/webwork3/courses/:course/users` for a course 'different' than the course you logged in with.  You should be shown the users in that course.  This happens even if "testprof" is not a member of the course.  

Looking at the code there are a lot of routes with this problem.  Things with 
```
  if(session->{permission} < 10){send_error($PERMISSION_ERROR,403)}
```
and no other user validation code will be vulnerable.   This includes most of Users.pm.   Things with 
```
    checkPermissions(10,session->{user});
```
do check against the WeBWorK session and all routes should do something like that.

**Comment by pstaabp** [comment]
I agree that this will need a more thorough rethinking moving forward.  It doesn't check the permission level set in the course configuration, which it should do as well.  I'll fix this first and then move to a more sophisticated permission checking.
