### ISSUE TITLE
Upgrade Notifier and Old Systems

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#533]
Sometimes on old systems the upgrade notifier will fail.  The message will be something like 
```
Couldn't find WeBWorK Branch master in remote origin
Couldn't find PG Branch master in remote origin
etc...
```
This is caused by the git command failing.  Restarting the web server fixes it temporarily but it will eventually fail again.  The relevant error message (if you add some debugging code) is
```
fatal: full write to remote helper failed: broken pipe
error reading command stream
``` 
I think this only happens on older versions of git but I haven't been able to track down a fix.

**Comment by mgage** [comment]
Possibly the issue is the size of some buffer?:

http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github <http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github>

is one of the hits I found by googling  "fatal full write to remote helper failed broken pipe”

Take care,

Mike

**Comment by goehle** [comment]
I did some poking around and it sounds closer to the issue from this thread:

https://code.google.com/p/skia/issues/detail?id=1630

Although I couldn't find a clear resolution for that.

**Comment by catfarts** [comment]
Can someone help me, please.
I recently installed 2.10 and moved my old database.  Everything seems okay except:
When I log into my new webwork site, I see these messages:
The following upgrades are available for your WeBWorK system:
Couldn't find WeBWorK Branch master in remote origin
Couldn't find PG Branch master in remote origin
Couldn't find OPL Branch master in remote origin

when I run the above command, it looks good:
# git ls-remote https://github.com/openwebwork/webwork2 --verify 'refs/heads/master'
6543eb8286a482c347ffce684472238f78c4573a refs/heads/master

I'd like to view the remote branches, and I tried:
# git branch -r
origin/HEAD -> origin/master
origin/develop
origin/master
origin/ww3

Is this a problem I need to be concerned with or just for-git it?

**Comment by goehle** [comment]
Take a look at:  http://webworkgoehle.blogspot.com/2014/12/upgrade-notifier.html for instructions on how to properly set up the notifier.  Or just set `$enableGitUpgradeNotifier = 0;` in your local overrides file and turn the system off.
