### ISSUE TITLE
Due date issue

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#552]
In 2.10 (and most likely earlier as well) I'm encountering this issue.

If a problem set has a due date, but a student has a modified due date for that problem set, then when the student visits the set, the original unmodified due date is displayed. It's showing that student's due date if they are in the overall list of sets, and it also shows the correct due date for the student in the set header pg blurb. But in the page for the problem set listing the numbers for the problem, the title at the top of the screen indicates the wrong due date.

My development server is down or I would look into fixing this. For now I'm just logging the issue here.

**Comment by goehle** [comment]
This was introduced into 2.10 by me as part of the accessibility stuff because I used `globalSet` and not `mergedSet` like a rookie.  Pull #553 has a fix.
