### ISSUE TITLE
Update Problem: Can't use an undefined value as a HASH reference

### ISSUE THREAD

**Issue by patrickspencer** [openwebwork/webwork2#556]
We have Webwork version 2.9 and pg versino 2.9.

It seems every time I I go to the problem editor, click on Update tab and hit "Take action" I get en error on the next screen that says 

`Can't use an undefined value as a HASH reference at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm line 1087.`

Here's the stack trace

- in WeBWorK::ContentGenerator::Problem::output_checkboxes called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm
- in WeBWorK::Template::template called at line 530 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
- in WeBWorK::ContentGenerator::content called at line 420 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
- in WeBWorK::ContentGenerator::Problem::content called at line 202 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
- in WeBWorK::ContentGenerator::go called at line 370 of /opt/webwork/webwork2/lib/WeBWorK.pm

The problem still saves though, it just gives this error. I've included a screenshot:

![screen shot 2015-01-28 at 3 07 56 pm](https://cloud.githubusercontent.com/assets/1836167/5947002/8bdc2e3c-a6ff-11e4-80c8-d9d0be6a9628.png)

**Comment by goehle** [comment]
Does this happen no matter how you get to the browser and no matter what problem you are editing or only for a specific problem.  Also, if possible could you check if it happens in 2.10?

Thanks.

**Comment by patrickspencer** [comment]
It seems to happen for any problem I try. I will test it on webwork 2.10 this weekend.

**Comment by goehle** [comment]
I loaded up 2.9 and couldn't reproduce it.  It looks like the $path variable for the problem is undefined, which shouldn't happen.  For example the message  is "Saved to File" in your screenshot, but there should be a file name there.  When you are on the problem editor and go to update what  does it say the file name is.

**Comment by patrickspencer** [comment]
It says something like this:

 save to [TMPL]/MizzouLibrary/Algebra/rational_expressions_mult_div/multiply_05_ia.pg

Do you think this could be a server misconfiguration?

**Comment by goehle** [comment]
It could be, I certainly can't reproduce the error here, using either 2.9 or 2.10.  I would keep poking around on your end to see if you can figure anything out.  One thing you can do is check out the tag WeBWorK-2.9+  This is 2.9 with all of its hotfixes and should be safe even for production machines.  I dont remember fixing anything like this, though, so it may not do much.

**Comment by patrickspencer** [comment]
Ok, I'll keep poking around. The fact that you can't reproduce it helps. Thank you.

**Comment by goehle** [comment]
What was the issue, in case I run across it sometime?

**Comment by patrickspencer** [comment]
Actually I couldn't find the error but I removed the issue because I
thought it was a problem with our setup rather than the codebase. Do you
think I should open up the issue again?

**Comment by goehle** [comment]
I can be both.  Its not a bug in the "standard" webwork installation, but you may have some sort of configuration setup which is unusual, but should work, and doesn't.  I'll keep an eye out for  similar reports in any case.  You can keep the issue closed if you are sure its something local.

**Comment by patrickspencer** [comment]
I'm not actually sure it's something local. I only closed it because I
didn't want to clutter up the issues. I'll keep looking into the issue.
