### ISSUE TITLE
Problem Set List in Scoring Tools

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#558]
In 2.10 it appears that the problem set list no longer allows multiple sets to be selected (the HTML tag for the select doesn't contain the "multiple" attribute).  I can't seem to find any relevant changes to the code in Scoring.pm, so this makes me feel that I'm losing it.  Can anyone reproduce this?

**Comment by goehle** [comment]
There is an issue that was in #526 which may be related.  In newer versions of perl the command `CGI::popup_menu` now ignores the `multiple` attribute, which makes it so you can't select multiple things.  You now have to use `CGI::scrolling_list`.  However, I changed all the instances I could find, and I can certainly score multiple sets using the Scoring Tools page on 2.10.

**Comment by pstaabp** [comment]
So line 807 in Scoring.pm has CGI::popup_menu.  Are you saying that it should be CGI::scrolling_list?

**Comment by goehle** [comment]
Yes, although I thought I had changed all of those.  If that does fix it then it should be a hotfix.

**Comment by pstaabp** [comment]
Would you like me to do it and send you the PR?

**Comment by goehle** [comment]
I still cant reproduce the problem.  What version of CGI do you have?

**Comment by pstaabp** [comment]
Looks like it is 4.13, which it says is up to date.

**Comment by goehle** [comment]
I can confirm this bug if I upgrade to 4.13.  Pull request  #559 has a fix if you want to look at it.  

I also took another grep through the code to find other multiple selects that slipped through.  I didn't find any others, but I also missed this one!  So let me know if you run into it again.
