### ISSUE TITLE
MathView labels

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#565]
Some accessibility issues have been raised by staff here relating to the MathView equation editor. (In prior testing, the editor had usually been disabled.)

1. The button for the editor itself just reads 'link' and the student doesn't know what is the link for. We should give it an informative label.
2. Within the equation editor, when MathJax is outputting MathML, the template buttons (like "a+b", "a-b") just read as "link". This is not an issue when MathJax is outputting HTML-CSS. 

You can see all of this at https://www.youtube.com/watch?v=v3WaNlWy5DM&feature=youtu.be. The video starts using HTML-CSS MathJax output, and at 2:17 switches to MathML.

**Comment by goehle** [comment]
I added pull request #571 which should address these issues.  It adds screen reader only texts to the problem links.
