### ISSUE TITLE
Library browser fails to update

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#567]
When I upgraded my dev machine from WW 2.9 to 2.10, the Library Browser stopped updating when I choose a Subject.  It no longer auto-populates the Chapters as soon as a subject is selected.  I've attached a screenshot of the js error console.
![screen shot 2015-04-06 at 3 05 34 pm](https://cloud.githubusercontent.com/assets/1794586/7012489/cf608226-dc6e-11e4-9ec7-243e790612ad.png)

**Comment by jwj61** [comment]
Maybe any relevant entry from the apache error log would shed more light on it.

**Comment by goehle** [comment]
The JS is dying because WeBWorK or Apache or something is returning an error message that doesn't parse as json.  Either looking at the apache error log, or the actual responses sent back by the server.  (You can find the responses by looking in the network tab of most browsers developer tools.)

**Comment by dlglin** [comment]
Here's what I get in the apache error log:

[/webwork2/instructorXMLHandler] Can't locate object method "ssl_opts" via package "SOAP::Transport::HTTP::Client" at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 483, <DATA> line 522.\n * in SOAP::Transport::__ANON__ called at line 149 of /opt/webwork/webwork2/lib/WebworkClient.pm\n * in WebworkClient::xmlrpcCall called at line 320 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/instructorXMLHandler.pm\n * in WeBWorK::ContentGenerator::instructorXMLHandler::pre_header_initialize called at line 183 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm\n * in WeBWorK::ContentGenerator::go called at line 380 of /opt/webwork/webwork2/lib/WeBWorK.pm,

Running SOAP::Lite 0.710.10

**Comment by mgage** [comment]
Hi Danny,

I ran into something like this awhile ago.

Here is a stackoverflow reference to the problem:  http://stackoverflow.com/questions/14839098/perl-cannot-access-web-service-with-ssl <http://stackoverflow.com/questions/14839098/perl-cannot-access-web-service-with-ssl>


What I have added to my webwork.apache2.4-config file is the last line in this group:
-------------------
my $webwork_dir = "/opt/webwork/webwork2";
# Cache this value for use by other scripts not necessarily in the Apache2 hierarchy
# Different scripts use different locations :-)

$ENV{WEBWORK_ROOT} = $webwork_dir;
$WeBWorK::SeedCE{webwork_dir} = $webwork_dir;
$WeBWorK::Constants::WEBWORK_DIRECTORY = $webwork_dir;
$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;
————————————

See if that helps.  The stackoverflow reference may help explain what is happening.

Take care,

Mike

**Comment by goehle** [comment]
It seems like whatever version of SOAP you are using doesn't support `ssl_opts`.  That call was added in pull #474 to deal with self signed certificates.  I would recommend updating to a newer version of 
SOAP::Lite using cpan (`cpan install SOAP::Lite`) and seeing if that fixes the problem.

**Comment by goehle** [comment]
Did you end up figuring this out?

**Comment by dlglin** [comment]
I haven’t had a chance to work on it.

I’m going to do some research on SOAP::Lite, since I’m using the version provided by the CentOS package manager, and I’m loath to switch to CPAN.  I’ll let you know when I have more info.

Danny
On Apr 8, 2015, at 3:04 PM, Geoff Goehle <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you end up figuring this out?

**Comment by dlglin** [comment]
Switching to a newer version of SOAP::Lite didn't help, nor did Mike's suggestion.
Some googling led me to this post:
http://blogs.perl.org/users/brian_d_foy/2011/07/now-you-need-lwpprotocolhttps.html
Installing LWP::Protocol::https (and its dependencies) from CPAN fixed the issue.
It looks like the version of lib-perl packed in with CentOS 6.6 (and probably by extension the whole RedHat 6 family) doesn't include support for SSL, and thus requires the extra package.
Should this be documented somewhere?  Is it overkill to add LWP::Protocol::https to check_modules.pl?

**Comment by goehle** [comment]
It seems appropriate to add it to check modules.  Https is very commmon and it seems necessary for the xmlrpc pathway to work, which is important.

**Comment by goehle** [comment]
Hey Danny, 

Did you do anything else to fix this?  I ran into someone with the same problem but installing LWP::Protocol::https didn't seem to help.

**Comment by dlglin** [comment]
So it turns out that I had LWP::Protocol::https installed all along, but the version supplied by the package manage in CentOS 6 predates the ssl_opts directive.

Is this person getting the same error message in the logs?

Danny
On May 6, 2015, at 3:50 PM, Geoff Goehle <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Danny,

Did you do anything else to fix this? I ran into someone with the same problem but installing LWP::Protocol::https didn't seem to help.

**Comment by goehle** [comment]
Yeah, and they are running the same version of Cent OS.

**Comment by dlglin** [comment]
My fix was to install the package from CPAN rather than yum.


On May 6, 2015, at 5:26 PM, Geoff Goehle <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah, and they are running the same version of Cent OS.

**Comment by lijia577** [comment]
Hi, so I am the "someone" who was having trouble yesterday with this issue on CentOS. This morning, I reinstalled "LWP::Protocol::https" manually. cpan is not working either way. I download the tar.gz file for LWP::Protocol::https  module and build it manually. The error DOES go way. I am no longer getting "SOAP::Transport::HTTP::Client" at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 483...."  

However, I get another error message: "Can't call method "result" on an undefined value at /opt/webwork/webwork2/lib/WebworkClient.pm line 168." 

For now, I uncommented the line with librarybrowsernojs in localOverrides.conf and using the original library browser. I know this is not quite a fix... If you know how to handle the above error, please let me know. Thanks! @goehle

**Comment by mgage** [comment]
There is still some difficulty when the libraryBrowser javaScript calls back to the server.  If you enable View->Developer->developer tools  on chrome (or similar inspection tools on other browsers) you should see the error message that the javascript subroutine reports when it cannot connect.  That will give some clues.  

What version of webwork2 are you using at the server end?

**Comment by lijia577** [comment]
ww_version: 2.10 | pg_version: 2.10.  I did what you said.  On Library Browser. I click on the subject dropdown and randomly click one subject. The "Chapters" are not loaded. The error I get from the firefox console is "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by jwj61** [comment]
And there are no other error messages in the apache error log?

**Comment by goehle** [comment]
Not to necromance a dead thread, but I figured out the other half of this bug.  Installing the newer version of LWP::Protocol::https also introduced a bug with Soap::Lite that can be identified by the following line in the apache error file.
```
Illegal field name 'APR::Table=HASH(0x7f4a77999868)' at /usr/local/share/perl/5.18.2/SOAP/Transport/HTTP2.pm
```
This can be solved by upgrading Soap::Lite
```
cpan LWP::Protocol::https
cpan SOAP::Lite
```
You may need to force the install depending on your setup.
