### ISSUE TITLE
Error in develop in Library Browser

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#586]
I have a newer machine (running in OSX) that I have gotten WW running and was trying to use it to test the JITAR stuff.  I ran into the following error in the Library Browser when selecting a new subject.  The following is the response from the instructorXMLHandler from this:

Error messages

Can't call method "ssl_opts" on an undefined value at /Library/Perl/5.18/SOAP/Lite.pm line 482.
Call stack

The information below can help locate the source of the problem.

in SOAP::Transport::__ANON__ called at line 152 of /Library/Webserver/Documents/webwork/webwork2/lib/WebworkClient.pm
in WebworkClient::xmlrpcCall called at line 319 of /Library/Webserver/Documents/webwork/webwork2/lib/WeBWorK/ContentGenerator/instructorXMLHandler.pm
in WeBWorK::ContentGenerator::instructorXMLHandler::pre_header_initialize called at line 184 of /Library/Webserver/Documents/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::go called at line 380 of /Library/Webserver/Documents/webwork/webwork2/lib/WeBWorK.pm

I'm thinking this is more of a configuration error on my side instead of a bug, but can't track it down.

**Comment by dlglin** [comment]
Check out https://github.com/openwebwork/webwork2/issues/567
My issue was solved there, but another one is still pending.

**Comment by pstaabp** [comment]
No luck fixing this.  I have another machine running on develop, and no problems with it.  I'm running perl 5.18 on the machine with errors (and all modules up to date) and 5.12 on the machine (and having trouble updating modules), so it might be a module issue or a perl version issue. 

Also, both of these are running as localhost with no ssl layer on them.

**Comment by pstaabp** [comment]
Here's another item.  at line 150 of WebworkClient.pm, there's a print if error occurs.  I'm getting the following:
```
WebworkClient: Initiating xmlrpc request to url localhost/mod_xmlrpc/mod_xmlrpc 
 Error: proxy: transport protocol not specified
```
So there is an error when running the block of code on 144-149.  

Is there supposed to be 2 mod_xmlrpc in the URL?

**Comment by pstaabp** [comment]
One more comment.  Shouldn't have clicked yet.  All of the example from https://metacpan.org/pod/SOAP::Transport for proxy has the protocol "http://" in the URL.  I hardcoded this in and it worked for me.  So I tracked down and when setting the server URL, I just put in localhost, not "http://localhost".  This fixed the problem. 

So my theory of setting up the configuration correctly was correct.
