### ISSUE TITLE
WW3 and WW2 cookies

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#599]
I've been meaning to post about this for a while.  Ever since you changed the path on the ww2 cookie (something which needed to be done to make it ww3 compatible) in 75d35321bed5c7ecaf whenever I switch between develop and ww3 I can't log in unless I remove any old cookies I had laying around.  

To test
1.  Switch to ww3 and log in.  
2.  Switch to develop and restart your server
3.  Open a different browser and log in to the same course with the same user.  (This will log you out in the server while leaving your cookie in the original browser intact.)  
4.  Go to the original browser.  When you click a webwork link it should redirect you to the log in page and your login should fail without any warnings.  

The issue is that the WW3 cookie is still hanging around and has path '/' and is being checked for authentication.  The authentication should kill the cookie if its no good, but it kills the cookie with ww2 path 'webwork2/' and that doesn't kill the ww3 cookie (which hangs around).  It would be good to fix this before ww3 goes in develop because it can cause really confusing issues for people using ww3 for the first time. 

Its a subtle issue.  One possible solution is to change the name of the cookie from `WeBWorKCourseAuthen.$courseID` to `WeBWorK.CourseAuthen.$courseID` in ww3.  This will cause there to actually be different cookies for ww3 and develop and the collision won't happen.  It needs to be changed everywhere in ww3 as well as ww2 (in the ww3 branch).

**Comment by pstaabp** [comment]
It's been on my mind as well and it will need to be dealt with.  I'll try the cookie rename.  That's a good idea.
