### ISSUE TITLE
Conditional Release seems broken in develop

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#637]
We are using develop (I'm afraid I won't have time to explore this in 2.11 for a while). 

It appear to us that Conditional Release is broken. If we set up a problem set A to depend on completion of set B, then all appears well until you actually complete set B, and try to work on set A. You can get to the list of problems for set A, but then when you click on Problem 1, you get an error message like this one:

You do not have permission to view unopened sets at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm line 529.

Turning off conditional release appears to give access to set A, so it seems certain that CR is the culprit.

**Comment by goehle** [comment]
This seems like a regression caused by JITAR. I can't test right now, but try removing the `$set->set_id` from https://github.com/openwebwork/webwork2/blob/develop/lib/WeBWorK/ContentGenerator/Problem.pm#L518
