### ISSUE TITLE
Is this a security issue?

### ISSUE THREAD

**Issue by devoxel** [openwebwork/webwork2#650]
I was just browsing the codebase when I found this in one of the scripts:

    $db->addPassword($db->newPassword(user_id=>"admin", password=>crypt("admin", "dc")));

Now I have very little perl experience but doesn't this function just create a digest from the string admin and salt dc? 

If so, that removes all point of salting in the first place, and is actually even worse than salting since I would know the plaintext too.

I assume I'm missing something here, but I said I'd make an issue out of it anyway.

**Comment by goehle** [comment]
This is a recovery script and adds an administrator user with username admin and password admin to a course, so its not particularly safe.  However, anyone with the ability to run this script has command line access to the machine and can already do pretty much whatever they want to WeBWorK.  Its not a security issue unless someone fines a way to run this from the web interface.  Thanks for your input, though.  Its good to have additional eyes looking out for this kind of stuff.  

P.S.  Its not entirely clear to me why the password is even salted at all considering its printed right there in plain text.
