### ISSUE TITLE
Change "Due Date" to "Close Date"

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#685]
One problem I have been thinking about is that there has been a lot of confusion about how reduced credit works because people expect the "partial credit due date" to be after the "due date".    They don't like that the current reduced credit date comes before the "due date" of the set. However, for WeBWorK we have always used due date to mean "close date".  This makes it tough to implement a reduced credit system where the set stays open after the due date.   One alternative is to try to make the current implementation easier to understand.  I was thinking about going through and changing the term "Due Date" to "Close Date" in all ContentGenerator pages.  The up sides are that this is a better description of what the date does and that its fairly safe.  (If I miss something it just means the wrong text is displayed on screen.)  The down side is its wide reaching change (influencing documentation, not just code) and that it may not solve the underlying problem.  Any thoughts?

**Comment by pstaabp** [comment]
Geoff,

Yes.  I get tons of confusing from both students and faculty.  I think this terminology sounds good.
