### ISSUE TITLE
Can't locate object method "mk_ro_accessors"

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#693]
Just installed the develop branch, and every time I submit an answer I get:
Can't locate object method "mk_ro_accessors" via package "WeBWorK::Utils::AttemptsTable" at /opt/webwork/webwork2/lib/WeBWorK/Utils/AttemptsTable.pm line 187.

A quick googling says that this is provided by Class::Accessor.  Should I be installing that package?  If so, it should be added to check_modules.pl.

**Comment by goehle** [comment]
Yes, you should install that package.  We did add `Clas::Accessor` to `check_modules.pl`, but only for the develop branch (https://github.com/openwebwork/webwork2/blob/develop/bin/check_modules.pl#L45).  Let me know if it doesn't work for some reason. 

Geoff.

**Comment by dlglin** [comment]
I didn't read the output of check_modules.pl very carefully.  I do have it installed, so that's not the problem.  Here's the whole stack trace:
Error messages

Can't locate object method "mk_ro_accessors" via package "WeBWorK::Utils::AttemptsTable" at /opt/webwork/webwork2/lib/WeBWorK/Utils/AttemptsTable.pm line 187.
Call stack

The information below can help locate the source of the problem.

in WeBWorK::Utils::AttemptsTable::new called at line 315 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::attemptResults called at line 1834 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::output_summary called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm
in WeBWorK::Template::template called at line 560 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::content called at line 356 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::content called at line 232 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::go called at line 382 of /opt/webwork/webwork2/lib/WeBWorK.pm

**Comment by goehle** [comment]
Hmm.  Attempts table works for me on a couple of machines, so it must be something subtle.  The exampel code I found for Class::Accessor has `use base qw(Class::Accessor);`.  Could you try adding that right after `package WeBWorK::Utils::AttemptsTable;` in `lib/WeBWorK/Utils/AttemptsTable.pm`.  If that doesn't work we may need to get Mike to chip in since this is his module.  

Geoff.

**Comment by dlglin** [comment]
That fixed it for me.

Thanks.
