### ISSUE TITLE
OPL-update failed

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#706]
I've been getting 
```
Library version is 2.5; using OPLtables!
DBD::mysql::db do failed: Specified key was too long; max key length is 1000 bytes at ./OPL-update line 268.
```
when running OPL-update.  I updated mysql recently and it appears UTF8 is default for this.   I have tracked it down to when the author table is being created because the key is the firstname and lastname which are each  VARCHAR(255) columns are being made and for UTF8, each character is 3 bytes in UTF8.  

I changed the firstname and lastname columns to be VARCHAR(100) and am running fine.   I would like 100 characters is sufficient for each name.  I'd be happy to submit a pull request for this...  Alternatively, I can work around with my database settings, but I think more and more databases are using UTF8 for this.

**Comment by mgage** [comment]
Is your repos up to date?  I thought this was handled in release 2.12

https://github.com/openwebwork/webwork2/pull/698 <https://github.com/openwebwork/webwork2/pull/698>

Take care,

Mike

**Comment by pstaabp** [comment]
It never made it into 2.12.  That PR was closed and and the point I'm having trouble with is in both master and develop:

https://github.com/openwebwork/webwork2/blob/master/bin/OPL-update#L156
https://github.com/openwebwork/webwork2/blob/develop/bin/OPL-update#L156

**Comment by mgage** [comment]
Let’s see what Geoff has to say.  It might just have been overlooked.

**Comment by goehle** [comment]
I fixed it in a different PR:
https://github.com/openwebwork/webwork2/pull/699

In particular master and develop both have the changes you suggested
already in place.

https://github.com/openwebwork/webwork2/blob/master/bin/OPL-update#L159

Geoff.

**Comment by goehle** [comment]
Those changes might not have made it into the ww3 branch though.  So if
your ww3 is behind develop you will need to pull develop into it.

P.S.  I'm currently on vacation.  I'll answer what questions I but won't
get much done otherwise.

Geoff.

**Comment by pstaabp** [comment]
I’m just running develop right now.  This isn’t urgent, so take a look after vacation.

**Comment by goehle** [comment]
Merged latest develop (including this opl fix) into ww3.
