### ISSUE TITLE
update-OPL-statistics doesn't escape special characters in passwords

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#715]
When I run update-OPL-statistics (either on its own or through OPL-update), everything works until the last statement, where I get
ERROR 1045 (28000): Access denied for user 'webworkWrite'@'localhost' (using password: YES)
This comes from [https://github.com/openwebwork/webwork2/blob/master/bin/update-OPL-statistics#L202](url), and I believe the problem is that my DB password contains an ampersand, which is treated differently at the command line.  Is it possible to either escape the special characters in the password used in this command, or quote the password verbatim?

**Comment by goehle** [comment]
In `upload-OPL-statistics` I use shell quote to quote the database password.  I must have just forgot to add that to `update-OPL-statistics`.  In any case I think it would solve the problem. 

https://github.com/openwebwork/webwork2/blob/master/bin/upload-OPL-statistics#L46
