### ISSUE TITLE
Problems with database dsn for update-OPL-statistics

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#722]
Two issues when trying to load the global statistics file:
1. I had old syntax with my database dsn, namely:
`$database_dsn ="dbi:mysql:database=webwork;host=mydb.myschool.edu";`

This one may not be worth doing anything about since it looks like the standard now is to use dpi:mysql:[dbname]:[dbhost].

The one that may come up is if someone were using a nonstandard port (or has the default port hard-coded), as the syntax is hostname:port, which would get intercepted by the "split" statement.  I think the fix would be to add another variable for port to the split statement, and then re-craft the mysql command if that value is present.

**Comment by goehle** [comment]
Fixed in #723.  Since site.conf specifies the dbi:mysql:dbname:host:port format I'm just going to support that.  

https://github.com/openwebwork/webwork2/blob/master/conf/site.conf.dist#L169
