### ISSUE TITLE
LTI Grade passback - Desire2Learn issue with newline

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#725]
Desire2Learn won't accept the grade passback because the XML block has a newline at the end.  Adding
`chomp($replaceResultXML);`
to line 212 of SubmitGrade.pm fixes the issue in D2L.  I've tested the altered code in Moodle, and it doesn't break anything.  I don't have access to any of the other LMSs to test.

**Comment by goehle** [comment]
Thanks for tracking down this fix.  I"ll test it out in Blackboard and
Canvas and make a pull.

Geoff.

**Comment by goehle** [comment]
Submitted fix.

**Comment by goehle** [comment]
P.S.  If you could find time to add instructions for Direct2Learn to the wiki that would be amazing. 

http://webwork.maa.org/wiki/LTI-Advanced_Authentication

http://webwork.maa.org/wiki/LTI-Advanced_Grading
