### ISSUE TITLE
Recommend using secure https more strongly.

### ISSUE THREAD

**Issue by paultpearson** [openwebwork/webwork2#728]
I propose changing line 49 of site.conf.dist to suggest the use of secure https, and add comments that recommend not using unsecure http.

In other words, change

$server_root_url   = '';   # e.g.  'http://webwork.yourschool.edu' or 'http://localhost'

to

$server_root_url   = '';   # e.g.  'https://webwork.yourschool.edu' or 'https://localhost'

**Comment by goehle** [comment]
I made this change, although I left the second example as "http://localhost" since if you are accessing your server as localhost then you probably dont have ssl.
