### ISSUE TITLE
give students choice of hardcopy template?

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#741]
Faculty can choose to print hardcopy using one or two column format (and perhaps more formats will become available). At the moment students do not seem to have a choice and the default value seems to be the two column format. 

Can students easily be given a choice of the format to use for printing hardcopy?  Is there a downside to that?

**Comment by goehle** [comment]
You were the one who wanted it this way, if I remember right.  It should
just be an issue of changing permissions on when the switch is shown.

**Comment by goehle** [comment]
I just looked it up and the theme is controlled by the permisison `download_hardcopy_change_theme`.  That can be changed in course.conf in the usual way.  If warranted we could add it to the permissions tab on Course Configuration.

**Comment by mgage** [comment]
I probably did want it that way.  Now I'm not so sure.  I'll change it in the config files for my class and if that seems useful I'll make a suggestion.  It might be that we just want to set this permission to student by default and hope that it seldom needs to be modified.
