### ISSUE TITLE
develop with code mirror has bug when codemirror is not enabled. 

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#742]
In develop, with the codemirror patch installed, set the value 

`$options{PGCodeMirror} = 0;`
in `localOverrides.conf`

The tabs for the PGProblemEditor will loose formatting -- both the ones above the textarea and the tabs for choosing the action in saving the edit.  The tabs at the bottom also loose the ability to respond to clicks.  

Restore 
`$options{PGCodeMirror} = 1;`

and everything works fine.

-- also reported as bug #3726

**Comment by goehle** [comment]
Could you check and see if a hard refresh fixes the issue?  I can't
reproduce the bug and I've seen similar issues when math4.js is out of
date.

Geoff.

**Comment by goehle** [comment]
I figured out the issue and fixed it in a pr.

**Comment by mgage** [comment]
Thanks.  I did do a hard refresh, but thanks for the suggestion. Sometimes I overlook that possibility.  I'll go look at the pull request now.
