### ISSUE TITLE
Renaming a course does not change the values in course_id in the past_answers table

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork2#762]
Renaming a course in the course administration does not update the value(s) in the course_id column of the past_answers table for the course.

**Comment by mgage** [comment]
This is good to know.  Does it use the new name for future "past answers" created after the name change?  The next question, since the past answers are to some extent a historical record, should the earlier past answers be updated or just the newer entries?  I don't know the answer to that question.  Do you have particular use cases in mind?

**Comment by heiderich** [comment]
It uses new name for future "past answers".

I do not know why the course ID is actually recorded in that table. I would guess that all the past answers belong to the same course (that might change its name). Therefore it seems to be redundant and is merely a historical record, as you say. I noticed this while using the script dump_past_answers. It seems only to exports those past answers that coincide with the (I believe current) course ID. So if a course was renamed, then those answers that were submitted before the rename are not exported. I would expect all answers to be exported. So in my opinion either this script should ignore the course IDs in this table or they should be updated when renaming the course.

**Comment by drgrice1** [comment]
This is not a valid issue.  Although the course ID is saved incorrectly to the past answers table, it is not used anywhere for anything, and is never even looked at again after it is saved.  So you can set that column to anything you want and it won't affect anything.  The column should be removed from the table (and probably will be soon).
