### ISSUE TITLE
Support for quotation marks in Taxonomy2

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork2#765]
It would be nice if quotation marks would be allowed in the Taxonomy2 file. Currently they cause SQL errors when OPL-update is executed. Is there any reason against supporting them?

**Comment by jwj61** [comment]
There are single quotes in Taxonomy2, and they seem to work ok.  Is the current Taxonomy2 file causing problems on your system?

**Comment by heiderich** [comment]
The single quotation marks do not cause problems. The double quotation marks caused SQL errors when running OPL-update:

    DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'bar","14")' at line 1 at /opt/webwork/webwork2/bin/OPL-update line 318, <IN> line 869.

when the entry in the Taxonomy file is of the form

    foo"bar

I guess that it is a matter of proper escaping.

**Comment by jwj61** [comment]
Should be fixed, once 834 is merged.  Sorry it took so long, I thought it was going to be connected with other problems with quotes.
