### ISSUE TITLE
Error updating grades via LTI

### ISSUE THREAD

**Issue by aruethe2** [openwebwork/webwork2#811]
I had a problem with grades not updating in our Moodle LMS via the LTI interface.  I saw the following error in ssl_error_log:

`An error occurred while trying to update grades via LTI: Can't call method "getSettingValue" on an undefined value at /opt/webwork/webwork2/lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm line 295.\n\n`

I noticed that in the `mass_update` function of SubmitGrade.pm, the first line is `my $self = shift;`, but in the calling function from /lib/WeBWorK/ContentGenerator.pm, there aren't any arguments passed to `mass_update`.  

I found that I was able to eliminate the error and update the grade via LTI by updating line 180 in /lib/WeBWorK/ContentGenerator.pm.

From:
`-           my $result_message = eval { $grader->mass_update() };`

To:
`+           my $result_message = eval { $grader->mass_update($self) };`

Was this the right thing to do?  We're using WeBWorK 2.12.

**Comment by dsteinmo** [comment]
This sounds like a pretty serious bug, perhaps it is even hotfix-worthy for 2.13? I'm not a developer on this project, so I'm not sure. Maybe create a pull-request direct into the 2.13 release branch and see what the developers think.

**Comment by mgage** [comment]
This may be at least partially resolved by PR #856 and #857

**Comment by drgrice1** [comment]
This issue is obsolete.
