### ISSUE TITLE
Phrasing for reduced credit

### ISSUE THREAD

**Issue by jwj61** [openwebwork/webwork2#824]
A request from one of our instructors (seconded by another).  I might do it, but want feedback first as to whether this is acceptable or not.  The biggest problem I foresee is that it changes phrases which already have translations to other languages.

---------------

I would very much like to use the Webwork reduced scoring feature again. I think it's good pedagogy, and it is very effective in eliminating student requests for time extensions (which come even when you say you don't give time extensions), but I stopped using it a few years ago, solely due to the way webwork presents the two different dates. 

The presentation has changed a bit in the meantime, but Webwork still calls the final date by which one can earn (reduced) credit the "due date". 

This creates a huge a problem of perception. The term "due date" comes with such a firm meaning attached to it, its usage by Webwork creates the irrational but undispellable impression in students' minds that they have "less time" to complete assignments, when they actually have more time. 

When I previously used this feature, I would explain clearly, in the syllabus, in announcements, etc, that the earlier date is the "real" due date, even list it as the "due date" in the syllabus, but to no avail. There were consistent complaints and challenges that I gave them "less time" to finish homework. Some students who missed an assignment would latch on to the phrase "due date" and angrily demand to get full credit for finishing by the "due date". A few even retaliated in final evaluations and left comments like "teacher penalized me for submitting homework by the due date".

Here is how I think this should be fixed: 

For example, if an assignment is officially due, for full credit, this Sunday, and if I want to give students another two days after that for reduced credit, I currently set the "reduced scoring date" to 12/10, and the "due date" to 12/12. This is fine, because students don't see the instructor tools.

What students see when the reduced scoring date has not yet passed is this:

open, reduced scoring starts on 12/10/2017 at 11:59pm MST

That should become:

open, due 12/10/2017 at 11:59pm MST, afterwards reduced credit can be earned until 12/12/2017 at 11:59pm MST.

This is what students see once the reduced scoring date has passed:

open, due 12/12/2017 at 11:59pm MST
reduced scoring started on 12/10/2017 at 11:59pm

It should be changed to:

due date 12/10/2017 at 11:59pm has passed
reduced credit can still be earned until 12/12/2017 at 11:59pm MST

**Comment by mgage** [comment]
I think changing the phrasing for students is a good fix for this for now.  When this issue first came up during the design state there were some compromises because we were nervous about changing names and behavior in the code and particularly in the database. Changing the wording of messages is not such a big deal.  I have changed spelling in messages and then changed the translation files with a global search and replace without any difficulty.  The proposed change seems a good way to address student confusion.  Potential instructor confusion remains, but addressing that might require more extensive changes and a lot of testing.

**Comment by Alex-Jordan** [comment]
This was addressed in #838.
