### ISSUE TITLE
Library Browser can't find questions if the DBsubject, DBchapter or DBsection contains an apostrophe

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#832]
Currently if you choose a DBsection which contains an apostrophe (e.g. Calculus - single variable -> Applications of differentiation -> Indeterminate forms and L'Hopital's rule), it indicates that there are 0 problems found, and fails to display them.

It looks like this is being caused by https://github.com/openwebwork/webwork2/blob/d85da39f5312c5364c893669d2d998b8f7da1d8e/lib/WeBWorK/Utils/ListingDB.pm#L465, https://github.com/openwebwork/webwork2/blob/d85da39f5312c5364c893669d2d998b8f7da1d8e/lib/WeBWorK/Utils/ListingDB.pm#L471 and https://github.com/openwebwork/webwork2/blob/d85da39f5312c5364c893669d2d998b8f7da1d8e/lib/WeBWorK/Utils/ListingDB.pm#L477.

Now that these are being passed as parameters, it doesn't look like apostrophes need to be escaped.  Before I submit a PR to fix this, I wanted to ask if there are security issues in not escaping apostrophes, or is this handled by the DBI package in perl?

**Comment by jwj61** [comment]
Escaping them is purely an artifact of building perl strings.  If removing the escaping works, then it seems clear that the quotes are being passed through properly (since there are quotation marks in the strings in the database).  So, I think you should go ahead and make the pull request.

**Comment by dlglin** [comment]
This was fixed in #833, which should be pulled into rel-2.14.

**Comment by mgage** [comment]
#833 was merged into develop in January 2018 so this feature/bug fix should already be part of rel-2.14 which was created from develop.

**Comment by dlglin** [comment]
Sorry I was looking at the wrong branch.  The fix is there.
