### ISSUE TITLE
Illegal character error when using docker compose up

### ISSUE THREAD

**Issue by jverrett** [openwebwork/webwork2#836]
When I initially tried setting up webwork2 on the localhost using the docker compose up command I get the following error:

"curl: (3) Illegal characters found in URL
ERROR: Service 'app' failed to build: The command '/bin/sh -c WEBWORK_VERSION=`cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p'`     && curl -fSL https://github.com/openwebwork/pg/archive/${WEBWORK_VERSION}.tar.gz -o /tmp/${WEBWORK_VERSION}.tar.gz     && tar xzf /tmp/${WEBWORK_VERSION}.tar.gz     && mv pg-${WEBWORK_VERSION} $APP_ROOT/pg     && rm /tmp/${WEBWORK_VERSION}.tar.gz     && curl -fSL https://github.com/openwebwork/webwork-open-problem-library/archive/master.tar.gz -o /tmp/opl.tar.gz     && tar xzf /tmp/opl.tar.gz     && mv webwork-open-problem-library-master $APP_ROOT/libraries/webwork-open-problem-library     && rm /tmp/opl.tar.gz     && curl -fSL https://github.com/mathjax/MathJax/archive/master.tar.gz -o /tmp/mathjax.tar.gz     && tar xzf /tmp/mathjax.tar.gz     && mv MathJax-master $APP_ROOT/MathJax     && rm /tmp/mathjax.tar.gz     && rm /tmp/VERSION' returned a non-zero code: 3"

I am on windows and using command prompt, so I am wondering if there is an issue there as opposed to using a linux machine?

**Comment by xcompass** [comment]
I think it is most likely related to windows command prompt. If you need to it right away, I suggest you can try it on a linux. I'll need some time to figure it out as I don't have a windows to test right now.

**Comment by Alex-Jordan** [comment]
Deciphering the error message, it is objecting to `https://github.com/openwebwork/pg/archive/${WEBWORK_VERSION}.tar.gz` being used as the argument to `curl`. The `${WEBWORK_VERSION}` variable should have been evaluated to something by the time `curl` is called instead of begin left literally as `${WEBWORK_VERSION}`. 

Unsure, but [this thread](https://github.com/moby/moby/issues/5509) may be relevant.
