### ISSUE TITLE
Not receiving WeBWorK emails set from Yahoo

### ISSUE THREAD

**Issue by betsyrosalen** [openwebwork/webwork2#843]
I work at Bronx Community college and we are using WeBWorK-2.13.  We discovered that emails sent from WeBWork that are coming from a student (or really anyone) with a yahoo email address are not getting delivered.  We tried other email addresses from bcc.cuny.edu and from gmail and those worked fine and get delivered almost immediately, but any email coming from yahoo just never shows up.  No error messages and in fact WeBWorK confirms that the email was sent, but the professor never gets the email.  We tried two different yahoo email addresses and we checked the spam folder too, and nothing.  We tested this using the "Email Instructor" button on the bottom of the problem pages.

Let me know if you need any additional info about our server and setup.  I would have to get that info from our IT dept.

**Comment by heiderich** [comment]
I guess this is not a problem with WeBWorK itself, but rather a problem with the setup of the mail server involved.

As far as I know WeBWorK delivers a mail with the e-mail address of the student and sends it through the server that is configured in WeBWorK. The mail server of the recipient (professor, TA, ...) may take measures to prevent receiving SPAM. One common technique is [SPF](http://www.openspf.org/). With SPF the administrator of the domain of the email address of the sender advertises in their DNS records which mail servers will send mail for this domain. In case of yahoo.com and gmail.com these entries looks as follows:

```
$ host -t TXT yahoo.com
yahoo.com descriptive text "v=spf1 redirect=_spf.mail.yahoo.com"
$ host -t TXT _spf.mail.yahoo.com
_spf.mail.yahoo.com descriptive text "v=spf1 ptr:yahoo.com ptr:yahoo.net ?all"
$ host -t TXT gmail.com
gmail.com descriptive text "v=spf1 redirect=_spf.google.com"
$ host -t TXT _spf.google.com
_spf.google.com descriptive text "v=spf1 include:_netblocks.google.com include:_netblocks2.google.com include:_netblocks3.google.com ~all"
```

The domain bcc.cuny.edu seems not to advertise SPF records:

```
$ host -t TXT bcc.cuny.edu
bcc.cuny.edu has no TXT record
```

More details about SPF record entries can be found on [http://www.openspf.org/SPF_Record_Syntax](http://www.openspf.org/SPF_Record_Syntax).

It is only speculation, but you may want to check whether the mail server of the recipient (the professor) is blocking the mail sent by WeBWorK in the name of the student. You may contact the administrator of that server and ask whether this is the case. If both the WeBWorK server and the mail server of the recipient belong to the same organization, the administrator of the mail server might whitelist the mail server that is used my WeBWorK to deliver the mail.

**Comment by betsyrosalen** [comment]
Hi Florian,

Thanks for the response.  It’s gonna take a me a while to understand all this, but I will figure it out and let you know if that solves the problem.

Thanks!
Betsy

**Comment by Alex-Jordan** [comment]
Closing this. It sounds to me as well that this was an issue with some mail server, not with WeBWorK. Can reopen if needed.
