### ISSUE TITLE
Non interactive installer

### ISSUE THREAD

**Issue by mxjeff** [openwebwork/webwork2#847]
Is there a way to handle a non interactive installation?
I'm trying to perform an automatic installation with an orchestration application.
ww_install is an interactive script, It is not convenient to use with tools such as ansible for instance.

Is this planned? Already possible?
Cheers

**Comment by mgage** [comment]
Hi,

I don’t believe anyone has set up ansible to configure WeBWorK.

There is a docker configuration file contributed by @xcompass at UBC
See the develop branch of webwork2 at github.com/openwebwork/ <http://github.com/openwebwork/>.

Also instructions at https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions <https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions>.

That would probably help you construct an ansible file.  There is also the manual
installation description at http://webwork.maa.org/wiki/Installation_Manual_for_2.13_on_Ubuntu_16.04#.WtXhL8gh1y

Hope that helps.  If you get it working and consider it useful please consider 
contributing back the ansible setup file.

Take care,

MIke

**Comment by mxjeff** [comment]
Alright.

I'll have a look at the docker solution then.

Thanks
