### ISSUE TITLE
Migrating webwork

### ISSUE THREAD

**Issue by pguerr061703** [openwebwork/webwork2#862]
Hello, I have webwork version 2.12 installed on our Ubuntu 16.04 virtual server, but looking to migrate it another Ubuntu host. 
How do i perform this migration? Our professor has some content on this host in the webwork database for math placement, and I am unsure how to get it over to a newly installed Ubuntu server. 
Would a mysqldump and import to other host work? What directories will I need to copy over that may have content ?
Source
Version - /opt/webwork/webwork2/VERSION
	$WW_VERSION = '2.12';
	$WW_COPYRIGHT_YEARS = '1996-2016';

Thank you for any  assistance.

**Comment by mgage** [comment]
Hi,

These are good questions to ask on the forum which is linked to from the webwork.maa.org/wiki <http://webwork.maa.org/wiki> (link is in the left margin).

You need to sign up on the wiki before you can post to the forum.

Probably the safest way to  migrate  is to archive each course you want saved.  (You can archive 
courses from the “admin” course on your current server or from the FileManager page in any course.)
Then copy the resulting  .tar.gz file to the courses/ directory on your new server. (You’ll need to do this 
with command line unix tools.)  Then  “unarchive” that file from the admin course.   (You may also have to “upgrade” courses if the new ww version changes.)

You could also use a mysqldump but it’s  more error prone.

Hope this helps.

Take care,

Mike

**Comment by mgage** [comment]
Hopefully all went well.  Closing this issue.
