### ISSUE TITLE
Hash key `webworkURL` in `lib/WebworkClient.pm` should probably be `server_root_url`

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#863]
I think there is an issue in `lib/WebworkClient.pm` and possibly in `t/grab_course_environment.pl`.

When using `clients/sendXMLRPC.pl` I received a Perl warning from line 165:
```
Use of uninitialized value $WebworkClient::site_url in concatenation (.) or string at /data2/webwork_docker_test_xmlrpc/webwork2/lib/WebworkClient.pm line 165.
```

The issue seems to be that the line (line 165 of `lib/WebworkClient.pm`):
```
our $site_url = $seed_ce->{server_root_url};
```
is referring to the key `server_root_url` which does not seem to be a key defined in the local `WeBWorK::CourseEnvironment` called `seed_ce` (which defined in  `lib/WebworkClient.pm` several lines earlier) while instead there is a key called `webworkURL`.

Note:  `lib/WebworkClient.pm` refers to a key of the same name (`server_root_url`) also in one other place (in sub `environment`) where it is set to a dummy value.

There seem to be several other files which expect a `WeBWorK::CourseEnvironment` hash to have a value for `server_root_url`:
 * `bin/addcourse`
 * `conf/webwork.apache2-config.dist`
 * `conf/webwork.apache2.4-config.dist`
 * `lib/WeBWorK/ContentGenerator/instructorXMLHandler.pm`
 * `lib/WeBWorK/ContentGenerator/renderViaXMLRPC.pm`
 * `lib/WeBWorK/AchievementEvaluator.pm`
 * `lib/WeBWorK/PG.pm`
 * `lib/WeBWorK/Authen/LTIBasic.pm`
 * `lib/WeBWorK/Authen/LTIAdvanced.pm`
 * `lib/WeBWorK/Utils/AttemptsTable.pm`

I am guessing that the key name `webworkURL` in `seed_ce` should be changed to `server_root_url`.

Note: There seems to be only one other current file with a key called  `webworkURL`: `t/grab_course_environment.pl` so maybe this key name is a leftover from an older version of the code, in which case the same change may apply there also.

**Comment by mgage** [comment]
resolved in   PR #860

**Comment by taniwallach** [comment]
This issue was a result of the special changes to `site.conf` for Docker installs. In such settings, it is necessary to set the environment variable `WEBWORK_ROOT_URL` which is read by `site.conf` and is used to set `$server_root_url`.

The environment variable is set automatically inside the Docker containers, but needs to be manually set when running `clients/sendXMLRPC.pl` from outside the Docker container. Ex:
```
export WEBWORK_ROOT_URL=https://demo.webwork.rochester.edu
```

This seems to be the real solution to this problem.

**Comment by taniwallach** [comment]
@mgage I still got the error message
```
Use of uninitialized value $WebworkClient::site_url in concatenation (.) or string at .../webwork2/lib/WebworkClient.pm line 165.
```
today when testing PR https://github.com/openwebwork/webwork2/pull/884 today.

I'm not convinced that the issue was resolved yet at least not on my setup.

**Comment by taniwallach** [comment]
I take that back. Running
```
export WEBWORK_ROOT_URL=http://localhost:8080
```
overcomes the error.
