### ISSUE TITLE
Issue with floating point values and conditional release

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#868]
Because the scores for conditional release are calculated as floating point values, there are cases when a student has achieved the exact score needed to access a subsequent less, but because the floating point value of their score is rounded differently than the required score, they do not receive access.

To reproduce:

- Create homework set 1 with 5 questions.
- Create homework set 2 which requires 40% or greater on homework set 1 to access
- Answer two questions correctly on homework set 1.  You should now have access to homework set 2, but in many cases you do not.

The offending check is https://github.com/openwebwork/webwork2/blob/84cf8e6c3b737885083d62f0d0342e1d8bf7084a/lib/WeBWorK/Utils.pm#L1146
A couple of suggested fixes are rounding $r_score and $restriction to some number of decimal places, or adding some small value to $r_score to make sure that it is greater than $restriction when they are supposed to be equal.

**Comment by Alex-Jordan** [comment]
This was fixed with #1535.
