### ISSUE TITLE
Error installing using Docker

### ISSUE THREAD

**Issue by apizer** [openwebwork/webwork2#873]
The error occurred following the 
https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions on a Windows 10 setup.  I doubt the error has anything to do with Windows 10.  I was using branch rel-ww2.14.   

The error is "curl: (3) Illegal characters found in URL"

Below is what I did and the error msg.  Has anyone else tried this?

PS D:\webwork_docker\webwork2> git checkout -b rel-2.14 origin/rel-ww2.14
Switched to a new branch 'rel-2.14'
Branch 'rel-2.14' set up to track remote branch 'rel-ww2.14' from 'origin'.
PS D:\webwork_docker\webwork2> git branch
  master
* rel-2.1

PS D:\webwork_docker\webwork2> docker-compose up
Creating network "webwork2_default" with the default driver
Pulling db (mariadb:10.1)...

[Many steps then this error]

Step 25/36 : COPY VERSION /tmp
 ---> e77546e1a672
Step 26/36 : RUN WEBWORK_VERSION=`cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p'`     && curl -fSL https://github.com/openwebwork/pg/archive/${WEBWORK_VERSION}.tar.gz -o /tmp/${WEBWORK_VERSION}.tar.gz     && tar xzf /tmp/${WEBWORK_VERSION}.tar.gz     && mv pg-${WEBWORK_VERSION} $APP_ROOT/pg     && rm /tmp/${WEBWORK_VERSION}.tar.gz     && curl -fSL https://github.com/openwebwork/webwork-open-problem-library/archive/master.tar.gz -o /tmp/opl.tar.gz     && tar xzf /tmp/opl.tar.gz     && mv webwork-open-problem-library-master $APP_ROOT/libraries/webwork-open-problem-library     && rm /tmp/opl.tar.gz     && curl -fSL https://github.com/mathjax/MathJax/archive/master.tar.gz -o /tmp/mathjax.tar.gz     && tar xzf /tmp/mathjax.tar.gz     && mv MathJax-master $APP_ROOT/MathJax     && rm /tmp/mathjax.tar.gz     && rm /tmp/VERSION
 ---> Running in 248de70aae80
curl: (3) Illegal characters found in URL
ERROR: Service 'app' failed to build: The command '/bin/sh -c WEBWORK_VERSION=`cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p'`     && curl -fSL https://github.com/openwebwork/pg/archive/${WEBWORK_VERSION}.tar.gz -o /tmp/${WEBWORK_VERSION}.tar.gz     && tar xzf /tmp/${WEBWORK_VERSION}.tar.gz     && mv pg-${WEBWORK_VERSION} $APP_ROOT/pg     && rm /tmp/${WEBWORK_VERSION}.tar.gz     && curl -fSL https://github.com/openwebwork/webwork-open-problem-library/archive/master.tar.gz -o /tmp/opl.tar.gz     && tar xzf /tmp/opl.tar.gz     && mv webwork-open-problem-library-master $APP_ROOT/libraries/webwork-open-problem-library     && rm /tmp/opl.tar.gz     && curl -fSL https://github.com/mathjax/MathJax/archive/master.tar.gz -o /tmp/mathjax.tar.gz     && tar xzf /tmp/mathjax.tar.gz     && mv MathJax-master $APP_ROOT/MathJax     && rm /tmp/mathjax.tar.gz     && rm /tmp/VERSION' returned a non-zero code: 3
PS D:\webwork_docker\webwork2> docker-compose up

Arnie

**Comment by apizer** [comment]
Looking a bit closer, it looks like in 
Step 26/36 : RUN WEBWORK_VERSION=cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p' && curl -fSL 

it is hard coded to look for a develop version (although not sure what the above actually does) and the documentation says to use rel-ww2.14.  In any case someone who knows what is going on should look at this before it gets pulled into master.

**Comment by apizer** [comment]
Actually this may be the same as Issue #836 below.

**Comment by apizer** [comment]
Believing the issue has to do with looking for the wrong version, I tried the following. I edited Dockerfile as follows:

Around line 25 replace
ENV DEV 0

RUN apt-get update \

by
ENV DEV 0
ENV WEBWORK_VERSION rel-ww2.14
ENV PG_VERSION rel-PG-2.14

RUN apt-get update \

Around line 83 replace

RUN WEBWORK_VERSION=`cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p'` \
    && curl -fSL https://github.com/openwebwork/pg/archive/${WEBWORK_VERSION}.tar.gz -o /tmp/${WEBWORK_VERSION}.tar.gz \
    && tar xzf /tmp/${WEBWORK_VERSION}.tar.gz \
    && mv pg-${WEBWORK_VERSION} $APP_ROOT/pg \
    && rm /tmp/${WEBWORK_VERSION}.tar.gz \

by

RUN WEBWORK_VERSION_bad=`cat /tmp/VERSION|sed -n 's/.*\(develop\)'\'';/\1/p' && cat /tmp/VERSION|sed -n 's/.*\([0-9]\.[0-9]*\)'\'';/PG\-\1/p'` \
    && curl -fSL https://github.com/openwebwork/pg/archive/${PG_VERSION}.tar.gz -o /tmp/${PG_VERSION}.tar.gz \
    && tar xzf /tmp/${PG_VERSION}.tar.gz \
    && mv pg-${PG_VERSION} $APP_ROOT/pg \
    && rm /tmp/${PG_VERSION}.tar.gz \

Then the process got much further but eventually failed with a db error:

Successfully tagged webwork:latest
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating webwork2_db_1 ... error
Creating webwork2_r_1  ... done

ERROR: for webwork2_db_1  Cannot create container for service db: b'Drive has not been shared'

ERROR: for db  Cannot create container for service db: b'Drive has not been shared'
ERROR: Encountered errors while bringing up the project.

Think I'll let someone try testing this on windows.

Arnie

**Comment by taniwallach** [comment]
I think the revised docker control files and install instructions in my comment to PR https://github.com/openwebwork/webwork2/pull/865 should solve the problems reported above.
