### ISSUE TITLE
Docker newbie instructons typo

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#885]
The Docker newbie instructions at:
https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions

start out with a folder `webwork_docker` and at some point the references turn into `webwork-docker`.

**Comment by Alex-Jordan** [comment]
Should I just take liberty to edit the instructions if I'm sure it is a good edit? I see another thing I would change (as I experience the instructions as a user).

**Comment by mgage** [comment]
Sure.  Go ahead.  I just haven’t gotten a chance yet to make the changes that you suggested.    Thanks.

Let me know if there is a major mistake that I should be aware of.

Take care,

mike

**Comment by Alex-Jordan** [comment]
I got confused about running nginx. Am I right to think that has nothing to do with getting WBWK running? If so, I'll add something about clearing away everything right when the "Docker commands" section starts. Not sure if it's necessary, but it could make people feel on firmer footing.

**Comment by pstaabp** [comment]
This has been fixed.
