### ISSUE TITLE
CAS module for Webwork

### ISSUE THREAD

**Issue by pguerr061703** [openwebwork/webwork2#897]
Can someone let me know if CAS works on Webwork 2.12?  I need to configure it for authentication on our Webworks application server, but I do not know how. Its currently running on Ubuntu 16.04. Any help would be greatly appreciated.

This document says its under development:
http://webwork.maa.org/wiki/Authentication#Authen::MercedCAS

However others seem to have got it to work.
http://webwork.maa.org/moodle/mod/forum/discuss.php?d=2859

**Comment by pstaabp** [comment]
Closing this.  We have a fix for CAS for 2.18
