### ISSUE TITLE
Webwork Main Menu not shown

### ISSUE THREAD

**Issue by pguerr061703** [openwebwork/webwork2#898]
I installed webwork 2.13 on a Ubuntu server. I set the admin password for course administration, and i set the admin password for the math course that I copied from another server.
When I log in as admin, I don't see the "Main Menu". Its not there. I'm a newbie with Webwork. Is there a way to display the main menu?? I cannot add/create users, use file manager..etc without the "Main Menu" shown.
Any help would be greatly appreciated.

**Comment by mgage** [comment]
You might want to ask this on the forum -- you'll get a wider range of responses. 
either http://webwork.maa.org/moodle/mod/forum/view.php?f=4 or 
http://webwork.maa.org/moodle/mod/forum/view.php?f=2. (you need to register on the 
wiki http://webwork.maa.org/wiki before you are allowed to post)

Are you logging in to the course.   admin?    myserver.edu/webwork2/admin?    (this course behaves a little differently -- you don't usually add users and problem sets to it but use it to create other "regular" courses.   If the menu is missing from the left hand side, have you tried widening the window to see if it appears?

-- Mike

**Comment by mgage** [comment]
Has anyone been able to duplicate this behavior?  If not I'll close this issue.

**Comment by julianrosen** [comment]
I see this behavior when I install Webwork 2.16 on Ubuntu server 20.04 and 21.04.

**Comment by dlglin** [comment]
I ran into this when I upgraded to 2.16 due to the change in how WeBWorK is serving javascript.  There are two things to check:

1. Make sure you installed the new javascript using the "npm install" command described in the installation instructions.
2. Clear your browser cache to make sure it is pointing at the new javascript.  Usually a shift-reload in the page in question will accomplish this.

**Comment by julianrosen** [comment]
Thank you, "npm install" fixed the issue. I had been looking at the (apparently outdated) installation guides at [https://webwork.maa.org/wiki/Manual_Installation_Guides](https://webwork.maa.org/wiki/Manual_Installation_Guides), which did not mention npm.

**Comment by drgrice1** [comment]
This issue is no longer valid.
