### ISSUE TITLE
Refreshing page resubmits answers

### ISSUE THREAD

**Issue by glennricster** [openwebwork/webwork2#901]
If a student submits an answer on a problem, and then refreshes the page after the problem reloads with the results and confirms form resubmission, then the browser will resubmit the form from its cache. The server then grades the problem again and adds an attempt on the problem. So one of the students' attempts on the problem is wasted.

Of course that is only a problem if the problem is set up with a limited number of attempts. However, things get worse if the course is set up to request a new version of the problem after a certain number of attempts. In this case, if the student submits answers until the "Request New Version" button appears and then refreshes the page and confirms form resubmission, the server will still grade the problem again and increment the number of attempts and reload that same problem again with 2 more attempts left. A new seed and problem is not generated. Using this the student can effectively work the same problem an unlimited number of times.

**Comment by taniwallach** [comment]
@drgrice1 - I think this issue can be closed, as https://github.com/openwebwork/webwork2/pull/1003 fixes the problem for WW 2.15.

**Comment by drgrice1** [comment]
Yep. Closing.
