### ISSUE TITLE
installing webwork in docker gives errors in the master branch 

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#903]
I'm reviewing installing webwork in docker using the files in master. I'm getting errors. 
#890 
For example at the end of "docker build ." I get this error.

The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends --no-install-suggests apache2 curl dvipng gcc libapache2-request-perl libcrypt-ssleay-perl libdatetime-perl libdancer-perl libdancer-plugin-database-perl libdbd-mysql-perl libemail-address-perl libexception-class-perl libextutils-xsbuilder-perl libfile-find-rule-perl-perl libgd-perl libhtml-scrubber-perl libjson-perl liblocale-maketext-lexicon-perl libmail-sender-perl libmime-tools-perl libnet-ip-perl libnet-ldap-perl libnet-oauth-perl libossp-uuid-perl libpadwalker-perl libpath-class-perl libphp-serialization-perl libsoap-lite-perl libsql-abstract-perl libstring-shellquote-perl libtemplate-perl libtext-csv-perl libtimedate-perl libuuid-tiny-perl libxml-parser-perl libxml-writer-perl libapache2-reload-perl make netpbm preview-latex-style texlive texlive-latex-extra libc6-dev git mysql-client && curl -Lk https://cpanmin.us | perl - App::cpanminus && cpanm install XML::Parser::EasyTree Iterator Iterator::Util Pod::WSDL Array::Utils HTML::Template XMLRPC::Lite Mail::Sender Email::Sender::Simple Data::Dump Statistics::R::IO && rm -fr /var/lib/apt/lists/* ./cpanm /root/.cpanm /tmp/*' returned a non-zero code: 1

Could some others try downloading the version currently in the master branch and help me locate the source of the errors?

I've been updating the install instructions at https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions
so you can follow what is written there -- skipping the initial introduction as appropriate.

**Comment by taniwallach** [comment]
I had no such problem getting a Docker image up from the updated master branch, but made two small tweaks to `docker-compose.yml` to avoid recreating the same image (and possibly messing up the existing image) and to avoid interfering with the named volume with mysql data which I did not want to overwrite or change. 

What I did:
```
cd /some_path/webwork2   #into a Git controlled webwork2 directory I could use for this test
git fetch

git checkout master
# Output:
#     Your branch is behind 'origin/master' by 204 commits, and can be fast-forwarded.
#        (use "git pull" to update your local branch)

git pull

git log
# Last listed commits are:
#     4c4fd092f994f76f68654db75216239c7519951e
#          Update reference to PG_BRANCH in Docker   config file.
#          Update dates in license and update version numbers
#     e42d124a5ecf95e3ec89e147057f41b6b9b0ffd9
#           Merge pull request #865 from openwebwork/rel-ww2.14
#           Rel ww2.14

vim docker-compose.yml
# Make 3 changes:
#    In `db:` section replace `- mysql:/var/lib/mysql` by `- mysqltmp:/var/lib/mysql`
#    In `app:` section replace `image: webwork` by `image: webworktmp`
#    In `volumes:` section replace `mysql:` by `mysqltmp:`

docker-compose build
# Ran with no real problems, but there were various debconf warnings, 
# and some warnings when color.c is compiled.
# Ended with "Successfully built 7c16641bb668" and "Successfully tagged webworktmp:latest"

cd ../ww-docker-data
sudo mv courses courses.REGULAR
# Move aside the the link to a shared courses directory which was there
cd ../webwork2

docker-compose up
```

Note: I had a file `webwork2/htdocs/DATA/tagging-taxonomy.json` in my webwork2 tree which was set up before, so `OPL-update` was not run on startup of the new Docker image.

Once all the 3 docker images were running, I could connect to `localhost:8080/webwork2` and then log in to the `Course Administration` site = `http://localhost:8080/webwork2/admin/`

**Comment by mgage** [comment]
I believe this issue is resolved.  Some of these comments may be useful if similar issues arise when installing via docker.

**Comment by heiderich** [comment]
@mgage How did you resolve the issue?
