### ISSUE TITLE
Collect internationalization/localization changes from forked repositories in particular from the CCDMD forks

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#914]
The CCDMD forks (focused on adding French support) of webwork2 and pg, and their repo has many "maketext" calls not in the current PR https://github.com/openwebwork/webwork2/pull/908 for UTF8 support, etc. The "maketext" calls and many other changes are probably relevant for the main internationalization/localization project.

There is also some initial support for a "maketext" type of behavior in some of the JavaScript files, much of which is apparently in commit https://github.com/openwebwork/webwork2/commit/e71babcd7f97a229e778b48426a5f14c6395e880 and in particular the files:
  * `htdocs/js/i18n/localize.js`
  * `htdocs/js/i18n/fr_CA.js`      
  * `htdocs/js/i18n/en.js`
which is something to examine. The need for such capabilities was discussed in https://github.com/openwebwork/webwork2/issues/781.

There is a need to figure out how to collect and "merge" the relevant code changes into the working branches for internationalization/localization, probably via pull requests to whatever is the current source branch of the most recent localization PR to webwork2 and/or pg.

@jutrembBDEB : 
  - Which of the CCDMD branches should be looked at to collect changes which should probably mostly be merged into the main webwork code?  
  - Can you or someone else possibly organize the relevant changes it into something ready to use as a PR to @mgage's  new_develop_candidate_01_01_2019 (the source of https://github.com/openwebwork/webwork2/pull/908)?

It is quite possible that other institutions running custom localized versions of WeBWorK also have code changes which would be helpful to review and merge as appropriate. Does someone know who to ask or which forks to examine?

Two cross-fork comparisons with the CCDMD code I looked at quickly:
  - https://github.com/mgage/webwork2/compare/new_develop_candidate_01_01_2019...CCDMD:CCDMD_H2018
  - https://github.com/openwebwork/pg/compare/PG-2.13...CCDMD:CCDMD_H2018

**Comment by drgrice1** [comment]
I am closing this.  Translations from any other forks at the time this issue was made are probably not valid anymore.  In general with the translations in Transifex, this is not an issue anymore anyway.
