### ISSUE TITLE
Multi-part answers are not properly stored in Gateway Quizzes

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#924]
Steps to reproduce:
Create a gateway quiz which includes a question that uses ans_array on a MathObject.  Enter an answer, then either preview, submit, or change pages (for multipage quizzes) in the quiz.  Both the last_answer field and the past_answers table will only contain the first element of the matrix.
See http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4549 for a MWE

It looks like this was fixed in homework mode (Problem.pm) with the creation of the process_and_log_answer function in ProblemUtil.pm, but the Gateway code was never updated to use this function.  Gateway code should probably be refactored to use the same function, but Gateways also store the type of submission (e.g. [submit], [preview] or [newpage]), so this would have to be considered, as well as testing the loading of past answers into answer blanks.

**Comment by glennricster** [comment]
This also causes a problem if the Gateway Quiz is set to show some of the problems on the page at a time.  If you change pages the additional answers for a multi answer problem are lost.  If you switch back to the page with that multi answer problem, then the additional parts are blank, and when the exam is graded those parts are of course grades wrong.

**Comment by mgage** [comment]
I believe that http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4598 (matrix answers disappearing) is probably related as well.

**Comment by mgage** [comment]
Pull requests #935 and #936 resolve this issue.
