### ISSUE TITLE
project to visit timezone issues (again) in develop

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#944]
* Importing set definition files created with "bad" short time-zone codes (like "IDT") does not work.
    *See https://github.com/openwebwork/webwork2/issues/928 where there is additional information.
    * Deleting the time zone code in the SDF file bypasses the problem.
    * A different solution is proposed in https://github.com/openwebwork/webwork2/pull/941. 
  * I don't think these are reasons to hold back on merging the PR into develop, but the first issue is something to be fixed before version 2.15 can be released.

**Comment by drgrice1** [comment]
This has been fixed.  If an invalid timezone is encountered, then a warning is issued, and the "America/New_York" timezone is used, but it does not fail.
