### ISSUE TITLE
Year 2038 bug - in use of timestamp in mySQL tables

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#952]
mySQL's `timestamp` is apparently still a 32-bit integer, so apparently suffers from the year 2038 bug: 

`timestamp` is used in 
  1. the `course_key` table (I think for the expiration time of the login key "cookie"), and
  2. the `course_past_answer` table (I think as the timestamp when the answer was submitted).

We have some time, but eventually unless mySQL/MariaDB fix this issue, these columns will need to be changed.

Background:
  - https://en.wikipedia.org/wiki/Year_2038_problem
  - https://mariadb.com/kb/en/library/timestamp/
  - https://stackoverflow.com/questions/36793545/year-2038-issue-64-bit-linux-os-php-mysql
  - https://stackoverflow.com/questions/2012589/php-mysql-year-2038-bug-what-is-it-how-to-solve-it
  - https://bugs.mysql.com/bug.php?id=12654

**Comment by drgrice1** [comment]
This issue as stated is not valid.  The information linked to refers to the mysql timestamp data type and mysql methods for working with that data type.  The timestamp data type is never used by webwork.  The issue does not apply to a column in a database that has the name "timestamp" but is of type "INT" or "BIGINT" which the columns that are referred to are.  Note that the "INT" type is 4 bytes and will have the year 2038 issue if it holds a value that represents a timestamp, but that only applies to the timestamp column in the past answers table.  This would be very easy to fix.

**Comment by taniwallach** [comment]
Sorry. You are certainly correct. I was still pretty new to WeBWorK back then, and messed up. Your https://github.com/openwebwork/webwork2/pull/2648 will fix the one column where the 4 byte INT column will run into the issue.
