### ISSUE TITLE
sendXMLRPC issue in 2.15 (beta) branch (when used from a webwork2 tree used to run a local Docker WW server)

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#955]
I am experiencing a **major** issue with `sendXMLRPC.pl` with the 2.15 (beta) branch when it is used from my `webwork2/clients` directory from **outside** my Docker container. 

(This issue does not occur when the command is run inside the Docker container, but there it is of far less value, as it cannot call a local browser, etc.)

The problem is that the `lib/WeBWorK/CourseEnvironment.pm` code expects to find pg at `/opt/webwork/pg` and that is not the actual location (on my system) and a `croak` is issued when the file is not found there.

In particular, running:
```
./sendXMLRPC.pl -b  t/input.pg
```
gives the **fatal** error messages:
```
Cannot read PG version file /opt/webwork/pg/VERSION at /data2/webwork_docker_USING/webwork2/../pg//lib/WeBWorK/PG/IO.pm line 20.
Compilation failed in require at /data2/webwork_docker_USING/webwork2/../pg//lib/WeBWorK/PG/Translator.pm line 16.
BEGIN failed--compilation aborted at /data2/webwork_docker_USING/webwork2/../pg//lib/WeBWorK/PG/Translator.pm line 16.
Compilation failed in require at /data2/webwork_docker_USING/webwork2/../pg//lib/PGloadfiles.pm line 76.
BEGIN failed--compilation aborted at /data2/webwork_docker_USING/webwork2/../pg//lib/PGloadfiles.pm line 76.
Compilation failed in require at /data2/webwork_docker_USING/webwork2/../pg//lib/PGcore.pm line 25.
BEGIN failed--compilation aborted at /data2/webwork_docker_USING/webwork2/../pg//lib/PGcore.pm line 25.
Compilation failed in require at /data2/webwork_docker_USING/webwork2/../pg//lib/WeBWorK/PG/ImageGenerator.pm line 30.
BEGIN failed--compilation aborted at /data2/webwork_docker_USING/webwork2/../pg//lib/WeBWorK/PG/ImageGenerator.pm line 30.
Compilation failed in require at /data2/webwork_docker_USING/webwork2/lib/WebworkClient.pm line 115.
BEGIN failed--compilation aborted at /data2/webwork_docker_USING/webwork2/lib/WebworkClient.pm line 115.
Compilation failed in require at ./sendXMLRPC.pl line 309.
BEGIN failed--compilation aborted at ./sendXMLRPC.pl line 309.
```

The problem is a result of how `lib/WeBWorK/CourseEnvironment.pm` is creating the expected file location for `pg/VERSION` (in the context I am working in) as it depends on a setting for the hash key `pg_dir` which is not properly set in my context (running in the `webwork2/clients` directory from **outside** the Docker container). (The setting is appropriate when `sendXMLRPC.pl` is run from inside the Docker container). 

The fatal error is caused by the `croak` line:
```
                croak "Cannot read PG version file $PG_version_file";
```
and the problem can by bypassed by commenting out that line, and as a safely measure manually setting a value for `PG_VERSION` just above/below the commented out `croak` line:
```
                $self->{PG_VERSION}="unknown";
```

I also was able to bypass the problem by adding fallback code to define a different expected location for the file. Just below the line:
```
        my $PG_version_file = $self->{'pg_dir'}."/VERSION";
```
I added:
```
        # Try a fallback location
        if ( !-r $PG_version_file ) {
          $PG_version_file = $self->{'webwork_dir'}."/../pg/VERSION";
        }
```
It seems that this fallback approach may be a reasonable long-term fix.

---

Other minor issues are triggering the following warnings:
```
"our" variable @path_list redeclared at ./sendXMLRPC.pl line 400.
"my" variable $credentials_string masks earlier declaration in same scope at ./sendXMLRPC.pl line 402.
"our" variable $UNIT_TESTS_ON redeclared at ./sendXMLRPC.pl line 567.
```

---

See also https://github.com/openwebwork/pg/pull/413 - where a different minor issue regarding the use of `sendXMLRPC.pl`  in the  2.15 (beta) branch is reported with a proposed fix.

**Comment by mgage** [comment]
Tani, would you submit a pull request to develop with your proposed long term fix?

Thanks. -- Mike

**Comment by taniwallach** [comment]
Fixed, including the minor issues by:
  - https://github.com/openwebwork/webwork2/pull/962
  - https://github.com/openwebwork/webwork2/pull/963
