### ISSUE TITLE
WW 2.15 RC (under Docker) + Ubuntu 19.04 or Debian 10 - problems with the library browser

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#974]
https://github.com/openwebwork/webwork2/pull/972 is moving the Docker base image (for the WW 2.15 branch) from Ubuntu 16.04 to Ubuntu 18.04, and everything I have tested seems fine.

However, I also tried upgrading the Docker base image to Ubuntu 19.04 (and changing nothing else). The library browser stops working, and the XMLRPC calls are timing out. I do not have time to look into that issue, but it does hint that WW 2.15 may not behave on Ubuntu 19.04 even outside Docker.

**Comment by heiderich** [comment]
I also experience such problems on Debian buster (outside of docker).

**Comment by heiderich** [comment]
Here are a few more details:

With 
https://github.com/openwebwork/webwork2/pull/948 (commit dae0c50539edc827c48a75e69748cdfa190b2c2c)
https://github.com/openwebwork/pg/pull/408 (commit https://github.com/openwebwork/pg/pull/408/commits/a79b70789603362c073e8124dd97e27fd4a02182)

I am getting the error message `183 setmaker.js: /webwork2/instructorXMLHandler: timeout` in a box in the browser once I try to select a subject. The apache2 error log shows the following:


```
There were a lot of errors
Errors:
 408 Request Timeout at /opt/webwork/webwork2/lib/WebworkClient.pm line 296.

 End Errors
xmlrpcCall to searchLib returned no result for
[Mon Aug 12 15:28:34.423412 2019] [perl:error] [pid 13594] [client
<CLIENT_IP_ADDRESS>:34366] [/webwork2/instructorXMLHandler] xmlrpcCall to
searchLib returned no result for \n * in
WeBWorK::ContentGenerator::instructorXMLHandler::content called at line
233 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm\n * in
WeBWorK::ContentGenerator::go called at line 384 of
/opt/webwork/webwork2/lib/WeBWorK.pm, referer:
https://<FQDN>/webwork2/<COURSENAME>/instructor/setmaker/?key=xVxjvnOj9Y5ezPo3LkJm8QIh22oYzs53&user=<USER>&effectiveUser=<USER>

```

**Comment by taniwallach** [comment]
This has apparently been fixed sometime...
The library browser on my servers running WW 2.15 and WW 2.16RC1 inside Docker containers running Ubuntu 20.04 work fine.
