### ISSUE TITLE
Small feature request: auto-check/uncheck checkboxes on edit of field

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#981]
When editing the dates for an individual student - if the checkbox is not marked, then the date does not get saved. Tabbing to a different field automatically checks the checkbox, but editing the field does not.

Teaching staff has complained that sometimes they forget to mark the checkbox to to tab to get it marked, and then fail to pay attention that their change did not get saved.

Could we make these type of checkboxes mark themselves as soon as the relevant field has a key-press, unless the field became empty?

**Comment by mgage** [comment]
I think that could be done at this point.  There are javascript commands for updating a field on “key up” which might be
appropriate.  At the time this was written I believe that updating on “leaveFocus” was the best you could do — hence
the current behavior.

Take care,
Mike


On Aug 6, 2019, at 4:16 AM, Nathan Wallach <notifications@github.com<mailto:notifications@github.com>> wrote:


When editing the dates for an individual student - if the checkbox is not marked, then the date does not get saved. Tabbing to a different field automatically checks the checkbox, but editing the field does not.

Teaching staff has complained that sometimes they forget to mark the checkbox to to tab to get it marked, and then fail to pay attention that their change did not get saved.

Could we make these type of checkboxes mark themselves as soon as the relevant field has a key-press, unless the field became empty?

**Comment by taniwallach** [comment]
> I think that could be done at this point. There are javascript commands for updating a field on “key up” which might be appropriate. At the time this was written I believe that updating on “leaveFocus” was the best you could do — hence the current behavior. 

I don't have time to work in this one now, but it annoyed someone enough to prompt me to file the issue.

If you have a volunteer to do it - we can get it in for WW 2.15 :smiley:  If not, it can wait.

**Comment by mgage** [comment]
I’m pretty sure this one will have to wait.  It’s good to have it filed as an issue however.

Perhaps someone will be inspired to start thinking about this and other javaScript/AJAX
tweaks for release 2.16 :-)

Mike

On Aug 6, 2019, at 1:17 PM, Nathan Wallach <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that could be done at this point. There are javascript commands for updating a field on “key up” which might be appropriate. At the time this was written I believe that updating on “leaveFocus” was the best you could do — hence the current behavior.

I don't have time to work in this one now, but it annoyed someone enough to prompt me to file the issue.

If you have a volunteer to do it - we can get it in for WW 2.15 😃 If not, it can wait.

**Comment by taniwallach** [comment]
Addressed and fixed in https://github.com/openwebwork/webwork2/pull/988 but the PR is being deferred for WW 2.16 and not being included in WW 2.15.
