### ISSUE TITLE
Disable autocorrect and autocapitalize on answer entry

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork2#996]
It seems like more and more browsers and devices automatically mangle user input in text input fields and textareas, by autocorrecting and automatically capitalizing "random" letters in the input.

For example, in the problem `UCSB/Stewart5_1_6/Stewart5_1_6_3.pg`, the accepted answer is either "y" or "n".  Today, a student emailed me that the problem cannot be answered, since both "y" and "n" get rejected.  What happened is, their browser autocapitalized their answer, so they were submitting "Y" and "N" instead.  There is an easy fix for that particular problem, but last week I had a tester pointing out that in an algebra problem where an expression simplified to just "x", trying to enter "x" on some browsers results in entering "X", which is incorrect.

There seems to be a way to disable this at least in some browsers, as described at https://davidwalsh.name/disable-autocorrect 

Would there be any problem with adding the `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"` tags to all answer input fields in WeBWorK?

(I was not sure whether this is a WeBWorK or PG issue)

**Comment by drgrice1** [comment]
This is done in pull request #423 in the pg repository.

**Comment by taniwallach** [comment]
@mgage - Can you draft someone to test the fix in Glenn's PR.

**Comment by taniwallach** [comment]
https://github.com/openwebwork/pg/pull/423 has been merged - so I am closing this issue.
